{
  "name": "imdepa_DirectLake",
  "id": "fe91dc94-e996-48dc-9cc7-93630895216c",
  "compatibilityLevel": 1604,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dStatus_pedido",
        "lineageTag": "2f8d2a83-0784-4faf-aa73-1ecb9dc90fb9",
        "sourceLineageTag": "[imdepa].[dStatus_pedido]",
        "columns": [
          {
            "name": "order_status",
            "dataType": "string",
            "sourceColumn": "order_status",
            "lineageTag": "e5a0e118-2a5e-4aab-b250-e2c2fe00929a",
            "sourceLineageTag": "order_status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "order_status_id",
            "dataType": "int64",
            "sourceColumn": "order_status_id",
            "formatString": "0",
            "lineageTag": "e87d9713-f6c2-44ea-87ba-0cc3b2fdce0c",
            "sourceLineageTag": "order_status_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dStatus_pedido",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dStatus_pedido",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "agg_last_login",
        "lineageTag": "58b69033-993e-4157-b0da-8afa91bad283",
        "sourceLineageTag": "[imdepa].[agg_last_login]",
        "columns": [
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "formatString": "0",
            "lineageTag": "e820004a-90f9-469b-8f32-763c59306d58",
            "sourceLineageTag": "account_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "days_since_last_login",
            "dataType": "int64",
            "sourceColumn": "days_since_last_login",
            "formatString": "0",
            "lineageTag": "6c99966a-c668-4651-8b05-5c0576e9ea33",
            "sourceLineageTag": "days_since_last_login",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "login_status",
            "dataType": "string",
            "sourceColumn": "login_status",
            "lineageTag": "bd97d2b6-36e4-489e-9890-ae869c156406",
            "sourceLineageTag": "login_status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "baa1226b-fb46-4c3a-a745-ec0fbc9c1158",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "agg_last_login",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "agg_last_login",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dGrupo_Cliente",
        "lineageTag": "79ebea88-dc62-4978-8d47-caccebe5166b",
        "sourceLineageTag": "[imdepa].[dGrupo_Cliente]",
        "columns": [
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "formatString": "0",
            "lineageTag": "b5c707d0-4afd-4ef6-bdc9-8a662f51f1b2",
            "sourceLineageTag": "account_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "document",
            "dataType": "string",
            "sourceColumn": "document",
            "lineageTag": "8425f6b2-8735-4a79-84ab-7f96445a6c5f",
            "sourceLineageTag": "document",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "lineageTag": "0a66d877-8928-450c-a07b-67fc5893c3db",
            "sourceLineageTag": "name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "customer_type",
            "dataType": "string",
            "sourceColumn": "customer_type",
            "lineageTag": "e719e310-dfaa-4cc1-a9bf-1cb8711e0d04",
            "sourceLineageTag": "customer_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "2f5d8aeb-7400-48a8-801f-cd3971aaf418",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "enable_group_display_in_registration",
            "dataType": "double",
            "sourceColumn": "enable_group_display_in_registration",
            "lineageTag": "f6ec3efb-09b9-44c6-bb8e-3084fb363cca",
            "sourceLineageTag": "enable_group_display_in_registration",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "customer_group_type",
            "dataType": "string",
            "sourceColumn": "customer_group_type",
            "lineageTag": "87ac3ca5-b4da-44dd-80c2-8705dc5d0b6d",
            "sourceLineageTag": "customer_group_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dGrupo_Cliente",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dGrupo_Cliente",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dCarteirizacao",
        "lineageTag": "4fefed84-11fe-4ef1-ab0d-9d5021e07b39",
        "sourceLineageTag": "[imdepa].[dCarteirizacao]",
        "columns": [
          {
            "name": "id_account_seller",
            "dataType": "int64",
            "sourceColumn": "id_account_seller",
            "formatString": "0",
            "lineageTag": "69d5694f-b019-46b0-b98a-40494d48a372",
            "sourceLineageTag": "id_account_seller",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "id_account_customer",
            "dataType": "int64",
            "sourceColumn": "id_account_customer",
            "formatString": "0",
            "lineageTag": "97fa1513-4821-45d6-adc1-9b39a04953c3",
            "sourceLineageTag": "id_account_customer",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "id_store",
            "dataType": "int64",
            "sourceColumn": "id_store",
            "formatString": "0",
            "lineageTag": "78476170-ec57-4eac-9481-8efb48cc84a8",
            "sourceLineageTag": "id_store",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dCarteirizacao",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dCarteirizacao",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "agg_last_purchase",
        "lineageTag": "912879a1-90bf-44b8-89a5-f77e1674ef16",
        "sourceLineageTag": "[imdepa].[agg_last_purchase]",
        "columns": [
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "formatString": "0",
            "lineageTag": "4a23f364-d304-49bd-8a6b-757c3d894f96",
            "sourceLineageTag": "account_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "days_since_last_purchase",
            "dataType": "int64",
            "sourceColumn": "days_since_last_purchase",
            "formatString": "0",
            "lineageTag": "4710132e-4237-47b6-811d-8da987cfe613",
            "sourceLineageTag": "days_since_last_purchase",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "plataform_status",
            "dataType": "string",
            "sourceColumn": "plataform_status",
            "lineageTag": "c7cff7ad-6258-48f7-a4e3-09d70c3fd998",
            "sourceLineageTag": "plataform_status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "cfd67e36-81d0-41a0-bee5-7ad22ce7b347",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "agg_last_purchase",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "agg_last_purchase",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dMetodo_pagamento",
        "lineageTag": "62a164d7-9d7a-4f30-9ca5-f46b75fd9b11",
        "sourceLineageTag": "[imdepa].[dMetodo_pagamento]",
        "columns": [
          {
            "name": "payment_method",
            "dataType": "string",
            "sourceColumn": "payment_method",
            "lineageTag": "4089a8b6-3e16-4645-b4c0-d2dfa793522e",
            "sourceLineageTag": "payment_method",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "payment_method_id",
            "dataType": "int64",
            "sourceColumn": "payment_method_id",
            "formatString": "0",
            "lineageTag": "75b75238-c9bb-4b35-b66c-5a0329c3e4cc",
            "sourceLineageTag": "payment_method_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dMetodo_pagamento",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dMetodo_pagamento",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dOfertas",
        "lineageTag": "521aab99-45b1-4aa6-bf92-793b6eb62153",
        "sourceLineageTag": "[imdepa].[dOfertas]",
        "columns": [
          {
            "name": "associate_id",
            "dataType": "int64",
            "sourceColumn": "associate_id",
            "formatString": "0",
            "lineageTag": "5dc4f521-a403-422b-93c2-d5e4d35ee130",
            "sourceLineageTag": "associate_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "partner_id",
            "dataType": "int64",
            "sourceColumn": "partner_id",
            "formatString": "0",
            "lineageTag": "f621469c-2a80-464a-99b9-1f713d17495d",
            "sourceLineageTag": "partner_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sku_id",
            "dataType": "int64",
            "sourceColumn": "sku_id",
            "formatString": "0",
            "lineageTag": "20c04c80-4285-4519-a342-0f6c7b0e560d",
            "sourceLineageTag": "sku_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "company_name",
            "dataType": "string",
            "sourceColumn": "company_name",
            "lineageTag": "f4f4b430-8d90-4ec2-8ee1-691de9261809",
            "sourceLineageTag": "company_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mfr_part_code",
            "dataType": "string",
            "sourceColumn": "mfr_part_code",
            "lineageTag": "2dcae1d3-d2ae-482a-8143-cae848afac3d",
            "sourceLineageTag": "mfr_part_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sku_name",
            "dataType": "string",
            "sourceColumn": "sku_name",
            "lineageTag": "4ebfdfc9-55f5-4f58-8dbc-a6c7b39afca9",
            "sourceLineageTag": "sku_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "5f86b0e6-0622-4f8d-b4a0-c2917d520d5d",
            "sourceLineageTag": "datekey",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "quantity_avaliable",
            "dataType": "int64",
            "sourceColumn": "quantity_avaliable",
            "formatString": "0",
            "lineageTag": "0480a726-5ed0-4305-9cb7-b53564a875ac",
            "sourceLineageTag": "quantity_avaliable",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "unit_price",
            "dataType": "decimal",
            "sourceColumn": "unit_price",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "8a08cc2a-7ee3-40e0-835f-dbd3b2ded848",
            "sourceLineageTag": "unit_price",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "partner_part_code",
            "dataType": "string",
            "sourceColumn": "partner_part_code",
            "lineageTag": "cedc3581-457d-460c-82e2-d529058ab3fc",
            "sourceLineageTag": "partner_part_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sku_created_date",
            "dataType": "dateTime",
            "sourceColumn": "sku_created_date",
            "formatString": "General Date",
            "lineageTag": "063fc400-514e-417a-b690-d53e457f3e26",
            "sourceLineageTag": "sku_created_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sku_last_updated",
            "dataType": "dateTime",
            "sourceColumn": "sku_last_updated",
            "formatString": "General Date",
            "lineageTag": "3620771c-69e9-4f0a-854c-df853636ef63",
            "sourceLineageTag": "sku_last_updated",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "by_request",
            "dataType": "int64",
            "sourceColumn": "by_request",
            "formatString": "0",
            "lineageTag": "ab30e6ae-b7e1-42ee-90b7-8ed086101133",
            "sourceLineageTag": "by_request",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dOfertas",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dOfertas",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dProdutos",
        "lineageTag": "79084cd0-9d35-45c8-8efe-51941cc004fd",
        "sourceLineageTag": "[imdepa].[dProdutos]",
        "columns": [
          {
            "name": "sku_id",
            "dataType": "int64",
            "sourceColumn": "sku_id",
            "formatString": "0",
            "lineageTag": "54856747-48d7-4374-9a84-0d153d1869cd",
            "sourceLineageTag": "sku_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sku_name",
            "dataType": "string",
            "sourceColumn": "sku_name",
            "lineageTag": "f1428c36-3828-4a31-a8d9-243ee4ed57d7",
            "sourceLineageTag": "sku_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "manufacturer",
            "dataType": "string",
            "sourceColumn": "manufacturer",
            "lineageTag": "ed65794f-5f82-4829-ab30-30be1f69d4fe",
            "sourceLineageTag": "manufacturer",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mfr_part_code",
            "dataType": "string",
            "sourceColumn": "mfr_part_code",
            "lineageTag": "ce5789c3-5196-4209-8c8f-628b8c6a10b3",
            "sourceLineageTag": "mfr_part_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "category_level_1",
            "dataType": "string",
            "sourceColumn": "category_level_1",
            "lineageTag": "d64c753b-9e74-4bfe-b974-b0ecbc3fdbb9",
            "sourceLineageTag": "category_level_1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "category_level_2",
            "dataType": "string",
            "sourceColumn": "category_level_2",
            "lineageTag": "fe9b8025-38c8-4cf6-9aff-a540f37dfff5",
            "sourceLineageTag": "category_level_2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "category_level_3",
            "dataType": "string",
            "sourceColumn": "category_level_3",
            "lineageTag": "f1b330d1-e20b-47b2-9682-a2db84b08118",
            "sourceLineageTag": "category_level_3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "nivel",
            "dataType": "string",
            "sourceColumn": "nivel",
            "lineageTag": "72b174ec-b8df-4b5a-bab0-d191e08913c4",
            "sourceLineageTag": "nivel",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dProdutos",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dProdutos",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dTipo_pedido",
        "lineageTag": "213b4aa4-50a7-4b98-ac81-fad315b473d6",
        "sourceLineageTag": "[imdepa].[dTipo_pedido]",
        "columns": [
          {
            "name": "order_type",
            "dataType": "string",
            "sourceColumn": "order_type",
            "lineageTag": "889beb1c-afa9-4e37-a234-bd991c480977",
            "sourceLineageTag": "order_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "order_type_id",
            "dataType": "int64",
            "sourceColumn": "order_type_id",
            "formatString": "0",
            "lineageTag": "f5dd366c-9fda-4496-8246-514c9afc9927",
            "sourceLineageTag": "order_type_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dTipo_pedido",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dTipo_pedido",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dVendedores",
        "lineageTag": "4f388db7-3ebf-4f85-8957-4ec35a44ba82",
        "sourceLineageTag": "[imdepa].[dVendedores]",
        "columns": [
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "formatString": "0",
            "lineageTag": "a6586f67-a51b-487c-82d6-7e0f587c06d3",
            "sourceLineageTag": "account_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_create_date",
            "dataType": "dateTime",
            "sourceColumn": "account_create_date",
            "formatString": "General Date",
            "lineageTag": "fd98a12c-32ca-4702-945b-915ac0348140",
            "sourceLineageTag": "account_create_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_id",
            "dataType": "int64",
            "sourceColumn": "client_id",
            "formatString": "0",
            "lineageTag": "0a92039d-4245-46a8-81df-703e1dd09da8",
            "sourceLineageTag": "client_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_create_date",
            "dataType": "dateTime",
            "sourceColumn": "client_create_date",
            "formatString": "General Date",
            "lineageTag": "071358ca-092f-4eaf-ae89-4fb241cdd90c",
            "sourceLineageTag": "client_create_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "lineageTag": "9cf56108-5967-4bb6-a844-dd1a619988fb",
            "sourceLineageTag": "name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "first_name",
            "dataType": "string",
            "sourceColumn": "first_name",
            "lineageTag": "d8c6262c-c1ee-4d1b-9059-ab451c5c4a6c",
            "sourceLineageTag": "first_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "zip_code",
            "dataType": "string",
            "sourceColumn": "zip_code",
            "lineageTag": "c9e65979-8b8a-4327-9f92-52f0778296b1",
            "sourceLineageTag": "zip_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "phone_number",
            "dataType": "string",
            "sourceColumn": "phone_number",
            "lineageTag": "ee5c1db9-4d2e-451f-92c6-e17ded52a74b",
            "sourceLineageTag": "phone_number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "740ba2d3-2d89-4aae-9c4c-57691d947469",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "profile_picture",
            "dataType": "string",
            "sourceColumn": "profile_picture",
            "lineageTag": "8cf75dad-6d55-4697-8c93-586530c0b850",
            "sourceLineageTag": "profile_picture",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "ff1de9d2-622f-4ce7-9f25-a04eb8a96440",
            "sourceLineageTag": "datekey",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "age",
            "dataType": "int64",
            "sourceColumn": "age",
            "formatString": "0",
            "lineageTag": "2a0e833b-bc87-41db-bae7-bdb0a03cd395",
            "sourceLineageTag": "age",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "lineageTag": "9128f3e7-5c11-4fca-b6b3-9c80c99cbd04",
            "sourceLineageTag": "country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UF",
            "dataType": "string",
            "sourceColumn": "UF",
            "lineageTag": "fb961866-169b-4bc3-9bbd-9c525bbb4526",
            "sourceLineageTag": "UF",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "state",
            "dataType": "string",
            "sourceColumn": "state",
            "lineageTag": "caae4f96-3f4a-419e-9d4f-4a7bdf90aba0",
            "sourceLineageTag": "state",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "lineageTag": "da556562-40c1-455a-a153-66f00cf2ffb0",
            "sourceLineageTag": "region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city",
            "lineageTag": "17e21b58-6e5a-4a96-9ea5-be3fa96fe06d",
            "sourceLineageTag": "city",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "last_name",
            "dataType": "string",
            "sourceColumn": "last_name",
            "lineageTag": "1e1336b6-4b22-428f-a9c3-750b00dd15fd",
            "sourceLineageTag": "last_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "contact",
            "dataType": "string",
            "sourceColumn": "contact",
            "lineageTag": "7e7171e5-3856-4035-aa06-cb5c3012eb39",
            "sourceLineageTag": "contact",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_user",
            "dataType": "string",
            "sourceColumn": "account_user",
            "lineageTag": "76e0cea8-694a-4767-b258-b8b7f74d9888",
            "sourceLineageTag": "account_user",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "document",
            "dataType": "string",
            "sourceColumn": "document",
            "lineageTag": "749c27cc-ef85-44bb-8b3a-daf4c49b6984",
            "sourceLineageTag": "document",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "gender",
            "dataType": "string",
            "sourceColumn": "gender",
            "lineageTag": "de0fcec3-9183-4773-9401-15f660b01c27",
            "sourceLineageTag": "gender",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "person_type",
            "dataType": "string",
            "sourceColumn": "person_type",
            "lineageTag": "afd28921-096e-4d67-ba45-96199c23b7fd",
            "sourceLineageTag": "person_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dVendedores",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dVendedores",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "fVendas",
        "lineageTag": "a87d1ec2-0a75-4baa-b2de-15788aecbc6e",
        "sourceLineageTag": "[imdepa].[fVendas]",
        "columns": [
          {
            "name": "partner_order_id",
            "dataType": "int64",
            "sourceColumn": "partner_order_id",
            "formatString": "0",
            "lineageTag": "3812cbbe-6004-49e1-a7da-58ee2e4333bb",
            "sourceLineageTag": "partner_order_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "cart_order_id",
            "dataType": "int64",
            "sourceColumn": "cart_order_id",
            "formatString": "0",
            "lineageTag": "b7da07e9-c6d8-4e6f-9072-b8863b2dc5df",
            "sourceLineageTag": "cart_order_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "order_subtotal",
            "dataType": "decimal",
            "sourceColumn": "order_subtotal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "34828c9a-ebec-4e8f-89f0-93d8a57d9d18",
            "sourceLineageTag": "order_subtotal",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "order_total",
            "dataType": "decimal",
            "sourceColumn": "order_total",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "c2724281-eab2-47bd-a89e-6c5685a5837c",
            "sourceLineageTag": "order_total",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "discount_value",
            "dataType": "decimal",
            "sourceColumn": "discount_value",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "81af93e5-91f4-456a-975d-06c5fc90d393",
            "sourceLineageTag": "discount_value",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "order_status_id",
            "dataType": "int64",
            "sourceColumn": "order_status_id",
            "formatString": "0",
            "lineageTag": "535e668b-654f-4f7e-99bc-5736135f76db",
            "sourceLineageTag": "order_status_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "5225d562-df4b-4b37-919e-99cf0643e2e3",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "a206fb04-0800-43ef-bd15-4f97a1397bd9",
            "sourceLineageTag": "datekey",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey_faturamento",
            "dataType": "int64",
            "sourceColumn": "datekey_faturamento",
            "formatString": "0",
            "lineageTag": "5cf1f84e-767d-4bf6-beac-810261e15683",
            "sourceLineageTag": "datekey_faturamento",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "invoice",
            "dataType": "string",
            "sourceColumn": "invoice",
            "lineageTag": "bf99d676-7257-46b4-8e94-466c8f991779",
            "sourceLineageTag": "invoice",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_account_id",
            "dataType": "int64",
            "sourceColumn": "client_account_id",
            "formatString": "0",
            "lineageTag": "11ce0bc3-61a7-4992-abe8-5f0fea87b66f",
            "sourceLineageTag": "client_account_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "salesperson_account_id",
            "dataType": "int64",
            "sourceColumn": "salesperson_account_id",
            "formatString": "0",
            "lineageTag": "74a65084-b1e1-418a-8238-01692e149f91",
            "sourceLineageTag": "salesperson_account_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "salesperson_document",
            "dataType": "string",
            "sourceColumn": "salesperson_document",
            "lineageTag": "9de5db94-2425-41ba-93f4-a6212efbc24d",
            "sourceLineageTag": "salesperson_document",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "marketplace",
            "dataType": "string",
            "sourceColumn": "marketplace",
            "lineageTag": "f7152b0e-2836-4fb4-9674-0a3ab006c26a",
            "sourceLineageTag": "marketplace",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "partner_id",
            "dataType": "int64",
            "sourceColumn": "partner_id",
            "formatString": "0",
            "lineageTag": "379eb1f9-62cd-4b23-bfde-f569d15707e9",
            "sourceLineageTag": "partner_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "amount_charged",
            "dataType": "decimal",
            "sourceColumn": "amount_charged",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "566feab5-84f1-48c6-a531-278ace4b1a3e",
            "sourceLineageTag": "amount_charged",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "unit_price",
            "dataType": "decimal",
            "sourceColumn": "unit_price",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "8c6118e1-1fe3-44f0-88ae-fdffb5b3e84f",
            "sourceLineageTag": "unit_price",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "median_charged_shipping",
            "dataType": "decimal",
            "sourceColumn": "median_charged_shipping",
            "formatString": "\"R$\"#,0;-\"R$\"#,0;\"R$\"#,0",
            "lineageTag": "6c9eeeff-f6ff-4b9d-b18c-112b7f5eefe3",
            "sourceLineageTag": "median_charged_shipping",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ]
          },
          {
            "name": "avg_credit_card_interest",
            "dataType": "decimal",
            "sourceColumn": "avg_credit_card_interest",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "40de609a-3ece-4d1a-aece-3575b00af143",
            "sourceLineageTag": "avg_credit_card_interest",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "avg_total_tax",
            "dataType": "decimal",
            "sourceColumn": "avg_total_tax",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d6352cfe-56d3-4d5c-af9b-b334cf9a85ef",
            "sourceLineageTag": "avg_total_tax",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "coupon_id",
            "dataType": "int64",
            "sourceColumn": "coupon_id",
            "formatString": "0",
            "lineageTag": "5a3ae7f2-b6c2-4637-9a24-d18c0cac8054",
            "sourceLineageTag": "coupon_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "order_type_id",
            "dataType": "int64",
            "sourceColumn": "order_type_id",
            "formatString": "0",
            "lineageTag": "742fb2d1-edda-49a3-9b41-b45fdab188a5",
            "sourceLineageTag": "order_type_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "device_id",
            "dataType": "int64",
            "sourceColumn": "device_id",
            "formatString": "0",
            "lineageTag": "50fe2281-2af6-4581-8124-72dcc3278c33",
            "sourceLineageTag": "device_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "payment_method_id",
            "dataType": "int64",
            "sourceColumn": "payment_method_id",
            "formatString": "0",
            "lineageTag": "c2a356cf-d52c-4d86-8a9c-475b0fe1b7e4",
            "sourceLineageTag": "payment_method_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "shipping_type_id",
            "dataType": "int64",
            "sourceColumn": "shipping_type_id",
            "formatString": "0",
            "lineageTag": "26c7e803-85ab-45eb-a820-b0e3a515a735",
            "sourceLineageTag": "shipping_type_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sku_id",
            "dataType": "int64",
            "sourceColumn": "sku_id",
            "formatString": "0",
            "lineageTag": "d5726ba6-a189-436d-9913-a2019e571b7d",
            "sourceLineageTag": "sku_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "quantity",
            "dataType": "int64",
            "sourceColumn": "quantity",
            "formatString": "0",
            "lineageTag": "0f9b8863-4fc6-41ec-a077-03056b6ddbe5",
            "sourceLineageTag": "quantity",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fVendas",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "fVendas",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "lineageTag": "c402c646-459a-4488-a6b4-4fe30bf2c094",
        "sourceLineageTag": "[imdepa].[dCalendario]",
        "columns": [
          {
            "name": "Hoje",
            "dataType": "boolean",
            "sourceColumn": "Hoje",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "5a3c03e5-66db-4302-9b37-1b9ee9078421",
            "sourceLineageTag": "Hoje",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "615ed536-d1c6-4411-a4f2-ab2091ec1071",
            "sourceLineageTag": "datekey",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AnoMes_Fechamento",
            "dataType": "int64",
            "sourceColumn": "AnoMes_Fechamento",
            "formatString": "0",
            "lineageTag": "e3cf1d15-bb98-4ef2-be5d-28c34f42710a",
            "sourceLineageTag": "AnoMes_Fechamento",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Feriado",
            "dataType": "string",
            "sourceColumn": "Feriado",
            "lineageTag": "783dd45a-a9de-446d-9c64-57fcc72cf72a",
            "sourceLineageTag": "Feriado",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Diatil",
            "dataType": "boolean",
            "sourceColumn": "Diatil",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "381602d8-323b-4927-9034-9141ca858ed9",
            "sourceLineageTag": "Diatil",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Semana_Ms",
            "dataType": "int64",
            "sourceColumn": "Semana_Ms",
            "formatString": "0",
            "lineageTag": "0e49c958-9621-4744-9d2e-f143c760c08b",
            "sourceLineageTag": "Semana_Ms",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ms_Atual",
            "dataType": "boolean",
            "sourceColumn": "Ms_Atual",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "366559a9-fbfd-4fd2-b40d-18b84736edf3",
            "sourceLineageTag": "Ms_Atual",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Semana_Atual",
            "dataType": "boolean",
            "sourceColumn": "Semana_Atual",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3385e925-05f1-4b32-bdc6-67b7817b923f",
            "sourceLineageTag": "Semana_Atual",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Offset_Trimestre",
            "dataType": "int64",
            "sourceColumn": "Offset_Trimestre",
            "formatString": "0",
            "lineageTag": "90c6406a-eb30-4540-9af9-22ce93a79d51",
            "sourceLineageTag": "Offset_Trimestre",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Offset_Ano",
            "dataType": "int64",
            "sourceColumn": "Offset_Ano",
            "formatString": "0",
            "lineageTag": "906cc253-58db-45fc-bc0c-b3e0c6cade0b",
            "sourceLineageTag": "Offset_Ano",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Semana_Completa",
            "dataType": "boolean",
            "sourceColumn": "Semana_Completa",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "91fd5fe0-8490-42df-a88b-ead4b44e7a65",
            "sourceLineageTag": "Semana_Completa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ms_Completo",
            "dataType": "boolean",
            "sourceColumn": "Ms_Completo",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ecc347c1-8a6f-4024-a738-33f13ddc1aa3",
            "sourceLineageTag": "Ms_Completo",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Trimestre_Completo",
            "dataType": "boolean",
            "sourceColumn": "Trimestre_Completo",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d60605cd-85bb-4768-9b64-4e8278b53943",
            "sourceLineageTag": "Trimestre_Completo",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ms/Ano_Fechamento",
            "dataType": "string",
            "sourceColumn": "Ms/Ano_Fechamento",
            "lineageTag": "76e33fdf-b9bb-4d16-b72a-e89827da2462",
            "sourceLineageTag": "Ms/Ano_Fechamento",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Trimestre_Fiscal",
            "dataType": "string",
            "sourceColumn": "Trimestre_Fiscal",
            "lineageTag": "a094b411-c6ce-4e7d-8daf-5b33018c8270",
            "sourceLineageTag": "Trimestre_Fiscal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ms_Fiscal",
            "dataType": "int64",
            "sourceColumn": "Ms_Fiscal",
            "formatString": "0",
            "lineageTag": "3351007c-71fe-4e95-90a7-bc55d9f13edb",
            "sourceLineageTag": "Ms_Fiscal",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Futuro",
            "dataType": "boolean",
            "sourceColumn": "Futuro",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "22090da1-7118-41cd-bb0a-d07313aaaba8",
            "sourceLineageTag": "Futuro",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Offset_Dia",
            "dataType": "int64",
            "sourceColumn": "Offset_Dia",
            "formatString": "0",
            "lineageTag": "b0bf6603-74c8-4851-841d-3ff3608af7b6",
            "sourceLineageTag": "Offset_Dia",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Offset_Semana",
            "dataType": "int64",
            "sourceColumn": "Offset_Semana",
            "formatString": "0",
            "lineageTag": "066178e4-acdf-4f2c-9f18-d3663ce641d0",
            "sourceLineageTag": "Offset_Semana",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Offset_Ms",
            "dataType": "int64",
            "sourceColumn": "Offset_Ms",
            "formatString": "0",
            "lineageTag": "97bde139-caa0-4c24-8a48-7089351695ab",
            "sourceLineageTag": "Offset_Ms",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Semana_Ano",
            "dataType": "int64",
            "sourceColumn": "Semana_Ano",
            "formatString": "0",
            "lineageTag": "7a88dce1-94ac-4463-aafe-db72e6f83a31",
            "sourceLineageTag": "Semana_Ano",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Semana/Ano",
            "dataType": "string",
            "sourceColumn": "Semana/Ano",
            "lineageTag": "b21360b3-c9a1-4161-872d-0410c158bfd3",
            "sourceLineageTag": "Semana/Ano",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AnoSemana",
            "dataType": "int64",
            "sourceColumn": "AnoSemana",
            "formatString": "0",
            "lineageTag": "d2574547-bbab-470e-a21e-4b470ff40c71",
            "sourceLineageTag": "AnoSemana",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AnoMes",
            "dataType": "int64",
            "sourceColumn": "AnoMes",
            "formatString": "0",
            "lineageTag": "e672d2d0-0a5e-4dbd-a7ff-e67e875e0ffc",
            "sourceLineageTag": "AnoMes",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AnoTrimestre",
            "dataType": "int64",
            "sourceColumn": "AnoTrimestre",
            "formatString": "0",
            "lineageTag": "37a15c71-6f51-4fb7-b0ec-f3cc220c6852",
            "sourceLineageTag": "AnoTrimestre",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AnoFiscal",
            "dataType": "string",
            "sourceColumn": "AnoFiscal",
            "lineageTag": "bcf0a026-a01c-48e9-9909-03460240e5e1",
            "sourceLineageTag": "AnoFiscal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ms",
            "dataType": "string",
            "sourceColumn": "Ms",
            "sortByColumn": "AnoMes",
            "lineageTag": "e402439d-4b2a-4195-9a6c-665ecc1fc875",
            "sourceLineageTag": "Ms",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ms/Ano",
            "dataType": "string",
            "sourceColumn": "Ms/Ano",
            "lineageTag": "ed00ce16-5884-4eb6-aea5-fd88a2f2f8b2",
            "sourceLineageTag": "Ms/Ano",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Trimestre/Ano",
            "dataType": "string",
            "sourceColumn": "Trimestre/Ano",
            "lineageTag": "b3aee50e-b0c4-4be8-8657-fa403c25f892",
            "sourceLineageTag": "Trimestre/Ano",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Dia_Semana",
            "dataType": "int64",
            "sourceColumn": "Dia_Semana",
            "formatString": "0",
            "lineageTag": "ddd66a2f-b033-41e0-b7f3-49a366a6e4d5",
            "sourceLineageTag": "Dia_Semana",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Nome_Dia",
            "dataType": "string",
            "sourceColumn": "Nome_Dia",
            "lineageTag": "79653ae8-3f71-49b8-a97d-80b35280cac5",
            "sourceLineageTag": "Nome_Dia",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Nome_Dia_abv",
            "dataType": "string",
            "sourceColumn": "Nome_Dia_abv",
            "lineageTag": "83eac87b-585e-4730-9862-ecb86a498dd1",
            "sourceLineageTag": "Nome_Dia_abv",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Data",
            "dataType": "dateTime",
            "sourceColumn": "Data",
            "formatString": "Short Date",
            "sortByColumn": "AnoMesDia",
            "lineageTag": "759139e4-274a-40eb-8f5d-72f914b4d099",
            "sourceLineageTag": "Data",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ano",
            "dataType": "int64",
            "sourceColumn": "Ano",
            "formatString": "0",
            "lineageTag": "42f369bd-19c5-47d7-8d47-74f3adfe6d35",
            "sourceLineageTag": "Ano",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Trimestre",
            "dataType": "int64",
            "sourceColumn": "Trimestre",
            "formatString": "0",
            "lineageTag": "01f5b85c-8c76-4ae8-b788-cefb5f7371d2",
            "sourceLineageTag": "Trimestre",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MesNo",
            "dataType": "int64",
            "sourceColumn": "MesNo",
            "formatString": "0",
            "lineageTag": "ff7a4737-0eb2-40fd-9420-86f740f65336",
            "sourceLineageTag": "MesNo",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Dia",
            "dataType": "int64",
            "sourceColumn": "Dia",
            "formatString": "0",
            "lineageTag": "4799784f-f4b8-4c4a-81df-75a9a11381dc",
            "sourceLineageTag": "Dia",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AnoMesDia",
            "dataType": "int64",
            "sourceColumn": "AnoMesDia",
            "formatString": "0",
            "lineageTag": "db918d4e-5ab5-45ba-80a4-a6df3c0500b7",
            "sourceLineageTag": "AnoMesDia",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dCalendario",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Data Hierarquia",
            "lineageTag": "e80a35d4-fc49-4278-ab1f-9cf17d380d87",
            "levels": [
              {
                "name": "Ano",
                "ordinal": 0,
                "column": "Ano",
                "lineageTag": "ae3c6783-b067-41d8-bd0e-d3909fcca485"
              },
              {
                "name": "Ms",
                "ordinal": 1,
                "column": "Ms",
                "lineageTag": "1c3c6ecd-b16b-4d67-ad35-a9b8fe75ee41"
              },
              {
                "name": "Dia",
                "ordinal": 2,
                "column": "Dia",
                "lineageTag": "973d1f3b-1650-4c9e-9bf5-2fd5da3245af"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ]
          }
        ]
      },
      {
        "name": "dTipo_envio",
        "lineageTag": "8d882799-d050-437f-91e5-c0369d6f3468",
        "sourceLineageTag": "[imdepa].[dTipo_envio]",
        "columns": [
          {
            "name": "shipping_type",
            "dataType": "string",
            "sourceColumn": "shipping_type",
            "lineageTag": "48b042c2-bb68-46ca-94b8-28cbfdc68d67",
            "sourceLineageTag": "shipping_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "shipping_type_id",
            "dataType": "int64",
            "sourceColumn": "shipping_type_id",
            "formatString": "0",
            "lineageTag": "03871a1b-d5a3-42d3-80ad-1b605b95b35a",
            "sourceLineageTag": "shipping_type_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dTipo_envio",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dTipo_envio",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dDispositivos",
        "lineageTag": "50611dc9-cc9b-4399-9fb6-2165d89a9788",
        "sourceLineageTag": "[imdepa].[dDispositivos]",
        "columns": [
          {
            "name": "device",
            "dataType": "string",
            "sourceColumn": "device",
            "lineageTag": "f44827aa-16de-4213-bf25-365a890ace4d",
            "sourceLineageTag": "device",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "device_id",
            "dataType": "int64",
            "sourceColumn": "device_id",
            "formatString": "0",
            "lineageTag": "f21ac5e0-018d-463d-967b-cd9027393e04",
            "sourceLineageTag": "device_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dDispositivos",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dDispositivos",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dFeriados",
        "lineageTag": "70fca2e6-2eed-49b3-a6f9-3d74bb4cf24b",
        "sourceLineageTag": "[imdepa].[dFeriados]",
        "columns": [
          {
            "name": "Data",
            "dataType": "dateTime",
            "sourceColumn": "Data",
            "formatString": "General Date",
            "lineageTag": "0c6ae2a3-addd-44cd-a058-01d17d9e4126",
            "sourceLineageTag": "Data",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Dia_Semana",
            "dataType": "string",
            "sourceColumn": "Dia_Semana",
            "lineageTag": "cb96592a-d450-4dd0-b6cc-604b2988610b",
            "sourceLineageTag": "Dia_Semana",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Feriado",
            "dataType": "string",
            "sourceColumn": "Feriado",
            "lineageTag": "2486e93e-6327-4a11-bc37-43a769fe4a41",
            "sourceLineageTag": "Feriado",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dFeriados",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dFeriados",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "fDatalayer_agg_pageviews",
        "lineageTag": "2afd34a6-5601-421c-97f6-bba2bb0462ba",
        "sourceLineageTag": "[imdepa].[fDatalayer_agg_pageviews]",
        "columns": [
          {
            "name": "min_datecreated_time",
            "dataType": "string",
            "sourceColumn": "min_datecreated_time",
            "lineageTag": "f3301d59-7a93-448a-ba6e-c8d6c22576c9",
            "sourceLineageTag": "min_datecreated_time",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "265fe007-0aa6-442e-8b98-df49ec6d6eab",
            "sourceLineageTag": "datekey",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "funil",
            "dataType": "string",
            "sourceColumn": "funil",
            "lineageTag": "5843ae73-4d65-4009-9e6e-f9634eb6f3ea",
            "sourceLineageTag": "funil",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sku_id",
            "dataType": "int64",
            "sourceColumn": "sku_id",
            "formatString": "0",
            "lineageTag": "b33d235e-7ad0-4c6b-9a79-b874a1886221",
            "sourceLineageTag": "sku_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "formatString": "0",
            "lineageTag": "8ed76558-90d1-464f-84d2-3c83187bc62f",
            "sourceLineageTag": "year",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "month",
            "dataType": "int64",
            "sourceColumn": "month",
            "formatString": "0",
            "lineageTag": "562a3818-b8f8-4164-a880-71b67975e0f9",
            "sourceLineageTag": "month",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sessoes_distintas",
            "dataType": "int64",
            "sourceColumn": "sessoes_distintas",
            "formatString": "0",
            "lineageTag": "16f169a9-e30f-497b-bdca-bf1f488de4cc",
            "sourceLineageTag": "sessoes_distintas",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey_max_datecreated",
            "dataType": "int64",
            "sourceColumn": "datekey_max_datecreated",
            "formatString": "0",
            "lineageTag": "00f5239b-a932-497a-ae10-78e57c699baf",
            "sourceLineageTag": "datekey_max_datecreated",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "max_datecreated_time",
            "dataType": "string",
            "sourceColumn": "max_datecreated_time",
            "lineageTag": "6f751fe4-a835-4f9a-bbc6-b0c39c382ac5",
            "sourceLineageTag": "max_datecreated_time",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey_min_datecreated",
            "dataType": "int64",
            "sourceColumn": "datekey_min_datecreated",
            "formatString": "0",
            "lineageTag": "3995a6cc-73fd-4724-a861-3aa12d0e09ed",
            "sourceLineageTag": "datekey_min_datecreated",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "visitor_id",
            "dataType": "int64",
            "sourceColumn": "visitor_id",
            "formatString": "0",
            "lineageTag": "ff770b16-10b5-4aca-9812-bf00e3af9765",
            "sourceLineageTag": "visitor_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "visitor_isloggedin",
            "dataType": "boolean",
            "sourceColumn": "visitor_isloggedin",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d5ed5683-d67b-47d0-8ef1-7670b06990f6",
            "sourceLineageTag": "visitor_isloggedin",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "vendor_id",
            "dataType": "int64",
            "sourceColumn": "vendor_id",
            "formatString": "0",
            "lineageTag": "1fabb0a2-16e0-4550-b823-825c682f2477",
            "sourceLineageTag": "vendor_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "vendor_isloggedin",
            "dataType": "boolean",
            "sourceColumn": "vendor_isloggedin",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "16adff1b-c964-4de8-bac0-ca2c97d8eb8f",
            "sourceLineageTag": "vendor_isloggedin",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "user_type",
            "dataType": "string",
            "sourceColumn": "user_type",
            "lineageTag": "7bab48ec-d04b-4777-af48-e70e5aefdeac",
            "sourceLineageTag": "user_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "pagepath",
            "dataType": "string",
            "sourceColumn": "pagepath",
            "lineageTag": "f7c8316b-b121-4bda-89af-41e76a363814",
            "sourceLineageTag": "pagepath",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "1b65d42c-ff38-4471-b7d8-003dcb7a6271",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "formatString": "0",
            "lineageTag": "66b887ad-d226-4628-8bd5-666aaed1d10c",
            "sourceLineageTag": "account_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fDatalayer_agg_pageviews",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "fDatalayer_agg_pageviews",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "fDatalayer_product_pageviews",
        "lineageTag": "3192d389-b2bc-49c7-85e7-38b09babc6a9",
        "sourceLineageTag": "[imdepa].[fDatalayer_product_pageviews]",
        "columns": [
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "2f8272c8-4ba3-4136-b6fd-619c98516eee",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "visitor_id",
            "dataType": "int64",
            "sourceColumn": "visitor_id",
            "formatString": "0",
            "lineageTag": "a3e35590-300a-4114-a2a2-0e0d797bd449",
            "sourceLineageTag": "visitor_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "visitor_email",
            "dataType": "string",
            "sourceColumn": "visitor_email",
            "lineageTag": "e83ed60c-6e3a-4058-85ef-146677b04efd",
            "sourceLineageTag": "visitor_email",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "visitor_isloggedin",
            "dataType": "boolean",
            "sourceColumn": "visitor_isloggedin",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "29c54c39-de66-4f6a-9432-5af879b1bd38",
            "sourceLineageTag": "visitor_isloggedin",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "vendor_id",
            "dataType": "int64",
            "sourceColumn": "vendor_id",
            "formatString": "0",
            "lineageTag": "6de195ff-0e9f-48ac-8a4e-9429070987d2",
            "sourceLineageTag": "vendor_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "vendor_email",
            "dataType": "string",
            "sourceColumn": "vendor_email",
            "lineageTag": "c483b5ac-0788-45e9-abd7-999e52d931ae",
            "sourceLineageTag": "vendor_email",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "min_datecreated_time",
            "dataType": "string",
            "sourceColumn": "min_datecreated_time",
            "lineageTag": "decf4962-0abf-4f07-8c75-9344dc112907",
            "sourceLineageTag": "min_datecreated_time",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "formatString": "0",
            "lineageTag": "5faa90cf-3278-43fb-b14d-4a0443498524",
            "sourceLineageTag": "account_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "35a602a5-8be4-49ad-9156-292babad7e6d",
            "sourceLineageTag": "datekey",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "vendor_isloggedin",
            "dataType": "boolean",
            "sourceColumn": "vendor_isloggedin",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ebafd683-7f0f-45e9-aa02-432602df3425",
            "sourceLineageTag": "vendor_isloggedin",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sku_id",
            "dataType": "int64",
            "sourceColumn": "sku_id",
            "formatString": "0",
            "lineageTag": "52e52e81-5b3f-4844-837a-b6c50aaaf17e",
            "sourceLineageTag": "sku_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "distinct_count_session",
            "dataType": "int64",
            "sourceColumn": "distinct_count_session",
            "formatString": "0",
            "lineageTag": "34476062-1608-4572-a439-904592cd2217",
            "sourceLineageTag": "distinct_count_session",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey_max_datecreated",
            "dataType": "int64",
            "sourceColumn": "datekey_max_datecreated",
            "formatString": "0",
            "lineageTag": "bc571dc2-a6b2-484b-b80b-f891210c1da9",
            "sourceLineageTag": "datekey_max_datecreated",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "max_datecreated_time",
            "dataType": "string",
            "sourceColumn": "max_datecreated_time",
            "lineageTag": "6591cef7-c038-48a0-87b9-b6a2fb495a85",
            "sourceLineageTag": "max_datecreated_time",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey_min_datecreated",
            "dataType": "int64",
            "sourceColumn": "datekey_min_datecreated",
            "formatString": "0",
            "lineageTag": "ef681804-b0aa-4b9a-bf6c-45c8b0dde0d4",
            "sourceLineageTag": "datekey_min_datecreated",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fDatalayer_product_pageviews",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "fDatalayer_product_pageviews",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dClientes",
        "lineageTag": "cb2a43eb-94d6-4bbd-8c5d-6eba0e3bcda6",
        "sourceLineageTag": "[imdepa].[dClientes]",
        "columns": [
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "formatString": "0",
            "lineageTag": "c01c00f8-8789-4f49-8c56-e5850ab5430d",
            "sourceLineageTag": "account_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_create_date",
            "dataType": "dateTime",
            "sourceColumn": "account_create_date",
            "formatString": "General Date",
            "lineageTag": "19ddf78a-5c62-456a-811f-e5a518b50900",
            "sourceLineageTag": "account_create_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_id",
            "dataType": "int64",
            "sourceColumn": "client_id",
            "formatString": "0",
            "lineageTag": "08b05b56-2882-4b8d-8c63-aee38cc41fc6",
            "sourceLineageTag": "client_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_status",
            "dataType": "boolean",
            "sourceColumn": "client_status",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f21342b8-4dd7-4922-a368-952c3e29cea6",
            "sourceLineageTag": "client_status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_origin",
            "dataType": "string",
            "sourceColumn": "account_origin",
            "lineageTag": "41ac78b1-ef77-4643-ba4b-9306b67e47ed",
            "sourceLineageTag": "account_origin",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_create_date",
            "dataType": "dateTime",
            "sourceColumn": "client_create_date",
            "formatString": "General Date",
            "lineageTag": "222aec9b-6c62-4eb1-955c-6daec75bc225",
            "sourceLineageTag": "client_create_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "total_credit_limit",
            "dataType": "decimal",
            "sourceColumn": "total_credit_limit",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "79966d53-0865-481d-baea-d32d4e1494fe",
            "sourceLineageTag": "total_credit_limit",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "credit_balance",
            "dataType": "decimal",
            "sourceColumn": "credit_balance",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "159100dd-40a5-4869-9c37-1ff7bff5ca58",
            "sourceLineageTag": "credit_balance",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "8cdd5e25-85bf-4918-98dd-909bf8aa8b37",
            "sourceLineageTag": "datekey",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "salesperson_account_id",
            "dataType": "int64",
            "sourceColumn": "salesperson_account_id",
            "formatString": "0",
            "lineageTag": "6929bad9-de5c-47f8-bb76-3dad8fa5047c",
            "sourceLineageTag": "salesperson_account_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "salesperson_document",
            "dataType": "string",
            "sourceColumn": "salesperson_document",
            "lineageTag": "fc60039e-18d4-4c7c-99ef-fe4e59995561",
            "sourceLineageTag": "salesperson_document",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "07c576ca-54cb-41fa-b9e3-f36fe30cf739",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_last_updated",
            "dataType": "dateTime",
            "sourceColumn": "client_last_updated",
            "formatString": "General Date",
            "lineageTag": "45e5c7bb-f50d-4627-9cf3-b547e7f1c300",
            "sourceLineageTag": "client_last_updated",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "profile_picture",
            "dataType": "string",
            "sourceColumn": "profile_picture",
            "lineageTag": "48903726-35fb-4f0b-a2eb-c98923fabe4b",
            "sourceLineageTag": "profile_picture",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "line",
            "dataType": "int64",
            "sourceColumn": "line",
            "formatString": "0",
            "lineageTag": "dab871ea-4d81-4492-8846-abc976de3716",
            "sourceLineageTag": "line",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city",
            "lineageTag": "8ecbf6ae-f407-4009-9be7-b5adbe106545",
            "sourceLineageTag": "city",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "zip_code",
            "dataType": "string",
            "sourceColumn": "zip_code",
            "lineageTag": "82fd4f52-d568-46a6-88c4-26b526f13ce9",
            "sourceLineageTag": "zip_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "phone_number",
            "dataType": "string",
            "sourceColumn": "phone_number",
            "lineageTag": "1d19dbf9-c06b-457f-8650-3686828efde3",
            "sourceLineageTag": "phone_number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CNAE",
            "dataType": "string",
            "sourceColumn": "CNAE",
            "lineageTag": "23f32946-9baf-4651-8df4-b8c7c955cf10",
            "sourceLineageTag": "CNAE",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "wpp_phone",
            "dataType": "string",
            "sourceColumn": "wpp_phone",
            "lineageTag": "29f65208-7ba8-4e10-829d-44240471b32b",
            "sourceLineageTag": "wpp_phone",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "wpp_opt_in",
            "dataType": "int64",
            "sourceColumn": "wpp_opt_in",
            "formatString": "0",
            "lineageTag": "78bafe6e-dac7-454d-b560-ff8b0574aa02",
            "sourceLineageTag": "wpp_opt_in",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "person_type",
            "dataType": "string",
            "sourceColumn": "person_type",
            "lineageTag": "f19e905b-3763-4d8b-a24b-bf6eba5edcbc",
            "sourceLineageTag": "person_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "age",
            "dataType": "int64",
            "sourceColumn": "age",
            "formatString": "0",
            "lineageTag": "5796809d-adbe-476b-b8fa-d03dccff38df",
            "sourceLineageTag": "age",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "lineageTag": "0163e138-091d-43ba-a314-f5980cc71854",
            "sourceLineageTag": "country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UF",
            "dataType": "string",
            "sourceColumn": "UF",
            "lineageTag": "e176e617-9e88-43c5-a99c-7254cc4e10b2",
            "sourceLineageTag": "UF",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "state",
            "dataType": "string",
            "sourceColumn": "state",
            "lineageTag": "49e31a65-b66c-4d26-af62-a87987aaf34c",
            "sourceLineageTag": "state",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "lineageTag": "0b418939-1450-4a13-8643-8e7d594a68dc",
            "sourceLineageTag": "region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "lineageTag": "f7fe38d0-7109-44b9-9aa1-a161cccb648d",
            "sourceLineageTag": "name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "contact",
            "dataType": "string",
            "sourceColumn": "contact",
            "lineageTag": "255ccfa6-7311-4180-8e52-361f425408d3",
            "sourceLineageTag": "contact",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_user",
            "dataType": "string",
            "sourceColumn": "account_user",
            "lineageTag": "d7374075-f38a-423e-b627-972e026b0bf7",
            "sourceLineageTag": "account_user",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_age_days",
            "dataType": "int64",
            "sourceColumn": "account_age_days",
            "formatString": "0",
            "lineageTag": "4556930a-4e6e-4662-b245-7e062b124726",
            "sourceLineageTag": "account_age_days",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "document",
            "dataType": "string",
            "sourceColumn": "document",
            "lineageTag": "2de31786-4038-45d0-927c-dafda6c7c62e",
            "sourceLineageTag": "document",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "gender",
            "dataType": "string",
            "sourceColumn": "gender",
            "lineageTag": "8577669a-adb5-4b0b-8d34-87c260a0033e",
            "sourceLineageTag": "gender",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dClientes",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dClientes",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "fLogins",
        "lineageTag": "e4d32ab2-05bd-4a1f-a64c-e6f12d47dc2a",
        "sourceLineageTag": "[imdepa].[fLogins]",
        "columns": [
          {
            "name": "login_date",
            "dataType": "dateTime",
            "sourceColumn": "login_date",
            "formatString": "General Date",
            "lineageTag": "5e93fd37-70e8-4903-bf17-237d227beef1",
            "sourceLineageTag": "login_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_user",
            "dataType": "string",
            "sourceColumn": "account_user",
            "lineageTag": "1765b86f-09c2-4b03-b940-0ffea2dd8755",
            "sourceLineageTag": "account_user",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "3dc1a32a-7fbd-4295-b212-9214abd5249f",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "login_type",
            "dataType": "string",
            "sourceColumn": "login_type",
            "lineageTag": "2fe84c82-6b46-47d3-a89a-97f2244ff670",
            "sourceLineageTag": "login_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "formatString": "0",
            "lineageTag": "25519a86-64e5-46ed-894b-4c5def6f3b13",
            "sourceLineageTag": "account_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "document",
            "dataType": "string",
            "sourceColumn": "document",
            "lineageTag": "39ffd4b6-b108-4b4a-b6d4-16e0cb4a0105",
            "sourceLineageTag": "document",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_type",
            "dataType": "string",
            "sourceColumn": "account_type",
            "lineageTag": "f1776a32-2cc9-467d-b4c1-0637bb7bd463",
            "sourceLineageTag": "account_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "9057259f-a0df-49db-87a5-e5f44f57666d",
            "sourceLineageTag": "datekey",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fLogins",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "fLogins",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "fDatalayer_session_summary",
        "lineageTag": "9269577d-ee9b-43cc-b964-f0f99e54eac6",
        "sourceLineageTag": "[imdepa].[fDatalayer_session_summary]",
        "columns": [
          {
            "name": "visitor_id",
            "dataType": "int64",
            "sourceColumn": "visitor_id",
            "formatString": "0",
            "lineageTag": "c3569a78-1fc8-4640-97d8-f7bbdec92830",
            "sourceLineageTag": "visitor_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "vendor_isloggedin",
            "dataType": "boolean",
            "sourceColumn": "vendor_isloggedin",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "10cd09d7-78ac-4114-b740-4d39bd4af2ae",
            "sourceLineageTag": "vendor_isloggedin",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "vendor_id",
            "dataType": "int64",
            "sourceColumn": "vendor_id",
            "formatString": "0",
            "lineageTag": "8a0b7813-e298-46a0-b18b-e2f50a73b245",
            "sourceLineageTag": "vendor_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "b2869324-de44-49d1-baf3-713008a159a0",
            "sourceLineageTag": "datekey",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "formatString": "0",
            "lineageTag": "dc56952c-e07b-424c-a2f8-46f5c15ac13c",
            "sourceLineageTag": "account_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "session",
            "dataType": "string",
            "sourceColumn": "session",
            "lineageTag": "abc10d83-279e-4f7b-a6a5-14ec4f2b591e",
            "sourceLineageTag": "session",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "session_time_in_seconds",
            "dataType": "int64",
            "sourceColumn": "session_time_in_seconds",
            "formatString": "0",
            "lineageTag": "e370b668-7b11-4d01-aa99-71e49e87e9b1",
            "sourceLineageTag": "session_time_in_seconds",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "user_type",
            "dataType": "string",
            "sourceColumn": "user_type",
            "lineageTag": "e1f3d6a3-5e34-4cfc-9237-152380886229",
            "sourceLineageTag": "user_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "04f91f8b-57b6-46a3-9658-1b9d31e530f5",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "visitor_isloggedin",
            "dataType": "boolean",
            "sourceColumn": "visitor_isloggedin",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a1b87698-b45d-4425-9d6e-4ecb910359a8",
            "sourceLineageTag": "visitor_isloggedin",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fDatalayer_session_summary",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "fDatalayer_session_summary",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dPeriodos",
        "lineageTag": "6412da6b-c1ad-40cb-8f80-7498e5841574",
        "sourceLineageTag": "[imdepa].[dPeriodos]",
        "columns": [
          {
            "name": "Data",
            "dataType": "dateTime",
            "sourceColumn": "Data",
            "formatString": "General Date",
            "lineageTag": "dc1d33cd-24ab-482e-9140-2321c6ac391f",
            "sourceLineageTag": "Data",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Periodo",
            "dataType": "string",
            "sourceColumn": "Periodo",
            "lineageTag": "747c453f-3642-4e61-b8b7-f6e0d888f1fd",
            "sourceLineageTag": "Periodo",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordem",
            "dataType": "int64",
            "sourceColumn": "Ordem",
            "formatString": "0",
            "lineageTag": "979679dd-7746-4bf6-bbba-b80f06c7a962",
            "sourceLineageTag": "Ordem",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dPeriodos",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dPeriodos",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dAssociados",
        "lineageTag": "a8be0e3c-5b67-44ad-a5c9-bf58e0c38c24",
        "sourceLineageTag": "[imdepa].[dAssociados]",
        "columns": [
          {
            "name": "copartner_id",
            "dataType": "int64",
            "sourceColumn": "copartner_id",
            "formatString": "0",
            "lineageTag": "c25af2bf-f256-451a-a41b-a90c2f32e0a7",
            "sourceLineageTag": "copartner_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "trading_name",
            "dataType": "string",
            "sourceColumn": "trading_name",
            "lineageTag": "f0a4ed4d-2cf6-441b-a5af-1b95fb783e49",
            "sourceLineageTag": "trading_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "trading_name_cut1",
            "dataType": "string",
            "sourceColumn": "trading_name_cut1",
            "lineageTag": "7ffc735e-a4e5-43bc-8cea-71be8557cdc6",
            "sourceLineageTag": "trading_name_cut1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "company_name",
            "dataType": "string",
            "sourceColumn": "company_name",
            "lineageTag": "9f415819-398e-48b8-9df0-7aa82edc2f75",
            "sourceLineageTag": "company_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "document",
            "dataType": "string",
            "sourceColumn": "document",
            "lineageTag": "5cd5b2b0-3502-484c-ad23-0535b657c8d4",
            "sourceLineageTag": "document",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "plataform_status",
            "dataType": "string",
            "sourceColumn": "plataform_status",
            "lineageTag": "455567db-7498-455a-b59e-7d6600308ec2",
            "sourceLineageTag": "plataform_status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "melhor_envio",
            "dataType": "string",
            "sourceColumn": "melhor_envio",
            "lineageTag": "7be01c67-e0b8-4ae3-8c8f-5b1fac9f7405",
            "sourceLineageTag": "melhor_envio",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "estados_b2b",
            "dataType": "string",
            "sourceColumn": "estados_b2b",
            "lineageTag": "489f7525-173e-45ea-a69e-7f788e9d7055",
            "sourceLineageTag": "estados_b2b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "estados_b2c",
            "dataType": "string",
            "sourceColumn": "estados_b2c",
            "lineageTag": "fc498b95-9c38-4524-a191-9b69e61e1268",
            "sourceLineageTag": "estados_b2c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "transportadoras",
            "dataType": "string",
            "sourceColumn": "transportadoras",
            "lineageTag": "a1e54aef-e79b-461f-b2f4-7bcc2dcb8ee6",
            "sourceLineageTag": "transportadoras",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "state",
            "dataType": "string",
            "sourceColumn": "state",
            "lineageTag": "e121fec3-d3ad-41a5-a581-26747e0991fe",
            "sourceLineageTag": "state",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "f5910456-76c9-44f9-af2a-b86f1ac00ae9",
            "sourceLineageTag": "datekey",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "retirada_loja",
            "dataType": "string",
            "sourceColumn": "retirada_loja",
            "lineageTag": "83ae280b-daf8-45a0-a093-b602a953a5b4",
            "sourceLineageTag": "retirada_loja",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "frota_propria",
            "dataType": "string",
            "sourceColumn": "frota_propria",
            "lineageTag": "19af8a3e-4544-4d9c-9aba-8e2cdb52cd73",
            "sourceLineageTag": "frota_propria",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "correios",
            "dataType": "string",
            "sourceColumn": "correios",
            "lineageTag": "df5017ef-abb8-4dca-9d40-db6c7d1b40d5",
            "sourceLineageTag": "correios",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "entrega_economica",
            "dataType": "string",
            "sourceColumn": "entrega_economica",
            "lineageTag": "544b7583-41e3-4266-a540-309a300dc17c",
            "sourceLineageTag": "entrega_economica",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "loggi",
            "dataType": "string",
            "sourceColumn": "loggi",
            "lineageTag": "d6663b73-20ce-4b5b-a3f8-998a82f966d3",
            "sourceLineageTag": "loggi",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "cupom_habilitado",
            "dataType": "string",
            "sourceColumn": "cupom_habilitado",
            "lineageTag": "f53b00d7-6977-4405-bec2-9644dde537ca",
            "sourceLineageTag": "cupom_habilitado",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "zip_code",
            "dataType": "string",
            "sourceColumn": "zip_code",
            "lineageTag": "dcb6d6bd-9c0e-4f17-b319-557ee749903a",
            "sourceLineageTag": "zip_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "partner_type",
            "dataType": "string",
            "sourceColumn": "partner_type",
            "lineageTag": "64cd88a0-894c-4e87-ac2f-354756da68c3",
            "sourceLineageTag": "partner_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "partner",
            "dataType": "int64",
            "sourceColumn": "partner",
            "formatString": "0",
            "lineageTag": "6d846c19-0a41-421e-991d-e7ee1fa443f2",
            "sourceLineageTag": "partner",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "loja_configurada",
            "dataType": "string",
            "sourceColumn": "loja_configurada",
            "lineageTag": "c4083cd8-12e2-4546-971e-3095902228df",
            "sourceLineageTag": "loja_configurada",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ecommerce_habilitado",
            "dataType": "string",
            "sourceColumn": "ecommerce_habilitado",
            "lineageTag": "b106c018-c4cc-420f-951b-5548ae91ed9a",
            "sourceLineageTag": "ecommerce_habilitado",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "wirecard",
            "dataType": "string",
            "sourceColumn": "wirecard",
            "lineageTag": "bd6bdedf-1520-4beb-953e-3e6813f7985e",
            "sourceLineageTag": "wirecard",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "partnership_date",
            "dataType": "dateTime",
            "sourceColumn": "partnership_date",
            "formatString": "General Date",
            "lineageTag": "46403b58-165c-4b2b-9cee-4313cc0dd79c",
            "sourceLineageTag": "partnership_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "last_update_date",
            "dataType": "dateTime",
            "sourceColumn": "last_update_date",
            "formatString": "General Date",
            "lineageTag": "db812ac7-c365-4e6e-9908-6e834d9b826e",
            "sourceLineageTag": "last_update_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "street_address",
            "dataType": "string",
            "sourceColumn": "street_address",
            "lineageTag": "e13e3553-c359-47fa-9782-17fb04669702",
            "sourceLineageTag": "street_address",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city",
            "lineageTag": "28172e54-a775-47fa-adfb-087b54ef4450",
            "sourceLineageTag": "city",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "uf",
            "dataType": "string",
            "sourceColumn": "uf",
            "lineageTag": "e80210f7-74a9-4a39-9c4c-be0e6ec2e181",
            "sourceLineageTag": "uf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "lineageTag": "aca228c3-9c67-4a63-bce7-824a629b24d1",
            "sourceLineageTag": "country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dAssociados",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dAssociados",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "dCupons",
        "lineageTag": "1f3e3a7c-b8f7-4a35-b702-8adefb3d7930",
        "sourceLineageTag": "[imdepa].[dCupons]",
        "columns": [
          {
            "name": "coupon_id",
            "dataType": "int64",
            "sourceColumn": "coupon_id",
            "formatString": "0",
            "lineageTag": "ac674536-039c-4eed-ac48-101e8cfb7700",
            "sourceLineageTag": "coupon_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "0e5a981b-4f41-4296-b38d-33e1452b9083",
            "sourceLineageTag": "site_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "code",
            "dataType": "int64",
            "sourceColumn": "code",
            "formatString": "0",
            "lineageTag": "625d380a-2519-4c87-a72f-774d13339cd7",
            "sourceLineageTag": "code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "campaign",
            "dataType": "string",
            "sourceColumn": "campaign",
            "lineageTag": "4ad89901-7665-4858-b2e3-0f7ff4d7c502",
            "sourceLineageTag": "campaign",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey_begin",
            "dataType": "int64",
            "sourceColumn": "datekey_begin",
            "formatString": "0",
            "lineageTag": "2b8f3063-391f-4f64-bd15-ce50b9fb3f6f",
            "sourceLineageTag": "datekey_begin",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey_end",
            "dataType": "int64",
            "sourceColumn": "datekey_end",
            "formatString": "0",
            "lineageTag": "8fb818e4-4cd5-4092-8b50-4b518df8ba7b",
            "sourceLineageTag": "datekey_end",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dCupons",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dCupons",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "lineageTag": "9c06ff6b-e17e-485f-b97c-806a11e59ae7",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "_",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Column]",
            "formatString": "0",
            "lineageTag": "3ecc4be6-5ff5-4179-ae22-435e9aba9748",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "ROW ( \"Column\", BLANK () )"
            }
          }
        ],
        "measures": [
          {
            "name": "GMV",
            "expression": [
              "",
              "CALCULATE(",
              "    SUMX(fVendas,",
              "        (fVendas[quantity] * fVendas[amount_charged]) + fVendas[median_charged_shipping] + fVendas[avg_credit_card_interest] + fVendas[avg_total_tax]",
              "    )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "d14aed45-e25d-4067-b213-048e8de7c248",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "GMV - Autoatendimento",
            "description": "GMV somando 100% cliente e venda assistida; GMV com participao do cliente",
            "expression": [
              "",
              "CALCULATE ( [GMV], dTipo_pedido[order_type_id] IN { 1, 3 } )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "52b83aee-af26-4c5e-b53c-1a6128b2dc71",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Quantidade de login",
            "description": "Quantidade de logins",
            "expression": [
              "",
              "CALCULATE ( COUNT ( fLogins[login_date] ), VALUES ( fLogins[account_id] ) )"
            ],
            "formatString": "#,0",
            "displayFolder": "Login",
            "lineageTag": "69cadd85-616e-40cc-8547-8e9cd265044c"
          },
          {
            "name": "Taxa de converso por login",
            "description": "Quantidade de logins para 1 pedido",
            "expression": [
              "",
              "DIVIDE ( [Quantidade de login], [Total de pedidos] )"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "displayFolder": "Login",
            "lineageTag": "b7cd3e96-f737-4130-a07f-4310bb239c46",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Quantidade de logins de cliente",
            "description": "Quantidade de logins de clientes",
            "expression": [
              "",
              "CALCULATE ( [Quantidade de login], NOT ( ISBLANK ( dClientes[client_id] ) ) )"
            ],
            "formatString": "#,0",
            "displayFolder": "Login",
            "lineageTag": "c1496285-5054-430a-9707-985d3230e995"
          },
          {
            "name": "Ticket Mdio",
            "description": "Ticket Mdio",
            "expression": [
              "",
              "DIVIDE ( [GMV], [Pedidos] )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\GMV",
            "lineageTag": "8ae24fbe-5908-4bee-a826-3c136092f76b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio por cliente",
            "description": "Ticket mdio ponderado por cliente",
            "expression": [
              "",
              "AVERAGEX ( VALUES ( fVendas[client_account_id] ), [Ticket Mdio] )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Ticket Mdio\\GMV",
            "lineageTag": "a53619d1-cbf6-42de-905d-8701902d0267",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio por estado",
            "description": "Ticket mdio ponderado por estado",
            "expression": [
              "",
              "AVERAGEX ( VALUES ( dClientes[state] ), [Ticket Mdio] )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\GMV",
            "lineageTag": "4bd4c7e7-15ef-4b60-8aa4-a04c38461c41",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio - Autoatendimento",
            "description": "Ticket mdio dos pedidos em auto atendimento",
            "expression": [
              "",
              "DIVIDE ( [GMV - Autoatendimento], [Pedidos - Autoatendimento] )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Ticket Mdio\\GMV",
            "lineageTag": "fa8ccaae-ee8e-406d-981e-deb24e7f4821",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio - Venda assistida",
            "description": "Ticket mdio dos pedidos de venda assistida",
            "expression": [
              "",
              "DIVIDE ( [GMV - Venda assistida], [Pedidos - Venda assistida] )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Ticket Mdio\\GMV",
            "lineageTag": "de069327-c37a-4399-9993-c45be8f0a372",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio - Mdulo vendedor",
            "description": "Ticket mdio dos pedidos em mdulo vendedor",
            "expression": [
              "",
              "DIVIDE ( [GMV - Mdulo vendedor], [Pedidos - Mdulo vendedor] )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Ticket Mdio\\GMV",
            "lineageTag": "b7ca749a-5a44-487d-9146-5490c18916d5",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio - App",
            "expression": [
              "",
              "DIVIDE ( [GMV - App], [Pedidos - App] )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Ticket Mdio\\GMV",
            "lineageTag": "bbdd4eaf-1e19-4865-9d59-32cf0a3fd592",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio - Desktop",
            "expression": [
              "",
              "DIVIDE ( [GMV - Desktop], [Pedidos - Desktop] )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Ticket Mdio\\GMV",
            "lineageTag": "a579ac18-398b-4f20-b1e0-ae1f1712dfa7",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio - Mobile",
            "expression": [
              "",
              "DIVIDE ( [GMV - Mobile], [Pedidos - Mobile] )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Ticket Mdio\\GMV",
            "lineageTag": "34e7bc87-4537-483a-98ba-be4417120c65",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Pedidos",
            "description": [
              "Nmero de pedidos, excluindo pedidos com status:",
              "",
              "- Cancelado",
              "- Aguardando pagamento",
              "- Pr-encomenda",
              "- Pagamento no caixa"
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( fVendas[partner_order_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "087a6806-8028-469a-832a-5f4d821efeb7",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Pedidos - 100% cliente",
            "description": "Pedidos realizados 100% pelo cliente",
            "expression": [
              "",
              "CALCULATE ( [Pedidos], dTipo_pedido[order_type_id] = 3 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "3968a02b-a6d1-4fc2-9ff8-1789ccbbfaf2"
          },
          {
            "name": "Pedidos - Venda assistida",
            "description": "Pedidos realizados com interao cliente-vendedor",
            "expression": [
              "",
              "CALCULATE ( [Pedidos], dTipo_pedido[order_type_id] = 1 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "212db723-9961-4102-8398-f7f9be70845b"
          },
          {
            "name": "Pedidos - Mdulo vendedor",
            "description": "Pedidos realizado 100% pelo vendedor.",
            "expression": [
              "",
              "CALCULATE ( [Pedidos], dTipo_pedido[order_type_id] = 2 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "2bb5a88c-5917-413e-ba41-a11a52f2e530"
          },
          {
            "name": "Pedidos - App",
            "description": "Pedidos via app",
            "expression": [
              "",
              "CALCULATE ( [Pedidos], dDispositivos[device_id] = 3 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "2e266327-b5a7-4564-b30a-a6baec9d9d6e"
          },
          {
            "name": "Pedidos - Desktop",
            "description": "Pedidos via desktop",
            "expression": [
              "",
              "CALCULATE ( [Pedidos], dDispositivos[device_id] = 1 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "7ec221ce-eaf6-4dbb-8adb-76d9b7d45174"
          },
          {
            "name": "Pedidos - Mobile",
            "description": "Pedidos via mobile",
            "expression": [
              "",
              "CALCULATE ( [Pedidos], dDispositivos[device_id] = 2 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "46c5a705-e4d6-4770-88eb-79c92455697e"
          },
          {
            "name": "Valor de frete",
            "description": "Valor de frete",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGEX (",
              "        VALUES ( fVendas[partner_order_id] ),",
              "        CALCULATE (",
              "            SUM ( fVendas[median_charged_shipping] )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "49d9f2a1-6fdb-40f8-8744-54befa04a2ca",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Total de pedidos",
            "description": [
              "Total de pedidos transacionados pela plataforma, engloba todos os status",
              ""
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( fVendas[partner_order_id] ),",
              "    ALL ( dStatus_pedido[order_status_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "8287ef67-1a74-4935-877b-2d0415420d1b"
          },
          {
            "name": "Frequencia de pedidos",
            "expression": [
              "",
              "VAR dtmin =",
              "    CALCULATE (",
              "        CONVERT ( MIN ( fVendas[datekey] ), DATETIME )",
              "    )",
              "VAR ciclo =",
              "    DATEDIFF ( dtmin, TODAY (), DAY )",
              "RETURN",
              "    DIVIDE ( ciclo, [Pedidos] )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "93252523-7da7-46dd-a215-72e88b886cb0",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Frequencia de pedidos por cliente",
            "expression": [
              "",
              "AVERAGEX ( VALUES ( dClientes[account_id] ), [Frequencia de pedidos] )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "6f3bce38-0946-4494-aac3-a26d1bf82b85"
          },
          {
            "name": "Frequencia de pedidos - dia til",
            "expression": [
              "",
              "VAR dtmin =",
              "    CALCULATE (",
              "        CONVERT ( MIN ( fVendas[datekey] ), DATETIME )",
              "    )",
              "VAR ciclo =",
              "    NETWORKDAYS ( dtmin, TODAY (), 1, VALUES ( dFeriados[Data] ) )",
              "RETURN",
              "    DIVIDE ( ciclo, [Pedidos] )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "b6ddc0dd-482c-4b1a-a2e9-aa64ac3811f3"
          },
          {
            "name": "Frequencia de pedidos - dia til por cliente",
            "expression": [
              "",
              "AVERAGEX (",
              "    VALUES ( dClientes[account_id] ),",
              "    [Frequencia de pedidos - dia til]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "cc73f5f5-69b2-435d-b478-d95ed44437ad"
          },
          {
            "name": "Quantidade de produtos distintos vendidos",
            "description": "Quantidade distinta de itens.",
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( fVendas[sku_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "c35b5dec-e850-495a-9039-8624f07ca4fc",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Mdia de produtos distintos por cliente",
            "expression": [
              "",
              "AVERAGEX (",
              "    VALUES ( fVendas[client_account_id] ),",
              "    [Quantidade de produtos distintos vendidos]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "3a83e867-e401-4945-94ad-c17f6a99670a"
          },
          {
            "name": "Rank de sku_id por pedidos",
            "expression": [
              "",
              "RANKX ( ALL ( fVendas[sku_id] ), [Pedidos],, DESC )"
            ],
            "formatString": "#,0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "ac2b1bcf-505e-49b5-a8ae-a86788753139"
          },
          {
            "name": "Quantidade de categoria distintas",
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( dProdutos[category_level_1] ),",
              "    CROSSFILTER ( dProdutos[sku_id], fVendas[sku_id], BOTH ),",
              "    dStatus_pedido[order_status_id] > 3",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Produtos\\Categoria",
            "lineageTag": "1b6536a2-2704-46e6-aa32-074b73db33c1"
          },
          {
            "name": "Quantidade de categoria-2 distintas",
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( dProdutos[category_level_2] ),",
              "    CROSSFILTER ( dProdutos[sku_id], fVendas[sku_id], BOTH ),",
              "    dStatus_pedido[order_status_id] > 3",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Produtos\\Categoria",
            "lineageTag": "5a651f9c-6537-45d9-b395-f5893a4d07f1"
          },
          {
            "name": "Quantidade de categoria-3 distintas",
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( dProdutos[category_level_3] ),",
              "    CROSSFILTER ( dProdutos[sku_id], fVendas[sku_id], BOTH ),",
              "    dStatus_pedido[order_status_id] > 3",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Produtos\\Categoria",
            "lineageTag": "a8572674-aec8-4ed1-a843-ca793cd9880f"
          },
          {
            "name": "Mdia de produtos distintos por pedido",
            "expression": [
              "",
              "AVERAGEX (",
              "    VALUES ( fVendas[partner_order_id] ),",
              "    [Quantidade de produtos distintos vendidos]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "25599176-27ae-4e37-9048-733b503c83ee"
          },
          {
            "name": "Mdia da quantidade de itens por cliente",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGEX ( VALUES ( fVendas[client_account_id] ), SUM ( fVendas[quantity] ) )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "9653316b-afd4-4527-b914-3b56af997461"
          },
          {
            "name": "Mdia da quantidade de itens por pedido",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGEX (",
              "        VALUES ( fVendas[partner_order_id] ),",
              "        CALCULATE (",
              "            SUM ( fVendas[quantity] ),",
              "            CROSSFILTER ( dProdutos[sku_id], fVendas[sku_id], BOTH )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "be813aea-8523-4936-a4ec-05bdc5c40f33"
          },
          {
            "name": "Faturamento digital",
            "expression": [
              "",
              "CALCULATE (",
              "    SUMX (",
              "        VALUES ( fVendas[partner_order_id] ),",
              "        CALCULATE (",
              "            AVERAGE ( fVendas[order_total] ),",
              "            dStatus_pedido[order_status_id] > 4",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado com imposto",
            "lineageTag": "726986a8-24e0-4199-b01b-9991f81ed9a1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital sem imposto",
            "expression": [
              "",
              "CALCULATE (",
              "    SUMX (",
              "        VALUES ( fVendas[partner_order_id] ),",
              "        CALCULATE (",
              "            AVERAGE ( fVendas[order_subtotal] ),",
              "            dStatus_pedido[order_status_id] > 4",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado sem imposto",
            "lineageTag": "f52a1a49-b303-4a58-8ec6-2c2a787aa59a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "GMV - 100% cliente",
            "expression": [
              "",
              "CALCULATE ( [GMV], dTipo_pedido[order_type_id] = 3 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "24e75658-e8f6-4a4e-ae63-43cf94b68850",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "GMV - Venda assistida",
            "expression": [
              "",
              "CALCULATE ( [GMV], dTipo_pedido[order_type_id] = 1 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "719b1b30-6d0e-4ac4-95c8-1d41f479c7bf",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "GMV - Mdulo vendedor",
            "expression": [
              "",
              "CALCULATE ( [GMV], dTipo_pedido[order_type_id] = 2 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "f6b13c35-ecf4-4043-9aaa-7d9e2f383e89",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital - Autoatendimento",
            "description": "GMV somando 100% cliente e venda assistida; GMV com participao do cliente",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital], dTipo_pedido[order_type_id] IN { 1, 3 } )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado com imposto",
            "lineageTag": "0ede3b5f-b633-4714-a738-bf869dabef6b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital - 100% cliente",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital], dTipo_pedido[order_type_id] = 3 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado com imposto",
            "lineageTag": "16bd8020-5e93-46d8-b3a9-aae0a846cd48",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital - Venda assistida",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital], dTipo_pedido[order_type_id] = 1 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado com imposto",
            "lineageTag": "1eca893e-1560-47c2-94af-6b42d5aacb5b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital - Mdulo vendedor",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital], dTipo_pedido[order_type_id] = 2 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado com imposto",
            "lineageTag": "0d8f3bc6-a9fa-47d4-a0cd-67d3691543ae",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital sem imposto - Autoatendimento",
            "description": "GMV somando 100% cliente e venda assistida; GMV com participao do cliente",
            "expression": [
              "",
              "CALCULATE (",
              "    [Faturamento digital sem imposto],",
              "    dTipo_pedido[order_type_id] IN { 1, 3 }",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado sem imposto",
            "lineageTag": "036dc221-b510-44c0-8cd2-adf16dd87ba6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital sem imposto - 100% cliente",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital sem imposto], dTipo_pedido[order_type_id] = 3 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado sem imposto",
            "lineageTag": "c3517aa6-6ad6-4edb-a99b-e641d3ab461a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital sem imposto - Venda assistida",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital sem imposto], dTipo_pedido[order_type_id] = 1 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado sem imposto",
            "lineageTag": "ec01e557-c497-41d4-aa83-1c77d6467243",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital sem imposto - Mdulo vendedor",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital sem imposto], dTipo_pedido[order_type_id] = 2 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado sem imposto",
            "lineageTag": "43857cf5-45bc-4ca2-80d2-418373f55978",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio - 100% cliente",
            "description": "Ticket mdio dos pedidos em auto atendimento",
            "expression": [
              "",
              "DIVIDE ( [GMV - 100% cliente], [Pedidos - 100% cliente] )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Ticket Mdio\\GMV",
            "lineageTag": "07814f10-ca48-4aab-b06e-b07812526948",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "GMV - App",
            "expression": [
              "",
              "CALCULATE ( [GMV], dDispositivos[device_id] = 3 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "6e7a5324-1185-49fd-8951-3aacf2d0ff1b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "GMV - Desktop",
            "expression": [
              "",
              "CALCULATE ( [GMV], dDispositivos[device_id] = 1 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "4972d193-94da-4dc5-b479-e9799543729b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "GMV - Mobile",
            "expression": [
              "",
              "CALCULATE ( [GMV], dDispositivos[device_id] = 2 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "8e9b404e-254d-4448-b458-7f28f2c8b469",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital - App",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital], dDispositivos[device_id] = 3 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado com imposto",
            "lineageTag": "ef261193-d11d-4d49-97aa-5848fc0fedd4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital - Desktop",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital], dDispositivos[device_id] = 1 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado com imposto",
            "lineageTag": "175690b4-abdf-42cc-9118-ca229f1e730f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital - Mobile",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital], dDispositivos[device_id] = 2 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado com imposto",
            "lineageTag": "ec3b27e1-8e33-4f53-b08a-cfdf85b75f30",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital sem imposto - App",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital sem imposto], dDispositivos[device_id] = 3 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado sem imposto",
            "lineageTag": "905bba15-fe79-47ae-ae8e-83ddf3609419",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital sem imposto - Desktop",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital sem imposto], dDispositivos[device_id] = 1 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado sem imposto",
            "lineageTag": "df26eeeb-6032-478a-827d-c89380e5fd1f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital sem imposto - Mobile",
            "expression": [
              "",
              "CALCULATE ( [Faturamento digital sem imposto], dDispositivos[device_id] = 2 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado sem imposto",
            "lineageTag": "651e2a4d-6f05-4030-8357-653c426ac481",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado sem imposto",
            "description": "Ticket Mdio",
            "expression": [
              "",
              "DIVIDE ( [Faturamento digital sem imposto], [Pedidos faturados] )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado sem imposto",
            "lineageTag": "a25ce509-579f-4904-a952-f8923bd385a2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado sem imposto por cliente",
            "description": "Ticket mdio ponderado por cliente",
            "expression": [
              "",
              "AVERAGEX (",
              "    VALUES ( fVendas[client_account_id] ),",
              "    [Ticket Mdio faturado sem imposto]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado sem imposto",
            "lineageTag": "fb2ebb48-969d-4676-8a65-d45457d1a2a4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado sem imposto por estado",
            "description": "Ticket mdio ponderado por estado",
            "expression": [
              "",
              "AVERAGEX ( VALUES ( dClientes[state] ), [Ticket Mdio faturado sem imposto] )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado sem imposto",
            "lineageTag": "b7db78c6-35f2-469d-9f93-cf63aac0807e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado sem imposto - Autoatendimento",
            "description": "Ticket mdio dos pedidos em auto atendimento",
            "expression": [
              "",
              "DIVIDE (",
              "    [Faturamento digital sem imposto - Autoatendimento],",
              "    [Pedidos faturados - Autoatendimento]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado sem imposto",
            "lineageTag": "26823f0d-163b-4d94-9146-877763c6a186",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado sem imposto - Venda assistida",
            "description": "Ticket mdio dos pedidos de venda assistida",
            "expression": [
              "",
              "DIVIDE (",
              "    [Faturamento digital sem imposto - Venda assistida],",
              "    [Pedidos faturados - Venda assistida]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado sem imposto",
            "lineageTag": "426291c9-5e54-49a7-b2a0-57df51956649",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado sem imposto - Mdulo vendedor",
            "description": "Ticket mdio dos pedidos em mdulo vendedor",
            "expression": [
              "",
              "DIVIDE (",
              "    [Faturamento digital sem imposto - Mdulo vendedor],",
              "    [Pedidos faturados - Mdulo vendedor]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado sem imposto",
            "lineageTag": "3910b3d1-597d-47f5-a0bc-14c71ade220a",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado sem imposto - App",
            "expression": [
              "",
              "DIVIDE ( [Faturamento digital sem imposto - App], [Pedidos faturados - App] )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado sem imposto",
            "lineageTag": "6e41fbb7-b08b-4534-8955-49f19b42cdc3",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado sem imposto - Desktop",
            "expression": [
              "",
              "DIVIDE (",
              "    [Faturamento digital sem imposto - Desktop],",
              "    [Pedidos faturados - Desktop]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado sem imposto",
            "lineageTag": "864e16e1-3afd-4eb2-b957-dd34e41e7833",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado sem imposto - Mobile",
            "expression": [
              "",
              "DIVIDE (",
              "    [Faturamento digital sem imposto - Mobile],",
              "    [Pedidos faturados - Mobile]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado sem imposto",
            "lineageTag": "9c375465-0760-4627-8e1f-b9bd663dda4d",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado sem imposto - 100% cliente",
            "description": "Ticket mdio dos pedidos em auto atendimento",
            "expression": [
              "",
              "DIVIDE (",
              "    [Faturamento digital sem imposto - 100% cliente],",
              "    [Pedidos faturados - 100% cliente]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado sem imposto",
            "lineageTag": "aa25042d-7f5a-4a67-b897-9d3c8fc0162e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Pedidos - Autoatendimento",
            "description": "Pedidos realizado 100% ou parcialmente pelo cliente.",
            "expression": [
              "",
              "CALCULATE ( [Pedidos], dTipo_pedido[order_type_id] IN { 1, 3 } )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "93298eb4-8cda-4571-8458-3593c385cd18"
          },
          {
            "name": "Pedidos faturados",
            "description": [
              "Nmero de pedidos, excluindo pedidos com status:",
              "",
              "- Cancelado",
              "- Aguardando pagamento",
              "- Pr-encomenda",
              "- Pagamento no caixa"
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( fVendas[partner_order_id] ),",
              "    dStatus_pedido[order_status_id] > 4",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "be3dba7a-3511-4641-a488-9372c310d51f",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Pedidos faturados - 100% cliente",
            "description": "Pedidos realizados 100% pelo cliente",
            "expression": [
              "",
              "CALCULATE ( [Pedidos faturados], dTipo_pedido[order_type_id] = 3 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "296e46d0-6862-4401-9272-03744dbdfacb"
          },
          {
            "name": "Pedidos faturados - Venda assistida",
            "description": "Pedidos realizados com interao cliente-vendedor",
            "expression": [
              "",
              "CALCULATE ( [Pedidos faturados], dTipo_pedido[order_type_id] = 1 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "96e87ae7-1158-4eb0-8fa3-8568cb269b35"
          },
          {
            "name": "Pedidos faturados - Mdulo vendedor",
            "description": "Pedidos realizado 100% pelo vendedor.",
            "expression": [
              "",
              "CALCULATE ( [Pedidos faturados], dTipo_pedido[order_type_id] = 2 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "aaa4cd9f-cc2f-4153-a58b-3d0e466d9f85"
          },
          {
            "name": "Pedidos faturados - App",
            "description": "Pedidos via app",
            "expression": [
              "",
              "CALCULATE ( [Pedidos faturados], dDispositivos[device_id] = 3 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "6d844ad6-05af-420f-bb2c-df3b018b7017"
          },
          {
            "name": "Pedidos faturados - Desktop",
            "description": "Pedidos via desktop",
            "expression": [
              "",
              "CALCULATE ( [Pedidos faturados], dDispositivos[device_id] = 1 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "17ffa0c7-4dcd-47a8-ab2e-961fac7d2e52"
          },
          {
            "name": "Pedidos faturados - Mobile",
            "description": "Pedidos via mobile",
            "expression": [
              "",
              "CALCULATE ( [Pedidos faturados], dDispositivos[device_id] = 2 )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "436c30e6-7da0-4311-b374-d6ef544fc4c4"
          },
          {
            "name": "Valor de frete faturado",
            "description": "Valor de frete",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGEX (",
              "        VALUES ( fVendas[partner_order_id] ),",
              "        CALCULATE (",
              "            SUM ( fVendas[median_charged_shipping] ),",
              "            dStatus_pedido[order_status_id] > 4",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "2eeb87c7-4222-43ac-abed-e652539611f8",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Frequencia de pedidos faturados",
            "expression": [
              "",
              "VAR dtmin =",
              "    CALCULATE (",
              "        CONVERT ( MIN ( fVendas[datekey] ), DATETIME ),",
              "        dStatus_pedido[order_status_id] > 4",
              "    )",
              "VAR ciclo =",
              "    DATEDIFF ( dtmin, TODAY (), DAY )",
              "RETURN",
              "    DIVIDE ( ciclo, [Pedidos] )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "e9f40fb6-19c4-4eea-a8f0-6098f15dbc2e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Frequencia de pedidos faturados por cliente",
            "expression": [
              "",
              "AVERAGEX ( VALUES ( dClientes[account_id] ), [Frequencia de pedidos] )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "288cd0e8-1c06-4c88-8c2f-df6b72c6494b"
          },
          {
            "name": "Frequencia de pedidos faturados - dia til",
            "expression": [
              "",
              "VAR dtmin =",
              "    CALCULATE (",
              "        CONVERT ( MIN ( fVendas[datekey] ), DATETIME ),",
              "        dStatus_pedido[order_status_id] > 4",
              "    )",
              "VAR ciclo =",
              "    NETWORKDAYS ( dtmin, TODAY (), 1, VALUES ( dFeriados[Data] ) )",
              "RETURN",
              "    DIVIDE ( ciclo, [Pedidos] )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "1fd012de-548b-4247-926e-2a735e9376cf"
          },
          {
            "name": "Frequencia de pedidos faturados - dia til por cliente",
            "expression": [
              "",
              "AVERAGEX (",
              "    VALUES ( dClientes[account_id] ),",
              "    [Frequencia de pedidos - dia til]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "983daa38-5a46-4cad-8d8e-b2f39945cc2d"
          },
          {
            "name": "Pedidos faturados - Autoatendimento",
            "description": "Pedidos realizado 100% pelo vendedor.",
            "expression": [
              "",
              "CALCULATE ( [Pedidos faturados], dTipo_pedido[order_type_id] IN { 1, 3 } )"
            ],
            "formatString": "#,0",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "0a5bb177-68d3-4bfc-b025-139bf35f5323"
          },
          {
            "name": "Ticket Mdio faturado",
            "description": "Ticket Mdio",
            "expression": [
              "",
              "DIVIDE ( [Faturamento digital], [Pedidos faturados] )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado com imposto",
            "lineageTag": "03955274-bce4-4014-93c2-1b13dbf48708",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado por cliente",
            "description": "Ticket mdio ponderado por cliente",
            "expression": [
              "",
              "AVERAGEX (",
              "    VALUES ( fVendas[client_account_id] ),",
              "    [Ticket Mdio faturado sem imposto]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado com imposto",
            "lineageTag": "1aac57fc-b5fb-4e29-9547-b1de9d398215",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado por estado",
            "description": "Ticket mdio ponderado por estado",
            "expression": [
              "",
              "AVERAGEX ( VALUES ( dClientes[state] ), [Ticket Mdio faturado sem imposto] )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado com imposto",
            "lineageTag": "7f934c9a-c6a9-48ff-b656-ccc0b13e4f56",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado - Autoatendimento",
            "description": "Ticket mdio dos pedidos em auto atendimento",
            "expression": [
              "",
              "DIVIDE (",
              "    [Faturamento digital - Autoatendimento],",
              "    [Pedidos faturados - Autoatendimento]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado com imposto",
            "lineageTag": "17153142-7b34-473f-becf-a47b2378e14d",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado - Venda assistida",
            "description": "Ticket mdio dos pedidos de venda assistida",
            "expression": [
              "",
              "DIVIDE (",
              "    [Faturamento digital - Venda assistida],",
              "    [Pedidos faturados - Venda assistida]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado com imposto",
            "lineageTag": "046852ce-acf6-4801-97b1-040841e87943",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado - Mdulo vendedor",
            "description": "Ticket mdio dos pedidos em mdulo vendedor",
            "expression": [
              "",
              "DIVIDE (",
              "    [Faturamento digital - Mdulo vendedor],",
              "    [Pedidos faturados - Mdulo vendedor]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado com imposto",
            "lineageTag": "d105e787-837a-479a-9df2-effbd4088a25",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado - App",
            "expression": [
              "",
              "DIVIDE ( [Faturamento digital - App], [Pedidos faturados - App] )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado com imposto",
            "lineageTag": "904b880b-a389-4837-a156-6673855b2548",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado - Desktop",
            "expression": [
              "",
              "DIVIDE ( [Faturamento digital - Desktop], [Pedidos faturados - Desktop] )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado com imposto",
            "lineageTag": "876dee3d-ebe5-475a-8970-b8c0ab73b7eb",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado - Mobile",
            "expression": [
              "",
              "DIVIDE ( [Faturamento digital - Mobile], [Pedidos faturados - Mobile] )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado com imposto",
            "lineageTag": "e145ce7a-aeac-4017-9cf5-0243c93df386",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ticket Mdio faturado - 100% cliente",
            "description": "Ticket mdio dos pedidos em auto atendimento",
            "expression": [
              "",
              "DIVIDE (",
              "    [Faturamento digital - 100% cliente],",
              "    [Pedidos faturados - 100% cliente]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ticket Mdio\\Faturado com imposto",
            "lineageTag": "bf7662ed-5050-4b58-860d-4c60b2ebeb60",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Quantidade de produtos distintos faturados",
            "description": "Quantidade distinta de itens.",
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( fVendas[sku_id] ),",
              "    dStatus_pedido[order_status_id] > 4",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Produtos\\Faturado",
            "lineageTag": "ac1b5bb8-04cb-4ecc-ba9c-de8a4baf98f8",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Mdia de produtos faturado distintos por cliente",
            "expression": [
              "",
              "AVERAGEX (",
              "    VALUES ( fVendas[client_account_id] ),",
              "    [Quantidade de produtos distintos faturados]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Produtos\\Faturado",
            "lineageTag": "7b55bcf3-03ee-4d66-8b0a-44b06a50baf3"
          },
          {
            "name": "Rank de sku_id por pedidos faturados",
            "expression": [
              "",
              "RANKX ( ALL ( fVendas[sku_id] ), [Pedidos faturados],, DESC )"
            ],
            "formatString": "0",
            "displayFolder": "Produtos\\Faturado",
            "lineageTag": "3f64392f-3282-40a0-8e0d-ba2edc1c038c"
          },
          {
            "name": "Mdia de produtos distintos por pedido faturados",
            "expression": [
              "",
              "AVERAGEX (",
              "    VALUES ( fVendas[partner_order_id] ),",
              "    [Quantidade de produtos distintos faturados]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Produtos\\Faturado",
            "lineageTag": "a0b150b1-908f-4af7-8f40-388befc3498a"
          },
          {
            "name": "Mdia da quantidade de itens faturados por cliente",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGEX ( VALUES ( fVendas[client_account_id] ), SUM ( fVendas[quantity] ) ),",
              "    dStatus_pedido[order_status_id] > 4",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Produtos\\Faturado",
            "lineageTag": "fcfb33cc-2d04-487a-945e-a909e178800d"
          },
          {
            "name": "Mdia da quantidade de itens faturados por pedido",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGEX (",
              "        VALUES ( fVendas[partner_order_id] ),",
              "        CALCULATE (",
              "            SUM ( fVendas[quantity] ),",
              "            CROSSFILTER ( dProdutos[sku_id], fVendas[sku_id], BOTH ),",
              "            dStatus_pedido[order_status_id] > 4",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Produtos\\Faturado",
            "lineageTag": "bfe8f4f7-bcb6-4b7d-ad77-a2b776de09f7"
          },
          {
            "name": "GMV - Produto linha-a-linha",
            "expression": [
              "",
              "CALCULATE(",
              "    SUMX(fVendas,",
              "    fVendas[quantity] * fVendas[amount_charged])",
              "    )"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "e67e4387-9949-4aeb-a6ea-7877059ef005",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital - Produto linha-a-linha",
            "expression": [
              "CALCULATE(",
              "    SUMX(fVendas,",
              "    (fVendas[quantity] * fVendas[amount_charged]) + fVendas[median_charged_shipping] + fVendas[avg_credit_card_interest] + fVendas[avg_total_tax]),",
              "    dStatus_pedido[order_status_id] > 4",
              ")",
              ""
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado com imposto",
            "lineageTag": "9862439d-5fa9-43b5-a3ca-4657aabab256",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Faturamento digital sem imposto - Produto linha-a-linha",
            "expression": [
              "CALCULATE(",
              "    SUMX(fVendas,",
              "    fVendas[quantity] * fVendas[amount_charged]),",
              "    dStatus_pedido[order_status_id] > 4",
              ")",
              ""
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Receita digital\\Faturado sem imposto",
            "lineageTag": "9bd09c09-db71-4704-a05a-670c3f9e1fed",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Quantidade de clientes",
            "description": [
              "Total de clientes.",
              "",
              "Clientes  definido como conta com client_id.",
              "",
              "Podem existir mais contas que clientes.",
              "",
              "As informaes de clientes se encontram em dClientes"
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( dClientes[client_id] ),",
              "    NOT(ISBLANK(dClientes[client_id]))",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "11b8bcb9-f724-4172-a92a-f01446d1672b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Quantidade de documentos distintos",
            "description": [
              "Total de clientes.",
              "",
              "Clientes  definido como conta com client_id.",
              "",
              "Podem existir mais contas que clientes.",
              "",
              "As informaes de clientes se encontram em dClientes"
            ],
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( dClientes[document] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "9d7fc7ee-8f98-4d5d-9e05-12da0ac1d047",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Quantidade de contas",
            "description": [
              "Total de clientes.",
              "",
              "Clientes  definido como conta com client_id.",
              "",
              "Podem existir mais contas que clientes.",
              "",
              "As informaes de clientes se encontram em dClientes"
            ],
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( dClientes[account_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "08dd1c43-eb9c-4999-8a3b-a14349ba9d9c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Quantidade de clientes - 100% cliente",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de clientes com pedidos],",
              "    FILTER(dClientes,",
              "    [Pedidos faturados - 100% cliente])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "1a39b77b-6f97-4217-86f2-ae7d054a3149"
          },
          {
            "name": "Quantidade de clientes com pedidos",
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( fVendas[client_account_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "508bbf91-6453-46a7-9efe-a0dfddf43511"
          },
          {
            "name": "Quantidade de clientes - Venda assistida",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de clientes com pedidos],",
              "    FILTER(dClientes,",
              "    [Pedidos faturados - Venda assistida])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "dd5e57e0-1b13-4332-9a8a-dcb6a993c59d"
          },
          {
            "name": "Quantidade de clientes - Modulo vendedor",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de clientes com pedidos],",
              "    FILTER(dClientes,",
              "    [Pedidos faturados - Mdulo vendedor])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "ca931785-5a5d-481b-a46a-4a2a446d0a61"
          },
          {
            "name": "Quantidade de clientes - App",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de clientes com pedidos],",
              "    FILTER(dClientes,",
              "    [Pedidos faturados - App])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "df78bbf5-923e-41bf-9426-e47d0349c328"
          },
          {
            "name": "Quantidade de clientes - Mobile",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de clientes com pedidos],",
              "    FILTER(dClientes,",
              "    [Pedidos faturados - Mobile])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "7ffcc6e6-0272-4ad5-be7e-e82e7db89573"
          },
          {
            "name": "Quantidade de clientes - Desktop",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de clientes com pedidos],",
              "    FILTER(dClientes,",
              "    [Pedidos faturados - Desktop])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "a1c4bef7-814c-43ab-b235-d99aac507cf6"
          },
          {
            "name": "Quantidade clientes acumulado por ano",
            "expression": [
              "",
              "VAR MaxDataVisivel =",
              "    MAX ( dCalendario[Data] ) // Pega a ltima data real do contexto (ex: 31 de janeiro)",
              "VAR AnoAtual =",
              "    YEAR ( MaxDataVisivel ) // Pega o ano dessa data",
              "RETURN",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( dClientes[client_id] ),",
              "        FILTER (",
              "            ALL ( dCalendario ),",
              "            // Filtra a tabela calendrio para o perodo acumulado",
              "            YEAR ( dCalendario[Data] ) = AnoAtual",
              "                && dCalendario[Data] <= MaxDataVisivel",
              "        ),",
              "        // Ativa a relao pela chave numrica para este clculo",
              "        USERELATIONSHIP ( dCalendario[datekey], dClientes[datekey] )",
              "    )"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "080bca7f-6a18-47c9-abbc-c45991d66e5d"
          },
          {
            "name": "Quantidade de carrinhos abandonados",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    fCarrinhos_abandonados[session_id]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Carrinhos abandonados",
            "lineageTag": "bb968257-7f6b-4f16-ae6f-fd07e39e8a85"
          },
          {
            "name": "Quantidade de carrinhos abandonados via desktop",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de carrinhos abandonados],",
              "    dDispositivos[device_id] = 1",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Carrinhos abandonados",
            "lineageTag": "94a85c87-90a8-45c7-aecd-aeebe41f9d4a"
          },
          {
            "name": "Quantidade de carrinhos abandonados via mobile",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de carrinhos abandonados],",
              "    dDispositivos[device_id] = 2",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Carrinhos abandonados",
            "lineageTag": "c6a5f13c-f3ea-4447-be1b-b442b6626f7b"
          },
          {
            "name": "Quantidade de carrinhos abandonados via app",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de carrinhos abandonados],",
              "    dDispositivos[device_id] = 3",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Carrinhos abandonados",
            "lineageTag": "ddb21b1c-7834-4791-97c5-c59a1a18eb1a"
          },
          {
            "name": "Data ultimo pedido faturado",
            "expression": [
              "",
              "CALCULATE(",
              "    CONVERT( MAX(fVendas[datekey]), DATETIME),",
              "    dStatus_pedido[order_status_id] > 4",
              ")"
            ],
            "formatString": "dd/mm/yyyy",
            "displayFolder": "Pedidos\\Faturado",
            "lineageTag": "64b38f99-8ab7-4916-82b5-2dfc7ad082d3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "Data ultimo pedido",
            "expression": [
              "",
              "VAR UltimaData = MAX(fVendas[datekey])",
              "",
              "VAR UltimaDataReal =",
              "DATE(",
              "    INT(UltimaData / 10000),                            -- Ano",
              "    INT(MOD(UltimaData, 10000) / 100),                  -- Ms",
              "    MOD(UltimaData, 100)                                -- Dia",
              ")",
              "",
              "RETURN",
              "UltimaDataReal"
            ],
            "formatString": "dd/mm/yyyy",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "65279795-62c1-4727-a298-2d00755b8339",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "Funil - sessoes",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(fDatalayer_agg_pageviews[sessoes_distintas])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "a8015e12-6019-44af-80f5-1963fb19bd68"
          },
          {
            "name": "Funil - paginas",
            "expression": [
              "",
              "CALCULATE(",
              "        COUNT( fDatalayer_agg_pageviews[pagepath] ),",
              "        fDatalayer_agg_pageviews[funil] = \"pageView\"",
              "    )"
            ],
            "formatString": "#,0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "20cce1bc-4224-4d28-8522-83e892bfa66b"
          },
          {
            "name": "Sessao_agg - sessoes distintas",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(fDatalayer_session_summary[session])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sessao_agg",
            "lineageTag": "3d56e912-30a6-4820-bc0d-38fba14b2f0e"
          },
          {
            "name": "Sessao_agg - sessoes",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(fDatalayer_session_summary[session])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sessao_agg",
            "lineageTag": "547f6957-004e-424b-81a7-975198325c6f"
          },
          {
            "name": "Sessao_agg - clientes distintos",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(fDatalayer_session_summary[account_id]),",
              "    NOT ISBLANK(fDatalayer_session_summary[account_id])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sessao_agg",
            "lineageTag": "60ab85fd-9312-4478-b985-3b7ec003d684"
          },
          {
            "name": "Sessao_agg - tempo medio por sessao",
            "expression": [
              "",
              "VAR tempo =",
              "    CALCULATE (",
              "        AVERAGEX (",
              "            VALUES ( fDatalayer_session_summary[session] ),",
              "            AVERAGE ( fDatalayer_session_summary[session_time_in_seconds] )",
              "        )",
              "    )",
              "VAR hora =",
              "    INT ( tempo / 3600 )",
              "VAR modhora =",
              "    MOD ( tempo, 3600 )",
              "VAR minutos =",
              "    INT ( modhora / 60 )",
              "VAR segundos =",
              "    INT ( MOD ( tempo, 60 ) )",
              "RETURN",
              "    hora * 10000 + minutos * 100 + segundos"
            ],
            "formatString": "00:00:00",
            "displayFolder": "Sessao_agg",
            "lineageTag": "93031175-4f4f-4076-9445-b582ea40f2d6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ]
          },
          {
            "name": "Sessao_agg - sessoes distintas por cliente",
            "expression": [
              "",
              "CALCULATE(",
              "    DIVIDE(",
              "        [Sessao_agg - sessoes distintas de clientes logados],",
              "        [Sessao_agg - clientes distintos],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sessao_agg",
            "lineageTag": "3cb7355d-249e-4a79-a082-d610ed9ad467"
          },
          {
            "name": "Sessao_agg - ultima sessao",
            "expression": [
              "",
              "VAR AnoMesDia = MAX(fDatalayer_session_summary[datekey]) -- exemplo: 20250703",
              "VAR Ano = INT(AnoMesDia / 10000)",
              "VAR Mes = INT(MOD(AnoMesDia, 10000) / 100)",
              "VAR Dia = MOD(AnoMesDia, 100)",
              "RETURN",
              "    DATE(Ano, Mes, Dia)"
            ],
            "formatString": "dd/mm/yyyy",
            "displayFolder": "Sessao_agg",
            "lineageTag": "17475489-f268-4790-b320-07273bb8b7fb",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "GMV YoY",
            "expression": [
              "",
              "VAR UltimaData = ",
              "CALCULATE(",
              "    MAX(fVendas[datekey]),",
              "    REMOVEFILTERS(dCalendario)",
              ")",
              "",
              "VAR UltimaDataReal =",
              "DATE(",
              "    INT(UltimaData / 10000),                            -- Ano",
              "    INT(MOD(UltimaData, 10000) / 100),                  -- Ms",
              "    MOD(UltimaData, 100)                                -- Dia",
              ")",
              "",
              "VAR DataLimite =",
              "EDATE(UltimaDataReal, -12)",
              "",
              "VAR YoY =",
              "CALCULATE(",
              "    [GMV],",
              "    DATEADD(dCalendario[Data], -12,MONTH),",
              "    FILTER(",
              "        ALL(dCalendario), dCalendario[Data] <= DataLimite",
              "    )",
              ")",
              "",
              "RETURN",
              "YoY"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "b4f5b010-ff8b-4fda-96cb-2546570541ae",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "GMV MoM",
            "expression": [
              "",
              "VAR UltimaData = ",
              "CALCULATE(",
              "    MAX(fVendas[datekey]),",
              "    REMOVEFILTERS(dCalendario)",
              ")",
              "",
              "VAR UltimaDataReal =",
              "DATE(",
              "    INT(UltimaData / 10000),                            -- Ano",
              "    INT(MOD(UltimaData, 10000) / 100),                  -- Ms",
              "    MOD(UltimaData, 100)                                -- Dia",
              ")",
              "",
              "VAR DataLimite =",
              "EDATE(UltimaDataReal, -1)",
              "",
              "VAR MoM =",
              "CALCULATE(",
              "    [GMV],",
              "    DATEADD(dCalendario[Data], -1,MONTH),",
              "    FILTER(",
              "        ALL(dCalendario), dCalendario[Data] <= DataLimite",
              "    )",
              ")",
              "",
              "RETURN",
              "MoM"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "7825d022-bbbb-4db1-8efc-e5232b41a6e3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Pedidos YoY",
            "expression": [
              "",
              "VAR UltimaData = ",
              "CALCULATE(",
              "    MAX(fVendas[datekey]),",
              "    REMOVEFILTERS(dCalendario)",
              ")",
              "",
              "VAR UltimaDataReal =",
              "DATE(",
              "    INT(UltimaData / 10000),                            -- Ano",
              "    INT(MOD(UltimaData, 10000) / 100),                  -- Ms",
              "    MOD(UltimaData, 100)                                -- Dia",
              ")",
              "",
              "VAR DataLimite =",
              "EDATE(UltimaDataReal, -12)",
              "",
              "VAR YoY =",
              "CALCULATE(",
              "    [Pedidos],",
              "    DATEADD(dCalendario[Data], -12,MONTH),",
              "    FILTER(",
              "        ALL(dCalendario), dCalendario[Data] <= DataLimite",
              "    )",
              ")",
              "",
              "RETURN",
              "YoY"
            ],
            "formatString": "#,0",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "91aac8df-f0ac-4fb1-a48f-fd901f091cc2"
          },
          {
            "name": "Pedidos MoM",
            "expression": [
              "",
              "VAR UltimaData = ",
              "CALCULATE(",
              "    MAX(fVendas[datekey]),",
              "    REMOVEFILTERS(dCalendario)",
              ")",
              "",
              "VAR UltimaDataReal =",
              "DATE(",
              "    INT(UltimaData / 10000),                            -- Ano",
              "    INT(MOD(UltimaData, 10000) / 100),                  -- Ms",
              "    MOD(UltimaData, 100)                                -- Dia",
              ")",
              "",
              "VAR DataLimite =",
              "EDATE(UltimaDataReal, -1)",
              "",
              "VAR MoM =",
              "CALCULATE(",
              "    [Pedidos],",
              "    DATEADD(dCalendario[Data], -1,MONTH),",
              "    FILTER(",
              "        ALL(dCalendario), dCalendario[Data] <= DataLimite",
              "    )",
              ")",
              "",
              "RETURN",
              "MoM"
            ],
            "formatString": "#,0",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "3ed36e5f-47e7-46ce-8d9e-1e8d456365d0"
          },
          {
            "name": "Variao de pedidos MoM (c/ icone)",
            "expression": [
              "",
              "VAR Porcentagem = [Variacao de pedidos MoM]",
              "",
              "VAR Icone =",
              "    SWITCH(",
              "        TRUE(),",
              "        ISBLANK(Porcentagem), \"\",",
              "        Porcentagem > 0, \"\",",
              "        Porcentagem < 0, \"\",",
              "        \"\"",
              "    )",
              "",
              "RETURN",
              "    Icone & \" \" & FORMAT(Porcentagem, \"#,##0%\")"
            ],
            "displayFolder": "Texto",
            "lineageTag": "14a49143-10cb-4f44-802b-4f395e30dc63"
          },
          {
            "name": "Variacao de pedidos YoY",
            "expression": [
              "",
              "VAR variacao = [Pedidos] - [Pedidos YoY]",
              "",
              "RETURN",
              "DIVIDE(",
              "    variacao,",
              "    [Pedidos YoY]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "255b7a42-d5ee-4e5e-8f4b-3209f5529426"
          },
          {
            "name": "Variacao de GMV MoM",
            "expression": [
              "",
              "VAR ValorAtual = [GMV]",
              "VAR ValorAnterior = [GMV MoM]",
              "VAR Variacao = ValorAtual - ValorAnterior",
              "",
              "RETURN",
              "DIVIDE(Variacao, ValorAnterior)"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "f424f1db-c2e0-4152-b58a-31cb9260e245"
          },
          {
            "name": "Variacao de GMV YoY",
            "expression": [
              "",
              "VAR variacao = [GMV] - [GMV YoY]",
              "",
              "RETURN",
              "DIVIDE(",
              "    variacao,",
              "    [GMV YoY]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "80a98524-104c-4431-856e-83c9338aa501"
          },
          {
            "name": "Periodo selecionado MoM",
            "expression": [
              "",
              "VAR DataMin = ",
              "    FORMAT(MIN(dCalendario[Data]), \"MMM yy\")",
              "",
              "VAR DataMax = ",
              "    FORMAT(MAX(dCalendario[Data]), \"MMM yy\")",
              "",
              "VAR DataMinMoM =",
              "    FORMAT(EDATE(DataMin, -1), \"MMM yy\")",
              "",
              "VAR DataMaxMoM =",
              "    FORMAT(EDATE(DataMax, -1), \"MMM yy\")",
              "",
              "RETURN",
              "    IF(",
              "        DataMin = DataMax,",
              "        \"MoM% | ( \" & DataMin & \" ) vs ( \" & DataMinMoM & \" )\",",
              "        \"MoM% | ( \" & DataMin & \" - \" &DataMax & \" ) vs ( \" & DataMinMoM & \" - \" &DataMaxMoM & \" )\"",
              "    )"
            ],
            "displayFolder": "Texto",
            "lineageTag": "b73fbb48-0b3c-4d5c-85b2-e170a47377f8"
          },
          {
            "name": "Dias uteis",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(dCalendario),",
              "    FILTER(",
              "        dCalendario,",
              "        dCalendario[Diatil] = TRUE()",
              "    ),",
              "    FILTER(",
              "        dCalendario,",
              "        dCalendario[Futuro] = FALSE()",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "d3a20f35-0d9e-492e-a0f2-a9eecb762eec"
          },
          {
            "name": "Media de pedidos por data",
            "expression": [
              "",
              "FORMAT(",
              "    AVERAGEX(",
              "        ADDCOLUMNS(",
              "            VALUES(dCalendario[Data]),",
              "            \"Pedidos\", [Pedidos]",
              "        ),",
              "        [Pedidos]",
              "    ),",
              "    \"#,#\" & \" mdia diria\"",
              ")"
            ],
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "a7040067-1d44-4bf2-8931-04d7df9e3d3e"
          },
          {
            "name": "Media de GMV por data",
            "expression": [
              "",
              "FORMAT(",
              "    AVERAGEX(",
              "        ADDCOLUMNS(",
              "            VALUES(dCalendario[Data]),",
              "            \"GMV\", [GMV]",
              "        ),",
              "        [GMV]",
              "    ),",
              "    \"R$ #,#\" & \" mdia diria\"",
              ")"
            ],
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "9245d896-b577-4860-9c48-de6ad8ca74a8"
          },
          {
            "name": "Meta de pedidos",
            "expression": [
              "",
              "CALCULATE(",
              "    [Pedidos] * 1.5",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Metas",
            "lineageTag": "8578baee-d431-4c97-a724-5b0469978b5c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Meta de GMV",
            "expression": [
              "",
              "CALCULATE(",
              "    [GMV] * 1.5",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Metas",
            "lineageTag": "c7bd09a8-2647-42ef-926d-c9059be8e1c5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Quantidade de itens no carrinho",
            "expression": [
              "",
              "SUM(fCarrinhos_abandonados[quantity])"
            ],
            "formatString": "#,0",
            "displayFolder": "Carrinhos abandonados",
            "lineageTag": "f71c5ae6-10a2-4bc2-98c9-9678b123b15f"
          },
          {
            "name": "Valor potencial do carrinho",
            "expression": [
              "",
              "SUMX(fCarrinhos_abandonados, fCarrinhos_abandonados[quantity] * fCarrinhos_abandonados[unit_price])"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Carrinhos abandonados",
            "lineageTag": "0b370207-d13d-444d-baa6-6f928a870c36",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Taxa de abandono por item",
            "expression": [
              "",
              "VAR carrinhos_total =",
              "    CALCULATE (",
              "        [Quantidade de carrinhos abandonados],",
              "        ALL ( fCarrinhos_abandonados[sku_name] )",
              "    )",
              "VAR divs =",
              "    CALCULATE (",
              "        DIVIDE ( [Quantidade de carrinhos abandonados], carrinhos_total, 0 )",
              "    )",
              "RETURN",
              "    divs"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Carrinhos abandonados",
            "lineageTag": "ad966bb3-cc74-40bc-9720-34af1541652b"
          },
          {
            "name": "Variacao de pedidos MoM",
            "expression": [
              "",
              "VAR ValorAtual = [Pedidos]",
              "VAR ValorAnterior = [Pedidos MoM]",
              "VAR Variacao = ValorAtual - ValorAnterior",
              "",
              "RETURN",
              "DIVIDE(Variacao, ValorAnterior)"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "ebd0fba8-b6cc-4064-9b1a-7e3917669399"
          },
          {
            "name": "Variao de GMV MoM (c/ icone)",
            "expression": [
              "",
              "VAR Porcentagem = [Variacao de GMV MoM]",
              "",
              "VAR Icone =",
              "    SWITCH(",
              "        TRUE(),",
              "        ISBLANK(Porcentagem), \"\",",
              "        Porcentagem > 0, \"\",",
              "        Porcentagem < 0, \"\",",
              "        \"\"",
              "    )",
              "",
              "RETURN",
              "    Icone & \" \" & FORMAT(Porcentagem, \"#,##0%\")"
            ],
            "displayFolder": "Texto",
            "lineageTag": "92f079fd-1491-4e77-85ba-6f8cf20d06d0"
          },
          {
            "name": "Quantidade de clientes com pedidos MoM",
            "expression": [
              "",
              "VAR UltimaData = ",
              "CALCULATE(",
              "    MAX(fVendas[datekey]),",
              "    REMOVEFILTERS(dCalendario)",
              ")",
              "",
              "VAR UltimaDataReal =",
              "DATE(",
              "    INT(UltimaData / 10000),                            -- Ano",
              "    INT(MOD(UltimaData, 10000) / 100),                  -- Ms",
              "    MOD(UltimaData, 100)                                -- Dia",
              ")",
              "",
              "VAR DataLimite =",
              "EDATE(UltimaDataReal, -1)",
              "",
              "VAR MoM =",
              "CALCULATE(",
              "    [Quantidade de clientes com pedidos],",
              "    DATEADD(dCalendario[Data], -1,MONTH),",
              "    FILTER(",
              "        ALL(dCalendario), dCalendario[Data] <= DataLimite",
              "    )",
              ")",
              "",
              "RETURN",
              "MoM"
            ],
            "formatString": "#,0",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "ed1b2e18-4e5b-4818-82fa-b78c8654175c"
          },
          {
            "name": "Ticket Medio MoM",
            "expression": [
              "",
              "VAR UltimaData = ",
              "CALCULATE(",
              "    MAX(fVendas[datekey]),",
              "    REMOVEFILTERS(dCalendario)",
              ")",
              "",
              "VAR UltimaDataReal =",
              "DATE(",
              "    INT(UltimaData / 10000),                            -- Ano",
              "    INT(MOD(UltimaData, 10000) / 100),                  -- Ms",
              "    MOD(UltimaData, 100)                                -- Dia",
              ")",
              "",
              "VAR DataLimite =",
              "EDATE(UltimaDataReal, -1)",
              "",
              "VAR MoM =",
              "CALCULATE(",
              "    [Ticket Mdio],",
              "    DATEADD(dCalendario[Data], -1,MONTH),",
              "    FILTER(",
              "        ALL(dCalendario), dCalendario[Data] <= DataLimite",
              "    )",
              ")",
              "",
              "RETURN",
              "MoM"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "8578dd29-83b5-40e5-aabf-503632786230",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Variacao de ticket medio MoM",
            "expression": [
              "",
              "VAR ValorAtual = [Ticket Mdio]",
              "VAR ValorAnterior = [Ticket Medio MoM]",
              "VAR Variacao = ValorAtual - ValorAnterior",
              "",
              "RETURN",
              "DIVIDE(Variacao, ValorAnterior)"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "923cbb5a-dc5c-45db-b97e-e79918ad4220"
          },
          {
            "name": "Variacao de quantidade de clientes com pedidos MoM",
            "expression": [
              "",
              "VAR ValorAtual = [Quantidade de clientes com pedidos]",
              "VAR ValorAnterior = [Quantidade de clientes com pedidos MoM]",
              "VAR Variacao = ValorAtual - ValorAnterior",
              "",
              "RETURN",
              "DIVIDE(Variacao, ValorAnterior)"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "4d1e91d1-fcb4-4a02-be58-89ff64ecf84e"
          },
          {
            "name": "Variacao de quantidade de clientes com pedidos MoM (c/ icone)",
            "expression": [
              "",
              "VAR Porcentagem = [Variacao de quantidade de clientes com pedidos MoM]",
              "",
              "VAR Icone =",
              "    SWITCH(",
              "        TRUE(),",
              "        ISBLANK(Porcentagem), \"\",",
              "        Porcentagem > 0, \"\",",
              "        Porcentagem < 0, \"\",",
              "        \"\"",
              "    )",
              "",
              "RETURN",
              "    Icone & \" \" & FORMAT(Porcentagem, \"#,##0%\")"
            ],
            "displayFolder": "Texto",
            "lineageTag": "3a416c44-84e0-439f-a16a-cc8e35d6c032"
          },
          {
            "name": "Variacao de ticket medio MoM (c/ icone)",
            "expression": [
              "",
              "VAR Porcentagem = [Variacao de ticket medio MoM]",
              "",
              "VAR Icone =",
              "    SWITCH(",
              "        TRUE(),",
              "        ISBLANK(Porcentagem), \"\",",
              "        Porcentagem > 0, \"\",",
              "        Porcentagem < 0, \"\",",
              "        \"\"",
              "    )",
              "",
              "RETURN",
              "    Icone & \" \" & FORMAT(Porcentagem, \"#,##0%\")"
            ],
            "displayFolder": "Texto",
            "lineageTag": "5aee1624-e7a5-4516-b6f8-978574695c0a"
          },
          {
            "name": "Quantidade de clientes por data",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de clientes],",
              "    USERELATIONSHIP(dClientes[datekey],dCalendario[datekey])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Clientes",
            "lineageTag": "1a0f8345-2197-4c8b-8c6d-fa8190dc1432"
          },
          {
            "name": "Taxa de abandono",
            "expression": [
              "",
              "VAR pedidos_geral =",
              "    CALCULATE ( DISTINCTCOUNT ( fVendas[partner_order_id] ) )",
              "VAR carrinhos_geral =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( fCarrinhos_abandonados[session_id] ),",
              "        fCarrinhos_abandonados[cart_type] = \"Carrinho abandonado\"",
              "    )",
              "VAR carrinhos =",
              "    CALCULATE ( DISTINCTCOUNT ( fCarrinhos_abandonados[session_id] ) )",
              "VAR total = pedidos_geral + carrinhos_geral",
              "VAR taxa =",
              "    CALCULATE ( DIVIDE ( carrinhos, total, 0 ) )",
              "RETURN",
              "    taxa"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Carrinhos abandonados",
            "lineageTag": "6e9c7290-0e50-4194-b6a3-ce2bdfa2850e"
          },
          {
            "name": "Sessao_agg - sessoes distintas de clientes logados",
            "expression": [
              "",
              "CALCULATE(",
              "    [Sessao_agg - sessoes distintas],",
              "    NOT ISBLANK(fDatalayer_session_summary[account_id])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sessao_agg",
            "lineageTag": "80f6022b-a38c-4803-8b08-2d1714c39d56"
          },
          {
            "name": "Quantidade de associados",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(dAssociados[partner])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Associados",
            "lineageTag": "24bc35cb-81c2-45d3-8ce1-941f045613b6"
          },
          {
            "name": "Quantidade de associados acumulado",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de associados],",
              "    dAssociados[partnership_date] <= MAX(dCalendario[Data])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Associados",
            "lineageTag": "e6e07cfb-27d0-4646-a61c-e19bdc42b050"
          },
          {
            "name": "Quantidade de associados com pedidos",
            "expression": [
              "",
              "CALCULATE (",
              "    DISTINCTCOUNT ( fVendas[partner_id] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Associados",
            "lineageTag": "edbb705e-0ba0-48b4-ab70-309dc244ae34"
          },
          {
            "name": "Quantidade de associados por periodo",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de associados],",
              "    USERELATIONSHIP(dAssociados[datekey],dCalendario[datekey])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Associados",
            "lineageTag": "4194e553-1f4b-420b-a45a-823e4de731e2"
          },
          {
            "name": "Estoque de ofertas",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(dOfertas[quantity_avaliable])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Ofertas",
            "lineageTag": "df9fc510-27a6-4438-bb7b-b0dbd17bea13"
          },
          {
            "name": "Menor Preo SKU",
            "expression": [
              "",
              "CALCULATE(",
              "    MIN(dOfertas[unit_price]),",
              "    ALLEXCEPT(dOfertas, dOfertas[sku_id])",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Ofertas",
            "lineageTag": "d8a3c5fe-2879-423f-bd57-53814dd93772",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Ofertas",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(dOfertas[sku_id])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Ofertas",
            "lineageTag": "5e90ceed-7638-4de3-af9e-000d296d36d1"
          },
          {
            "name": "Ofertas distinta",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(dOfertas[sku_id])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Ofertas",
            "lineageTag": "93352dd2-a0ca-486c-85b3-e761560da77c"
          },
          {
            "name": "Preco maximo vendido",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(fVendas[amount_charged]),",
              "    ALLEXCEPT(fVendas,fVendas[sku_id],dAssociados[trading_name])",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "044be161-7120-4b70-afcb-d2b1add83e61",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Preco minimo vendido",
            "expression": [
              "",
              "CALCULATE(",
              "    MIN(fVendas[amount_charged]),",
              "    ALLEXCEPT(fVendas,fVendas[sku_id],dAssociados[trading_name])",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "189cd3e4-9124-40fa-ba83-661b8d1cc1bc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Produtos com ofertas",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de produtos cadastrados],",
              "    FILTER(dOfertas, [Ofertas distinta] > 0)",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "42d4a1a5-d134-4fa0-a9c8-90aab161defa"
          },
          {
            "name": "Quantidade de produtos cadastrados",
            "expression": "DISTINCTCOUNT(dProdutos[sku_id])",
            "formatString": "#,0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "1d8393b5-c810-4c6d-af08-14ea1417a0ee"
          },
          {
            "name": "Pareto de categoria 1 por vendas",
            "expression": [
              "",
              "VAR TotalVendas = CALCULATE([GMV], ALLSELECTED(dProdutos))",
              "VAR TotalAtual = [GMV]",
              "VAR tbResumo = ",
              "    SUMMARIZE(",
              "        ALLSELECTED(dProdutos),",
              "        dProdutos[category_level_1],",
              "        \"Total\", [GMV]",
              "    )",
              "VAR TotalAcumulado = ",
              "    SUMX(",
              "        FILTER(",
              "            tbResumo,",
              "            [Total] >= TotalAtual",
              "        ),",
              "        [Total]",
              "    )",
              "RETURN",
              "TotalAcumulado / TotalVendas"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Produtos\\Categoria",
            "lineageTag": "6cf0812b-b431-4643-894b-a5c2653955d7"
          },
          {
            "name": "Rank vendas por categoria 1",
            "expression": [
              "",
              "RANKX(",
              "    ALLSELECTED(dProdutos[category_level_1]),",
              "    CALCULATE(",
              "        SUMX(fVendas,",
              "            (fVendas[quantity] * fVendas[amount_charged]) + fVendas[median_charged_shipping] + fVendas[avg_credit_card_interest] + fVendas[avg_total_tax]",
              "        )",
              "    ),,",
              "    DESC,",
              "    Dense",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Produtos\\Categoria",
            "lineageTag": "5695b17e-3b60-4472-a773-71e327880090"
          },
          {
            "name": "Quantidade de produtos sem venda",
            "expression": [
              "",
              "[Quantidade de produtos cadastrados] - [Quantidade de produtos distintos vendidos]"
            ],
            "formatString": "#,0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "eaca13d9-1739-4052-afa8-8e64631ab67b"
          },
          {
            "name": "Preco medio vendido",
            "expression": [
              "",
              "AVERAGEX(fVendas, fVendas[unit_price])"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "8dfcf5f5-99ae-40dc-a80b-a38d39a0fb4d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Pedidos convertido",
            "expression": [
              "",
              "DIVIDE(",
              "    [Pedidos - Autoatendimento],",
              "    [Pedidos]",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "45652cc6-a6d4-4672-b1d2-ace9edaaa8fd"
          },
          {
            "name": "Limite de valor GMV",
            "expression": "[GMV] * 1.1",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "Formatao",
            "lineageTag": "fe22de70-6770-4a4d-b3e8-59171dab32e4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Limite de valor Pedidos",
            "expression": "[Pedidos] * 1.2",
            "displayFolder": "Formatao",
            "lineageTag": "cfb33919-9f58-475a-8b69-f9bd7b5cfd70",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Vendedores cadastrados",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(dVendedores[account_id])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Vendedores",
            "lineageTag": "038ebe2d-2892-41f0-a847-e2b419b072e2"
          },
          {
            "name": "Vendedores com pedidos",
            "expression": [
              "",
              "CALCULATE(",
              "    [Vendedores cadastrados],",
              "    FILTER(",
              "        fVendas,",
              "        [Pedidos] > 0",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Vendedores",
            "lineageTag": "c2791e6b-647f-4bd8-b01d-c46ab7dfb994"
          },
          {
            "name": "Rank vendas por associados",
            "expression": [
              "",
              "RANKX(",
              "    ALLSELECTED(dAssociados[trading_name]),",
              "    CALCULATE(",
              "        SUMX(fVendas,",
              "            (fVendas[quantity] * fVendas[amount_charged]) + fVendas[median_charged_shipping] + fVendas[avg_credit_card_interest] + fVendas[avg_total_tax]",
              "        )",
              "    ),,",
              "    DESC,",
              "    Dense",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Associados",
            "lineageTag": "415ec268-ab4b-49ce-b74c-9aecc28726c4"
          },
          {
            "name": "Rank de sku_id por GMV",
            "expression": [
              "",
              "RANKX(",
              "    ALLSELECTED(dProdutos[sku_name]),",
              "    CALCULATE(",
              "        SUMX(fVendas,",
              "            (fVendas[quantity] * fVendas[amount_charged]) + fVendas[median_charged_shipping] + fVendas[avg_credit_card_interest] + fVendas[avg_total_tax]",
              "        )",
              "    ),,",
              "    DESC,",
              "    Dense",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Produtos\\Geral",
            "lineageTag": "540a23fc-1c46-4a68-a173-a939d00b57a2"
          },
          {
            "name": "Cupons",
            "expression": "DISTINCTCOUNT(dCupons[coupon_id])",
            "formatString": "#,0",
            "displayFolder": "Cupons",
            "lineageTag": "1cd226fe-5738-40f9-90f9-50fe2b94c21d"
          },
          {
            "name": "Cupons com pedido",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    fVendas[coupon_id]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Cupons",
            "lineageTag": "84903f1e-d676-4ba6-a29a-48982e6675b1"
          },
          {
            "name": "GMV - Cupom",
            "expression": [
              "",
              "CALCULATE(",
              "    [GMV],",
              "    NOT ISBLANK(fVendas[coupon_id])",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.0;-\"R$\"\\ #,0.0;\"R$\"\\ #,0.0",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "669b2252-295e-4b19-bee9-970429af67bd",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Rank vendas por cupom",
            "expression": [
              "",
              "RANKX(",
              "    ALLSELECTED(dCupons[campaign]),",
              "    CALCULATE(",
              "        SUMX(fVendas,",
              "            (fVendas[quantity] * fVendas[amount_charged]) + fVendas[median_charged_shipping] + fVendas[avg_credit_card_interest] + fVendas[avg_total_tax]",
              "        )",
              "    ),,",
              "    DESC,",
              "    Dense",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Cupons",
            "lineageTag": "67984521-2d21-4910-984d-ba64cdd8438c"
          },
          {
            "name": "Conversao de ofertas",
            "expression": [
              "",
              "DIVIDE(",
              "    [Pedidos],",
              "    [Ofertas]",
              ")"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Ofertas",
            "lineageTag": "25d99373-b245-44bd-b033-121eb264d6fa"
          },
          {
            "name": "Data minima",
            "expression": "MIN(dCalendario[Data])",
            "formatString": "dd/mm/yyyy",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "9e7fb2d9-b5ea-496e-9e7b-10e3ce12ad61",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "Data maxima",
            "expression": "MAX(dCalendario[Data])",
            "formatString": "dd/mm/yyyy",
            "displayFolder": "Inteligencia_temporal",
            "lineageTag": "db1bea1b-dd94-47dc-ba41-81ab12cc2cf5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "Periodo selecionado segmentador",
            "expression": [
              "",
              "VAR dt_min = [Data minima]",
              "VAR dt_max = [Data maxima]",
              "",
              "RETURN",
              "\"Perodo selecionado: \"& dt_min &\" a \"& dt_max"
            ],
            "displayFolder": "Texto",
            "lineageTag": "9d50c407-7682-493e-a0c2-1af5d7afc11f"
          },
          {
            "name": "Funil clientes",
            "expression": [
              "",
              "-- =============================================================================================",
              "-- SEO 1: DEFINIO DAS VARIVEIS PRINCIPAIS",
              "-- Aqui, armazenamos as medidas base de cada etapa do funil em variveis.",
              "-- Isso torna o cdigo mais legvel e otimizado, pois cada medida  calculada apenas uma vez.",
              "-- =============================================================================================",
              "VAR _sessoes    = [Funil - sessoes]   -- Nmero total de sesses que iniciam o funil.",
              "VAR _produto    = [Funil - produto]   -- Sesses que visualizaram pelo menos uma pgina de produto.",
              "VAR _carrinhos  = [Funil - carrinhos]  -- Sesses que adicionaram pelo menos um produto ao carrinho.",
              "VAR _frete      = [Funil - frete]     -- Sesses que chegaram  etapa de clculo/seleo de frete.",
              "VAR _pedidos    = [Funil - pedido]           -- Nmero total de pedidos concludos.",
              "-- =============================================================================================",
              "-- SEO 2: CLCULO DAS PORCENTAGENS TOTAIS (PARA AS BARRAS DE PROGRESSO)",
              "-- Esta seo calcula a porcentagem de cada etapa em relao ao nmero inicial de sesses (_sessoes).",
              "-- O resultado  usado para definir a LARGURA das barras de progresso no visual HTML.",
              "-- Ex: Se 50 de 100 sesses viram um produto, _pctProduto ser 50%, e a barra ter 50% de largura.",
              "-- =============================================================================================",
              "VAR _pctProduto   = DIVIDE(_produto, _sessoes, 0)   -- % de sesses que viram produtos.",
              "VAR _pctCarrinhos = DIVIDE(_carrinhos, _sessoes, 0) -- % de sesses que adicionaram ao carrinho.",
              "VAR _pctFrete     = DIVIDE(_frete, _sessoes, 0)     -- % de sesses que calcularam o frete.",
              "VAR _pctPedidos   = DIVIDE(_pedidos, _sessoes, 0)   -- % de sesses que se tornaram pedidos (Taxa de Converso).",
              "-- =============================================================================================",
              "-- SEO 3: CLCULO DAS REDUES (QUEDAS) ENTRE ETAPAS",
              "-- Esta seo calcula a taxa de abandono (drop-off) de uma etapa para a PRXIMA.",
              "--  calculado como: 1 - (valor da etapa atual / valor da etapa ANTERIOR).",
              "-- O resultado  usado para mostrar a \"plula\" de reduo (ex:  30.0%) em cada etapa.",
              "-- =============================================================================================",
              "VAR _redProduto   = 1 - DIVIDE(_produto, _sessoes, 0)    -- Queda de \"Sesses\" para \"Visualizao de Produto\".",
              "VAR _redCarrinhos = 1 - DIVIDE(_carrinhos, _produto, 0)  -- Queda de \"Visualizao de Produto\" para \"Carrinho\".",
              "VAR _redFrete     = 1 - DIVIDE(_frete, _carrinhos, 0)    -- Queda de \"Carrinho\" para \"Seleo de Frete\".",
              "VAR _redPedidos   = 1 - DIVIDE(_pedidos, _frete, 0)      -- Queda de \"Seleo de Frete\" para \"Pedido Concludo\".",
              "-- =============================================================================================",
              "-- SEO 4: CLCULO DA TAXA DE CONVERSO GERAL",
              "-- Esta varivel calcula a taxa de converso final, que  o total de pedidos dividido pelo total de sesses.",
              "--  a mesma conta de _pctPedidos, mas armazenada em uma varivel com nome mais claro para ser usada no cabealho.",
              "-- =============================================================================================",
              "VAR _taxaConv = DIVIDE(_pedidos, _sessoes, 0)",
              "-- =============================================================================================",
              "-- SEO 5: RETORNO DO HTML",
              "-- A funo RETURN constri o visual final.",
              "-- Ela gera uma string de texto contendo cdigo HTML e CSS.",
              "-- As variveis DAX calculadas acima so inseridas no HTML usando o operador de concatenao \"&\".",
              "-- =============================================================================================",
              "RETURN",
              "\"<!DOCTYPE html>",
              "<html lang='pt-br'>",
              "<head>",
              "<meta charset='UTF-8'>",
              "<style>",
              "/* CSS para estilizar o funil. Tudo est contido aqui para que o visual seja autnomo. */",
              "body { font-family:'Segoe UI',Tahoma,sans-serif; background:#fff; margin:0; padding:8px; color:#333; max-width:830px; box-sizing:border-box;}",
              "h1 { font-size:18px; margin:0 0 8px 0; font-weight:600; color:#202124;}",
              ".total-conversion-box { background:#f6f0fb; border:1px solid #DCD1E6; border-radius:6px; padding:6px 12px; display:inline-block;}",
              ".total-conversion-rate { font-size:14px; font-weight:700; color:#7b1fa2;}",
              ".funnel-step { width:100%; margin-bottom:8px; padding:8px; border-radius:6px; transition: background-color 0.2s ease-in-out;}",
              ".funnel-step:hover { background-color: #F9F9F9; }",
              ".step-header { display:flex; justify-content:space-between; align-items:center; margin-bottom:6px;}",
              ".step-title-group { display:flex; align-items:center; gap:8px; font-size:14px; font-weight:600; color:#333;}",
              ".step-icon { width:16px; height:16px; fill:#7b1fa2;}",
              ".step-value-text { font-size:13px; font-weight:700; color:#202124;}",
              ".step-reduction-pill { background:#fff9c4; color:#613c00; border:1px solid #F9E69A; padding:1px 6px; border-radius:10px; font-size:12px; font-weight:600;}",
              ".progress-container { display:flex; align-items:center; gap:8px; }",
              ".progress-bar-background { height:18px; background:#f1f3f4; border-radius:4px; overflow:hidden; flex-grow:1; border:1px solid #E0E0E0;}",
              ".progress-label { font-size:13px; font-weight:700; color:#202124; width:45px; text-align:right; }",
              ".funnel-bar { height:100%; border-radius:3px; }",
              ".sessoes .funnel-bar { background:linear-gradient(90deg,#50005C,#73175C);}",
              ".visualizados .funnel-bar { background:linear-gradient(90deg,#73175C,#9E1E7F);}",
              ".carrinhos .funnel-bar { background:linear-gradient(90deg,#9E1E7F,#A666B0);}",
              ".frete .funnel-bar { background:linear-gradient(90deg,#A666B0,#C499CA);}",
              ".concluido .funnel-bar { background:linear-gradient(90deg,#388E3C,#66BB6A);}",
              "</style>",
              "</head>",
              "<body>",
              "<div class='container'>",
              "  <div class='header'>",
              "    <h1>Funil de Converso do Cliente</h1>",
              "    <div class='total-conversion-box'>",
              "      <div class='total-conversion-rate'>Taxa de Converso Total: \" & FORMAT(_taxaConv,\"0.0%\") & \"</div>",
              "    </div>",
              "  </div>",
              "  <div class='funnel-step sessoes'>",
              "    <div class='step-header'>",
              "      <div class='step-title-group'>",
              "        <svg class='step-icon' viewBox='0 0 24 24'><path d='M13.5,4A1.5,1.5 0 0,0 12,5.5A1.5,1.5 0 0,0 13.5,7A1.5,1.5 0 0,0 15,5.5A1.5,1.5 0 0,0 13.5,4M10.5,10.94L7.5,7.94L6.44,9L10.5,13.06L12.94,10.62L17.5,15.18L18.91,13.76L12.94,7.8L10.5,10.18V10.94M4,2H20A2,2 0 0,1 22,4V20A2,2 0 0,1 20,22H4A2,2 0 0,1 2,20V4A2,2 0 0,1 4,2Z' /></svg>",
              "        <span>Sesses</span>",
              "      </div>",
              "      <span class='step-value-text'>\" & FORMAT(_sessoes,\"#,##0\") & \"</span>",
              "    </div>",
              "    <div class='progress-container'>",
              "      <div class='progress-bar-background'>",
              "        <div class='funnel-bar' style='width:100%;'></div>",
              "      </div>",
              "      <span class='progress-label'>100%</span>",
              "    </div>",
              "  </div>",
              "  <div class='funnel-step visualizados'>",
              "  <div class='step-header'>",
              "    <div class='step-title-group'>",
              "      <svg class='step-icon' viewBox='0 0 24 24'><path d='M12,9A3,3 0 0,0 9,12A3,3 0 0,0 12,15A3,3 0 0,0 15,12A3,3 0 0,0 12,9M12,17A5,5 0 0,1 7,12A5,5 0 0,1 12,7A5,5 0 0,1 17,12A5,5 0 0,1 12,17M12,4.5C7,4.5 2.73,7.61 1,12C2.73,16.39 7,19.5 12,19.5C17,19.5 21.27,16.39 23,12C21.27,7.61 17,4.5 12,4.5Z'/></svg>",
              "      <span>Produtos Visualizados</span>",
              "      <span class='step-reduction-pill'> \" & FORMAT(_redProduto,\"0.0%\") & \"</span>",
              "    </div>",
              "    <span class='step-value-text'>\" & FORMAT(_produto,\"#,##0\") & \"</span>",
              "  </div>",
              "  <div class='progress-container'>",
              "    <div class='progress-bar-background'>",
              "      <div class='funnel-bar' style='width:\" & FORMAT(_pctProduto,\"0%\") & \";'></div>",
              "    </div>",
              "    <span class='progress-label'>\" & FORMAT(_pctProduto,\"0.0%\") & \"</span>",
              "  </div>",
              "</div>",
              "<div class='funnel-step carrinhos'>",
              "  <div class='step-header'>",
              "    <div class='step-title-group'>",
              "      <svg class='step-icon' viewBox='0 0 24 24'><path d='M17,18A2,2 0 0,1 19,20A2,2 0 0,1 17,22A2,2 0 0,1 15,20A2,2 0 0,1 17,18M1,2V4H3L6.6,11.59L5.24,14.04C5.09,14.32 5,14.65 5,15A2,2 0 0,0 7,17H19V15H7.42A0.25,0.25 0 0,1 7.17,14.75L8.1,13H15.55C16.3,13 16.96,12.58 17.3,11.97L20.88,5.5C20.95,5.34 21,5.17 21,5A1,1 0 0,0 20,4H5.21L4.27,2H1M7,18A2,2 0 0,1 9,20A2,2 0 0,1 7,22A2,2 0 0,1 5,20A2,2 0 0,1 7,18Z'/></svg>",
              "      <span>Carrinhos</span>",
              "      <span class='step-reduction-pill'> \" & FORMAT(_redCarrinhos,\"0.0%\") & \"</span>",
              "    </div>",
              "    <span class='step-value-text'>\" & FORMAT(_carrinhos,\"#,##0\") & \"</span>",
              "  </div>",
              "  <div class='progress-container'>",
              "    <div class='progress-bar-background'>",
              "      <div class='funnel-bar' style='width:\" & FORMAT(_pctCarrinhos,\"0%\") & \";'></div>",
              "    </div>",
              "    <span class='progress-label'>\" & FORMAT(_pctCarrinhos,\"0.0%\") & \"</span>",
              "  </div>",
              "</div>",
              "<div class='funnel-step frete'>",
              "  <div class='step-header'>",
              "    <div class='step-title-group'>",
              "      <svg class='step-icon' viewBox='0 0 24 24'><path d='M3,4A2,2 0 0,0 1,6V17H3A3,3 0 0,0 6,20A3,3 0 0,0 9,17H15A3,3 0 0,0 18,20A3,3 0 0,0 21,17H23V12L20,8H17V4H3M17,9.5H19.5L21.47,12H17V9.5M6,15.5A1.5,1.5 0 0,1 7.5,17A1.5,1.5 0 0,1 6,18.5A1.5,1.5 0 0,1 4.5,17A1.5,1.5 0 0,1 6,15.5M18,15.5A1.5,1.5 0 0,1 19.5,17A1.5,1.5 0 0,1 18,18.5A1.5,1.5 0 0,1 16.5,17A1.5,1.5 0 0,1 18,15.5Z'/></svg>",
              "      <span>Frete Selecionado</span>",
              "      <span class='step-reduction-pill'> \" & FORMAT(_redFrete,\"0.0%\") & \"</span>",
              "    </div>",
              "    <span class='step-value-text'>\" & FORMAT(_frete,\"#,##0\") & \"</span>",
              "  </div>",
              "  <div class='progress-container'>",
              "    <div class='progress-bar-background'>",
              "      <div class='funnel-bar' style='width:\" & FORMAT(_pctFrete,\"0%\") & \";'></div>",
              "    </div>",
              "    <span class='progress-label'>\" & FORMAT(_pctFrete,\"0.0%\") & \"</span>",
              "  </div>",
              "</div>",
              "<div class='funnel-step concluido'>",
              "  <div class='step-header'>",
              "    <div class='step-title-group'>",
              "      <svg class='step-icon' fill='#388E3C' viewBox='0 0 24 24'><path d='M12 2C6.5 2 2 6.5 2 12S6.5 22 12 22 22 17.5 22 12 17.5 2 12 2M10 17L5 12L6.41 10.59L10 14.17L17.59 6.58L19 8L10 17Z'/></svg>",
              "      <span>Pedido Concludo</span>",
              "      <span class='step-reduction-pill'> \" & FORMAT(_redPedidos,\"0.0%\") & \"</span>",
              "    </div>",
              "    <span class='step-value-text'>\" & FORMAT(_pedidos,\"#,##0\") & \"</span>",
              "  </div>",
              "  <div class='progress-container'>",
              "    <div class='progress-bar-background'>",
              "      <div class='funnel-bar' style='width:\" & FORMAT(_pctPedidos,\"0%\") & \";'></div>",
              "    </div>",
              "    <span class='progress-label'>\" & FORMAT(_pctPedidos,\"0.0%\") & \"</span>",
              "  </div>",
              "</div>",
              "</div>",
              "</body>",
              "</html>\""
            ],
            "displayFolder": "Visuais HTML",
            "lineageTag": "e5438922-6d00-4614-9b52-692b911ab6c2"
          },
          {
            "name": "Funil - produto",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(fDatalayer_agg_pageviews[sessoes_distintas]),",
              "    fDatalayer_agg_pageviews[funil] IN {\"produto\",\"p\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "018bf967-5217-4b2d-befa-7eb3338220bf"
          },
          {
            "name": "Funil - carrinhos",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(fDatalayer_agg_pageviews[sessoes_distintas]),",
              "    fDatalayer_agg_pageviews[funil] IN {\"carrinho\", \"meus-carrinhos\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "0e764a2c-b516-49e5-ab3b-8bdf4e7e2669"
          },
          {
            "name": "Funil - frete",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(fDatalayer_agg_pageviews[sessoes_distintas]),",
              "    fDatalayer_agg_pageviews[funil] IN {\"escolha-frete\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "11ebed80-f524-443d-9121-ac6ff6b2ac4e"
          },
          {
            "name": "Pginas mais visitadas HTML",
            "expression": [
              "",
              "-- =============================================================================================",
              "-- OBJETIVO DA MEDIDA:",
              "-- Cria um visual HTML dinmico de grfico de barras horizontais ordenado por visitas.",
              "-- =============================================================================================",
              "-- =============================================================================================",
              "-- PASSO 1: CAPTURAR OS VALORES DAS MEDIDAS",
              "-- =============================================================================================",
              "VAR _homeValue      = COALESCE([Funil - home], 0)",
              "VAR _buscaValue     = COALESCE([Funil - busca], 0)",
              "VAR _produtoValue   = COALESCE([Funil - produto], 0)",
              "VAR _categoriaValue = COALESCE([Funil - categoria], 0)",
              "VAR _lojaValue      = COALESCE([Funil - loja], 0)",
              "VAR _ofertasValue   = COALESCE([Funil - ofertas], 0)",
              "",
              "-- =============================================================================================",
              "-- PASSO 2: CRIAR UMA TABELA VIRTUAL",
              "-- SVGs SUBSTITUDOS POR CDIGOS VLIDOS E ESCAPADOS",
              "-- =============================================================================================",
              "VAR _pagesTable =",
              "    UNION(",
              "        ROW(\"PageName\", \"Home\",       \"Value\", _homeValue,      \"CSSClass\", \"home\",      \"IconSVG\", \"<svg viewBox=\"\"0 0 24 24\"\" fill=\"\"#7b1fa2\"\"><path d=\"\"M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z\"\"/></svg>\"),",
              "        ROW(\"PageName\", \"Busca\",      \"Value\", _buscaValue,     \"CSSClass\", \"busca\",     \"IconSVG\", \"<svg viewBox=\"\"0 0 24 24\"\" fill=\"\"#7b1fa2\"\"><path d=\"\"M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zM10 14c-2.49 0-4.5-2.01-4.5-4.5S7.51 5 10 5s4.5 2.01 4.5 4.5S12.49 14 10 14z\"\"/></svg>\"),",
              "        ROW(\"PageName\", \"Produtos\",   \"Value\", _produtoValue,   \"CSSClass\", \"produtos\",  \"IconSVG\", \"<svg viewBox=\"\"0 0 24 24\"\" fill=\"\"#7b1fa2\"\"><path d=\"\"M20 7H4V5h16v2zm-1 5H5v-2h14v2zm-4 5H9v-2h6v2z\"\"/></svg>\"),",
              "        ROW(\"PageName\", \"Categorias\", \"Value\", _categoriaValue, \"CSSClass\", \"categoria\", \"IconSVG\", \"<svg viewBox=\"\"0 0 24 24\"\" fill=\"\"#7b1fa2\"\"><path d=\"\"M10 18h5v-6h-5v6zm-6 0h5V5H4v13zm12 0h5v-6h-5v6zM4 5v2h5V5H4zm12 0v2h5V5h-5z\"\"/></svg>\"),",
              "        ROW(\"PageName\", \"Lojas\",      \"Value\", _lojaValue,      \"CSSClass\", \"lojas\",     \"IconSVG\", \"<svg viewBox=\"\"0 0 24 24\"\" fill=\"\"#7b1fa2\"\"><path d=\"\"M12 12c.55 0 1-.45 1-1V6c0-.55-.45-1-1-1s-1 .45-1 1v5c0 .55.45 1 1 1zm-2 8h4v2h-4v-2zm-6 2h4v-2H4v2zM16 2h-8C5.79 2 4 3.79 4 6v13h2V6c0-.55.45-1 1-1h10c.55 0 1 .45 1 1v13h2V6c0-2.21-1.79-4-4-4z\"\"/></svg>\"),",
              "        ROW(\"PageName\", \"Ofertas\",    \"Value\", _ofertasValue,   \"CSSClass\", \"ofertas\",   \"IconSVG\", \"<svg viewBox=\"\"0 0 24 24\"\" fill=\"\"#7b1fa2\"\"><path d=\"\"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.77-7-4.14-7-8.1 0-1.98.7-3.83 1.87-5.33L16.5 17.5 12 21.93z\"\"/></svg>\")",
              "    )",
              "    ",
              "-- =============================================================================================",
              "-- PASSO 2.5: CALCULAR O VALOR MXIMO PARA A ESCALA",
              "-- =============================================================================================",
              "VAR _maxValue = MAXX(_pagesTable, [Value])",
              "VAR _safeMaxValue = IF(_maxValue = 0, 1, _maxValue)",
              "",
              "-- =============================================================================================",
              "-- PASSO 3: GERAR O HTML DINMICO COM CONCATENATEX",
              "-- =============================================================================================",
              "VAR _dynamicHTML =",
              "    CONCATENATEX(",
              "        _pagesTable,",
              "        VAR _currentValue = [Value]",
              "        VAR _percentage = DIVIDE(_currentValue, _safeMaxValue, 0)",
              "        VAR _itemClass = \"page-item \" & [CSSClass] & IF(_currentValue = 0, \" zero-value\", \"\")",
              "        VAR _tooltipText = FORMAT(_currentValue, \"#,##0\") & \" sesses\"",
              "        ",
              "        RETURN",
              "        -- HTML do item de pgina (estrutura de barra e label)",
              "        \"<div class='\" & _itemClass & \"' title='\" & _tooltipText & \"'>\" &",
              "            \"<div class='step-header'>\" &",
              "                \"<div class='step-title-group'>\" &",
              "                    \"<span class='step-icon'>\" & [IconSVG] & \"</span>\" &",
              "                    \"<span>\" & [PageName] & \"</span>\" &",
              "                \"</div>\" &",
              "                \"<span class='step-value-text'>\" & FORMAT(_currentValue, \"#,##0\") & \"</span>\" &",
              "            \"</div>\" &",
              "            \"<div class='progress-container'>\" &",
              "                \"<div class='progress-bar-background'>\" &",
              "                    \"<div class='funnel-bar' style='width:\" & FORMAT(_percentage, \"0%\") & \";'></div>\" &",
              "                \"</div>\" &",
              "            \"</div>\" &",
              "        \"</div>\",",
              "        \"\", ",
              "        [Value], DESC ",
              "    )",
              "",
              "-- =============================================================================================",
              "-- PASSO 4: MONTAR O HTML FINAL",
              "-- =============================================================================================",
              "RETURN",
              "\"<!DOCTYPE html>",
              "<html lang='pt-br'>",
              "<head>",
              "<meta charset='UTF-8'>",
              "<style>",
              "/* Estilos para o visual 'Pginas Mais Visitadas' */",
              "body { font-family:'Segoe UI',Tahoma,sans-serif; background:#fff; margin:0; padding:8px; color:#333; max-width:830px; box-sizing:border-box;}",
              "h1 { font-size:18px; margin:0 0 10px 0; font-weight:600; color:#202124;}",
              "/* Reduo de margem para aproximar as barras */",
              ".page-item { width:100%; margin-bottom:6px; padding:6px; border-radius:6px; transition: background-color 0.2s ease-in-out;}",
              ".page-item:hover { background-color: #F9F9F9; }",
              ".step-header { display:flex; justify-content:space-between; align-items:center; margin-bottom:4px;}",
              ".step-title-group { display:flex; align-items:center; gap:8px; font-size:14px; font-weight:600; color:#333;}",
              ".step-icon { width:16px; height:16px; fill:#7b1fa2;}",
              ".step-value-text { font-size:13px; font-weight:700; color:#202124;}",
              ".progress-container { display:flex; align-items:center; gap:0; }",
              "/* Reduo da altura da barra */",
              ".progress-bar-background { height:12px; background:#f1f3f4; border-radius:4px; overflow:hidden; flex-grow:1; border:1px solid #E0E0E0;}",
              ".funnel-bar { height:100%; border-radius:3px; }",
              ".home .funnel-bar { background:linear-gradient(90deg,#1f77b4,#4f95d4); }",
              ".busca .funnel-bar { background:linear-gradient(90deg,#ff7f0e,#ffa54f); }",
              ".produtos .funnel-bar { background:linear-gradient(90deg,#2ca02c,#70c470); }",
              ".categoria .funnel-bar { background:linear-gradient(90deg,#d62728,#e27272); }",
              ".lojas .funnel-bar { background:linear-gradient(90deg,#9467bd,#b699d4); }",
              ".ofertas .funnel-bar { background:linear-gradient(90deg,#8c564b,#b58873); }",
              ".zero-value .funnel-bar { background:#ccc; }",
              "</style>",
              "</head>",
              "<body>",
              "<div class='container'>",
              " <h1>Pginas Mais Visitadas</h1>\"",
              "& _dynamicHTML &",
              "\"</div>",
              "</body>",
              "</html>\""
            ],
            "displayFolder": "Visuais HTML",
            "lineageTag": "150a400a-1b8e-4e6f-b261-e20ccb66dc0a"
          },
          {
            "name": "Funil - home",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(fDatalayer_agg_pageviews[sessoes_distintas]),",
              "    fDatalayer_agg_pageviews[funil] IN {\"home\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "4a78be83-538d-4158-a506-513d84dcd3c5"
          },
          {
            "name": "Funil - busca",
            "expression": [
              "CALCULATE(",
              "    COUNT(fDatalayer_agg_pageviews[sessoes_distintas]),",
              "    fDatalayer_agg_pageviews[funil] IN {\"busca\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "3b31d726-fd7f-4659-b956-a7d62ee0e147"
          },
          {
            "name": "Funil - categoria",
            "expression": [
              "CALCULATE(",
              "    COUNT(fDatalayer_agg_pageviews[sessoes_distintas]),",
              "    fDatalayer_agg_pageviews[funil] IN {\"categoria\",\"categorias\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "79a88743-4211-4112-8a13-27bd4fd2f94c"
          },
          {
            "name": "Funil - loja",
            "expression": [
              "CALCULATE(",
              "    COUNT(fDatalayer_agg_pageviews[sessoes_distintas]),",
              "    fDatalayer_agg_pageviews[funil] IN {\"loja\", \"lojas\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "525abfc4-b736-4026-bfdc-1036e3220f98"
          },
          {
            "name": "Funil - ofertas",
            "expression": [
              "CALCULATE(",
              "    COUNT(fDatalayer_agg_pageviews[sessoes_distintas]),",
              "    fDatalayer_agg_pageviews[funil] IN {\"ofertas\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "240334f8-39db-414d-b1e2-4c6e50b98152"
          },
          {
            "name": "Funil - pedido",
            "expression": [
              "CALCULATE(",
              "    COUNT(fDatalayer_agg_pageviews[sessoes_distintas]),",
              "    fDatalayer_agg_pageviews[funil] IN {\"sucesso\"}",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Datalayer - Funil",
            "lineageTag": "fe4ff423-0011-442b-a088-c719d9aa06af"
          },
          {
            "name": "Clientes Autoatendimento",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de clientes],",
              "    FILTER(dClientes,",
              "    [Pedidos - Autoatendimento])",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Clientes",
            "lineageTag": "91fc3280-ee1b-444b-bc86-9396effd721e"
          },
          {
            "name": "Clients sem pedidos",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de clientes],",
              "    FILTER(dClientes,",
              "    NOT([Pedidos]))",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Clientes",
            "lineageTag": "f1320849-d717-4aef-8758-8ce1a01adfaa"
          },
          {
            "name": "Clientes com GMV",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantidade de clientes],",
              "    FILTER(dClientes,",
              "    [GMV])",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Clientes",
            "lineageTag": "5df6c8bf-7fdc-42bc-9430-3dcd2df7a219"
          },
          {
            "name": "Ranking de clientes por GMV",
            "expression": [
              "",
              "RANKX(",
              "    ALL(dClientes[account_id]),",
              "    [GMV],",
              "    ,",
              "    DESC",
              "    )"
            ],
            "formatString": "0",
            "displayFolder": "Clientes",
            "lineageTag": "9363f2c5-6e8d-405a-ad5e-240119105ded"
          },
          {
            "name": "GMV Vendedor",
            "expression": "[GMV - Mdulo vendedor] + [GMV - Venda assistida]",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "7fb12cd1-2df9-41f4-a6ad-8c8c283ee1c0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "Concentrao GMV",
            "expression": [
              "",
              "[GMV]-[GMV Vendedor]"
            ],
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "d27af8e8-ad67-41e8-9197-5366470f3739",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ]
          },
          {
            "name": "% GMV do vendedor",
            "expression": [
              "",
              "VAR GT = CALCULATE(",
              "    [GMV],",
              "    ALL(fVendas[client_account_id], fVendas[salesperson_account_id])",
              ")",
              "RETURN",
              "DIVIDE(",
              "    [GMV Vendedor],",
              "    GT",
              ")"
            ],
            "displayFolder": "Receita digital\\GMV",
            "lineageTag": "11357fdc-15e5-4d46-86b6-a66711ed8dc3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Vendedor Acumulado",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(dVendedores[account_id]),",
              "    dVendedores[client_id] <> BLANK(),",
              "    dVendedores[account_create_date] <= MAX(dCalendario[Data])",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Vendedores",
            "lineageTag": "3d99c8a2-b9c5-4fed-9ef4-7f09a909d580"
          },
          {
            "name": "Vendedores",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(dVendedores[account_id]),",
              "    dVendedores[client_id] <> BLANK(),",
              "    USERELATIONSHIP(dVendedores[client_create_date],dCalendario[Data])",
              ")"
            ],
            "displayFolder": "Vendedores",
            "lineageTag": "f92a1483-517e-4cba-9433-616fde618984"
          },
          {
            "name": "Vendedores com Logins",
            "expression": [
              "",
              "CALCULATE(",
              "    [Vendedores],",
              "    FILTER(dVendedores,",
              "    [Quantidade de login] <> 0),",
              "    USERELATIONSHIP(dVendedores[account_id],fLogins[account_id])",
              ")+0"
            ],
            "formatString": "0",
            "displayFolder": "Vendedores",
            "lineageTag": "de597a3c-b95e-4605-b827-72ed94bef965"
          },
          {
            "name": "Converso de Logins",
            "expression": [
              "",
              "DIVIDE(",
              "    [Quantidade de login],",
              "    [pedidos potencial]",
              ")"
            ],
            "lineageTag": "41d975e9-70ee-4311-98ce-3b34758664d1"
          },
          {
            "name": "pedidos potencial",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(fVendas[partner_order_id]),",
              "    ALL(fVendas[order_status_id])",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Pedidos\\Geral",
            "lineageTag": "8af4eaa9-552f-4b9e-b430-ca76750b17dc"
          },
          {
            "name": "Rank Categoria por GMV",
            "expression": [
              "",
              "RANKX(",
              "    ALLSELECTED(dProdutos[category_level_1]),",
              "    CALCULATE(",
              "        SUMX(",
              "            fVendas,",
              "            (fVendas[quantity] * fVendas[amount_charged])",
              "            + fVendas[median_charged_shipping]",
              "            + fVendas[avg_credit_card_interest]",
              "            + fVendas[avg_total_tax]",
              "        )",
              "    ),",
              "    ,",
              "    DESC,",
              "    DENSE",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f307d938-3001-421a-bf5f-9f89700961f4"
          },
          {
            "name": "Nome cliente",
            "expression": [
              "CALCULATE(",
              "    max(dClientes[name]))"
            ],
            "lineageTag": "8a9b7692-f7f8-4cdd-9c91-507d54b8b490"
          },
          {
            "name": "Dias da ultima sesso",
            "expression": [
              "",
              "VAR DataUltimaSessao =",
              "    CALCULATE(",
              "        MAX(dCalendario[data]),",
              "        FILTER(",
              "            fDatalayer_session_summary,",
              "            fDatalayer_session_summary[user_type] = \"Cliente navegando\"",
              "        )",
              "    )",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(DataUltimaSessao),",
              "    DATEDIFF(DataUltimaSessao, TODAY(), DAY),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6dafd937-46aa-48ba-8af7-4682fdcd07eb"
          },
          {
            "name": "Dias do ltimo carrinho",
            "expression": [
              "",
              "VAR UltimaDataCarrinho =",
              "    CALCULATE(",
              "        MAX('dCalendario'[Data]),",
              "        KEEPFILTERS(fCarrinhos_abandonados)",
              "    )",
              "RETURN",
              "DATEDIFF(UltimaDataCarrinho, TODAY(), DAY)"
            ],
            "formatString": "0",
            "lineageTag": "14d01df3-f0e5-45ef-8781-3d4aa27b1690"
          },
          {
            "name": "Dias do ltimo pedido",
            "expression": [
              "",
              "VAR DataUltimoPedido =",
              "    CALCULATE(",
              "        MAX(dCalendario[data]),",
              "        fVendas",
              "    )",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(DataUltimoPedido),",
              "    DATEDIFF(DataUltimoPedido, TODAY(), DAY),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1a985801-330e-4363-b689-99620442ad86"
          },
          {
            "name": "Email CWS?",
            "expression": [
              "",
              "VAR Dominio =",
              "    CALCULATE(",
              "        MAX(dClientes[account_user]))",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(Dominio) && CONTAINSSTRING(LOWER(Dominio), \"cws\"),",
              "    \"Sim\",",
              "    \"No\"",
              ")"
            ],
            "lineageTag": "abda0948-c7db-4735-be16-5f1fb386e7ee"
          },
          {
            "name": "Email Imdepa?",
            "expression": [
              "",
              "VAR Dominio =",
              "    CALCULATE(",
              "        MAX(dClientes[account_user]))",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(Dominio) && CONTAINSSTRING(LOWER(Dominio), \"imdepa\"),",
              "    \"Sim\",",
              "    \"No\"",
              ")"
            ],
            "lineageTag": "e27a3cb0-e6fb-43c8-8da0-eb2669718c7d"
          },
          {
            "name": "Valor potencial do ltimo carrinho",
            "expression": [
              "",
              "VAR UltimaDataCarrinho =",
              "    CALCULATE(",
              "        MAX('dCalendario'[Data]),",
              "        KEEPFILTERS(fCarrinhos_abandonados)",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    [Valor potencial do carrinho],",
              "    FILTER(",
              "        fCarrinhos_abandonados,",
              "        RELATED('dCalendario'[Data]) = UltimaDataCarrinho",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "b43dbdfc-3f88-4820-b9a6-cf6d565063a8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Qte itens do ltimo carrinho",
            "expression": [
              "",
              "VAR UltimaDataCarrinho =",
              "    CALCULATE(",
              "        MAX('dCalendario'[Data]),",
              "        KEEPFILTERS(fCarrinhos_abandonados)",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    [Quantidade de itens no carrinho],",
              "    FILTER(",
              "        fCarrinhos_abandonados,",
              "        RELATED('dCalendario'[Data]) = UltimaDataCarrinho",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0ac05122-188e-4c6c-a7de-07e2e0008a1c"
          },
          {
            "name": "Categorias 1 vistas ltimos 30 dias",
            "expression": [
              "",
              "VAR DataMaxima = TODAY()",
              "VAR DataMinima = DataMaxima - 30",
              "VAR CategoriasVistas =",
              "    CALCULATETABLE(",
              "        DISTINCT(dProdutos[category_level_1]),",
              "        FILTER(",
              "            fDatalayer_agg_pageviews,",
              "            RELATED('dCalendario'[Data]) >= DataMinima &&",
              "            RELATED('dCalendario'[Data]) <= DataMaxima &&",
              "            fDatalayer_agg_pageviews[user_type] = \"Cliente navegando\"",
              "        )",
              "    )",
              "RETURN",
              "CONCATENATEX(",
              "    CategoriasVistas,",
              "    dProdutos[category_level_1],",
              "    \", \"",
              ")"
            ],
            "lineageTag": "76063713-aa8a-4458-8557-cbdd23e574db"
          },
          {
            "name": "Categorias 2 vistas ltimos 30 dias",
            "expression": [
              "",
              "VAR DataMaxima = TODAY()",
              "VAR DataMinima = DataMaxima - 30",
              "VAR CategoriasVistas =",
              "    CALCULATETABLE(",
              "        DISTINCT(dProdutos[category_level_2]),",
              "        FILTER(",
              "            fDatalayer_agg_pageviews,",
              "            RELATED('dCalendario'[Data]) >= DataMinima &&",
              "            RELATED('dCalendario'[Data]) <= DataMaxima &&",
              "            fDatalayer_agg_pageviews[user_type] = \"Cliente navegando\"",
              "        )",
              "    )",
              "RETURN",
              "CONCATENATEX(",
              "    CategoriasVistas,",
              "    dProdutos[category_level_2],",
              "    \", \"",
              ")"
            ],
            "lineageTag": "8ced83e0-e56e-453d-a0cd-f07c11a0b8e1"
          },
          {
            "name": "Tutorial_Balo_1",
            "expression": [
              "",
              "\"",
              "<div style='position: relative; max-width: 520px; margin-left: 24px; padding: 16px;",
              "background-color: #DADADA; border: 1px solid #D9A8E0; border-radius: 10px;",
              "font-family: Segoe UI, sans-serif; color: rgba(0, 0, 0, 0.8); font-size: 14px;",
              "box-shadow: 0px 2px 6px rgba(0,0,0,0.05);'>",
              "",
              "  <!-- Seta  esquerda -->",
              "  <div style='position: absolute; left: -16px; top: 24px; width: 0; height: 0;",
              "    border-top: 14px solid transparent;",
              "    border-bottom: 14px solid transparent;",
              "    border-right: 16px solid #DADADA'>",
              "  </div>",
              "",
              "  <!-- Ttulo -->",
              "  <div style='font-weight: 600; font-size: 16px; color: rgba(0, 0, 0, 0.8); margin-bottom: 8px;'>",
              "    1/7 - <span style='color: #9E1E7F;'> Seja bem-vindo ao nosso tutorial!</span>",
              "  </div>",
              "",
              "  <!-- Texto -->",
              "  <div style='line-height: 1.6; font-size: 15px; color: rgba(0, 0, 0, 0.6);'>",
              "      esquerda est o nosso <strong>menu de navegao</strong>.  ",
              "    Voc pode clicar nos cones ou textos para <strong>mudar de pgina</strong>.",
              "  </div>",
              "",
              "  <!-- Botes -->",
              "  <div style='margin-top: 16px; display: flex; justify-content: flex-end; gap: 8px;'>",
              "    <span style='",
              "      background-color: transparent;",
              "      color: #9E1E7F;",
              "      border: 1px solid #9E1E7F;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      border-radius: 16px;",
              "      font-weight: 500;'>",
              "      Finalizar",
              "    </span>",
              "    <span style='",
              "      background-color: #9E1E7F;",
              "      color: white;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      font-weight: bold;",
              "      border-radius: 16px;'>",
              "      Prximo ",
              "    </span>",
              "  </div>",
              "</div>",
              "\"",
              ""
            ],
            "displayFolder": "Tutoriais",
            "lineageTag": "0edcaca9-7e13-4fbb-829c-83967d7109be"
          },
          {
            "name": "Tutorial_Balo_2",
            "expression": [
              "",
              "VAR HTMLCode = ",
              "    \"",
              "<div style='position: relative; max-width: 520px; margin-left: 24px; padding: 16px;",
              "background-color: #DADADA; border: 1px solid #B2B2B2; border-radius: 10px;",
              "font-family: Segoe UI, sans-serif; color: rgba(0, 0, 0, 0.8); font-size: 14px;",
              "box-shadow: 0px 2px 6px rgba(0,0,0,0.05);'>",
              "",
              "  <!-- Seta  esquerda -->",
              "  <div style='position: absolute; right: -16px; top: 12px; width: 0; height: 0;",
              "    border-top: 14px solid transparent;",
              "    border-bottom: 14px solid transparent;",
              "    border-left: 16px solid #DADADA;'>",
              "  </div>",
              "",
              "  <!-- Ttulo -->",
              "  <div style='font-weight: 600; font-size: 16px; color: rgba(0, 0, 0, 0.8); margin-bottom: 8px;'>",
              "    2/7 - <span style='color: #9E1E7F;'> Painel de filtros</span>",
              "  </div>",
              "",
              "  <!-- Texto -->",
              "  <div style='line-height: 1.6; font-size: 15px; color: rgba(0, 0, 0, 0.6);'>",
              "     Clique no <strong>texto acima</strong> para acessar o painel de filtros e comear a ",
              "    <strong>personalizar sua visualizao</strong>.",
              "  </div>",
              "",
              "  <!-- Botes -->",
              "  <div style='margin-top: 16px; display: flex; justify-content: flex-end; gap: 8px;'>",
              "    <span style='",
              "      background-color: transparent;",
              "      color: #9E1E7F;",
              "      border: 1px solid #9E1E7F;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      border-radius: 16px;",
              "      font-weight: 500;'>",
              "      Finalizar",
              "    </span>",
              "",
              "    <span style='",
              "      background-color: #9E1E7F;",
              "      color: white;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      font-weight: bold;",
              "      border-radius: 16px;'>",
              "      Prximo ",
              "    </span>",
              "  </div>",
              "</div>\"",
              "RETURN",
              "    HTMLCode",
              ""
            ],
            "displayFolder": "Tutoriais",
            "lineageTag": "13d1f04d-ce88-4f69-85e4-2cae49d51d9b"
          },
          {
            "name": "Tutorial_Balo_3_",
            "expression": [
              "",
              "\"",
              "<div style='position: relative; max-width: 520px; margin-left: 24px; padding: 16px;",
              "background-color: #DADADA; border: 1px solid #B2B2B2; border-radius: 10px;",
              "font-family: Segoe UI, sans-serif; color: rgba(0, 0, 0, 0.8); font-size: 14px;",
              "box-shadow: 0px 2px 6px rgba(0,0,0,0.05);'>",
              "",
              "  <!-- Seta  direita -->",
              "  <div style='position: absolute; right: -16px; top: 12px; width: 0; height: 0;",
              "    border-top: 14px solid transparent;",
              "    border-bottom: 14px solid transparent;",
              "    border-left: 16px solid #DADADA;'>",
              "  </div>",
              "",
              "  <!-- Ttulo -->",
              "  <div style='font-weight: 600; font-size: 16px; color: rgba(0, 0, 0, 0.8); margin-bottom: 8px;'>",
              "    3/7 - <span style='color:#9E1E7F;'> Personalizando sua visualizao</span>",
              "  </div>",
              "",
              "  <!-- Texto -->",
              "  <div style='line-height: 1.6; font-size: 15px; color: rgba(0, 0, 0, 0.6);'>",
              "     Clique no <strong>segmentador de dados</strong> ao lado (Perodo) para selecionar o <strong>perodo desejado</strong>.",
              "  </div>",
              "",
              "  <!-- Botes -->",
              "  <div style='margin-top: 16px; display: flex; justify-content: flex-end; gap: 8px;'>",
              "    <span style='",
              "      background-color: transparent;",
              "      color: #9E1E7F;",
              "      border: 1px solid #9E1E7F;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      border-radius: 16px;",
              "      font-weight: 500;'>",
              "      Finalizar",
              "    </span>",
              "    <span style='",
              "      background-color: #9E1E7F;",
              "      color: white;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      font-weight: bold;",
              "      border-radius: 16px;'>",
              "      Prximo ",
              "    </span>",
              "  </div>",
              "</div>",
              "\""
            ],
            "displayFolder": "Tutoriais",
            "lineageTag": "65437554-265c-483e-8b3d-5f1ade9bde73"
          },
          {
            "name": "Tutorial_Balo_4",
            "expression": [
              "",
              "\"",
              "<div style='position: relative; max-width: 520px; margin-right: 24px; padding: 16px;",
              "background-color: #DADADA; border: 1px solid #B2B2B2; border-radius: 10px;",
              "font-family: Segoe UI, sans-serif; color: rgba(0, 0, 0, 0.8); font-size: 14px;",
              "box-shadow: 0px 2px 6px rgba(0,0,0,0.05);'>",
              "",
              "  <!-- Seta  direita -->",
              "  <div style='position: absolute; right: -16px; top: 50px; width: 0; height: 0;",
              "    border-top: 14px solid transparent;",
              "    border-bottom: 14px solid transparent;",
              "    border-left: 16px solid #DADADA;'>",
              "  </div>",
              "",
              "  <!-- Ttulo -->",
              "  <div style='font-weight: 600; font-size: 16px; color: rgba(0, 0, 0, 0.8); margin-bottom: 8px;'>",
              "    4/7 - <span style='color:#9E1E7F;'> Limpar Filtros</span>",
              "  </div>",
              "",
              "  <!-- Texto -->",
              "  <div style='line-height: 1.6; font-size: 15px; color: rgba(0, 0, 0, 0.6);'>",
              "    Clique no boto <strong>Limpar</strong> para remover todos os filtros aplicados e reiniciar sua visualizao.",
              "  </div>",
              "",
              "  <!-- Botes -->",
              "  <div style='margin-top: 16px; display: flex; justify-content: flex-end; gap: 8px;'>",
              "    <span style='",
              "      background-color: transparent;",
              "      color: #9E1E7F;",
              "      border: 1px solid #9E1E7F;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      border-radius: 16px;",
              "      font-weight: 500;'>",
              "      Finalizar",
              "    </span>",
              "    <span style='",
              "      background-color: #9E1E7F;",
              "      color: white;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      font-weight: bold;",
              "      border-radius: 16px;'>",
              "      Prximo ",
              "    </span>",
              "  </div>",
              "</div>",
              "\""
            ],
            "displayFolder": "Tutoriais",
            "lineageTag": "c4154957-0156-48ee-b650-fb043f4c818f"
          },
          {
            "name": "Tutorial_Balo_5",
            "expression": [
              "",
              "\"",
              "<div style='position: relative; max-width: 520px; padding: 16px;",
              "background-color: #DADADA; border: 1px solid #B2B2B2; border-radius: 10px;",
              "font-family: Segoe UI, sans-serif; color: rgba(0, 0, 0, 0.8); font-size: 14px;",
              "box-shadow: 0px 2px 6px rgba(0,0,0,0.05);'>",
              "",
              "  <!-- Seta  direita -->",
              "  <div style='position: absolute; right: -16px; top: 16px; width: 0; height: 0;",
              "    border-top: 14px solid transparent;",
              "    border-bottom: 14px solid transparent;",
              "    border-left: 16px solid #DADADA;'>",
              "  </div>",
              "",
              "  <!-- Ttulo -->",
              "  <div style='font-weight: 600; font-size: 16px; color: rgba(0, 0, 0, 0.8); margin-bottom: 8px;'>",
              "    5/7 - <span style='color:#9E1E7F;'> Fechar Painel</span>",
              "  </div>",
              "",
              "  <!-- Texto -->",
              "  <div style='line-height: 1.6; font-size: 15px; color: rgba(0, 0, 0, 0.6);'>",
              "    Clique no boto <strong>X</strong> para esconder o painel de filtros e ampliar sua rea de anlise.",
              "  </div>",
              "",
              "  <!-- Botes -->",
              "  <div style='margin-top: 16px; display: flex; justify-content: flex-end; gap: 8px;'>",
              "    <span style='",
              "      background-color: transparent;",
              "      color: #9E1E7F;",
              "      border: 1px solid #9E1E7F;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      border-radius: 16px;",
              "      font-weight: 500;",
              "      cursor: pointer;'>",
              "      Finalizar",
              "    </span>",
              "    <span style='",
              "      background-color: #9E1E7F;",
              "      color: white;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      font-weight: bold;",
              "      border-radius: 16px;",
              "      cursor: pointer;'>",
              "      Prximo ",
              "    </span>",
              "  </div>",
              "</div>",
              "\""
            ],
            "displayFolder": "Tutoriais",
            "lineageTag": "475ce0ac-98a3-4014-a535-73668626ae90"
          },
          {
            "name": "Tutorial_Balo_6",
            "expression": [
              "",
              "\"",
              "<div style='position: relative; max-width: 520px; padding: 16px;",
              " background-color: #DADADA; border: 1px solid #B2B2B2; border-radius: 10px;",
              " font-family: Segoe UI, sans-serif; color: rgba(0, 0, 0, 0.8); font-size: 14px;",
              " box-shadow: 0px 2px 6px rgba(0,0,0,0.05);",
              " margin-top: 20px;'> <div style='",
              "    position: absolute;",
              "    right: 20px;",
              "    top: -16px; /* Ajustei para ficar 1px acima do preenchimento */",
              "    width: 0; ",
              "    height: 0;",
              "    border-left: 12px solid transparent; ",
              "    border-right: 12px solid transparent; ",
              "    border-bottom: 12px solid #B2B2B2;",
              "    z-index: 9;'>",
              "  </div>",
              "",
              "  <div style='",
              "    position: absolute;",
              "    right: 20px;",
              "    top: -15px; /* Ajustei para o novo tamanho da seta */",
              "    width: 0; ",
              "    height: 0;",
              "    border-left: 15px solid transparent;",
              "    border-right: 15px solid transparent;",
              "    border-bottom: 15px solid #DADADA;",
              "    z-index: 10;'>",
              "  </div>",
              "",
              "  <div style='font-weight: 600; font-size: 16px; color: rgba(0, 0, 0, 0.8); margin-bottom: 8px;'>",
              "    6/7 - <span style='color:#9E1E7F;'> Glossrio</span>",
              "  </div>",
              "",
              "  <div style='line-height: 1.6; font-size: 15px; color: rgba(0, 0, 0, 0.6);'>",
              "    Clique no cone de <strong>livro</strong> acima para expandir o glossrio.",
              "  </div>",
              "",
              "  <div style='margin-top: 16px; display: flex; justify-content: flex-end; gap: 8px;'>",
              "    <span style='",
              "      background-color: transparent;",
              "      color: #9E1E7F;",
              "      border: 1px solid #9E1E7F;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      border-radius: 16px;",
              "      font-weight: 500;",
              "      cursor: pointer;'>",
              "      Finalizar",
              "    </span>",
              "    <span style='",
              "      background-color: #9E1E7F;",
              "      color: white;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      font-weight: bold;",
              "      border-radius: 16px;",
              "      cursor: pointer;'>",
              "      Prximo ",
              "    </span>",
              "  </div>",
              "</div>",
              "\""
            ],
            "displayFolder": "Tutoriais",
            "lineageTag": "f61de679-43f0-4429-907a-a5815b03d59f"
          },
          {
            "name": "Tutorial_Balo_7_",
            "expression": [
              "\"",
              "<div style='position: relative; max-width: 520px; padding: 16px;",
              "  background-color: #DADADA; border: 1px solid #B2B2B2; border-radius: 10px;",
              "  font-family: Segoe UI, sans-serif; color: rgba(0, 0, 0, 0.8); font-size: 14px;",
              "  box-shadow: 0px 2px 6px rgba(0,0,0,0.05);",
              "  margin-top: 20px;'>",
              "",
              "  <!-- Seta sombra (maior, atrs) -->",
              "  <div style='",
              "    position: absolute;",
              "    right: 20px;",
              "    top: -16px; /* fica 1px acima do preenchimento */",
              "    width: 0; ",
              "    height: 0;",
              "    border-left: 12px solid transparent; ",
              "    border-right: 12px solid transparent; ",
              "    border-bottom: 12px solid #B2B2B2;",
              "    z-index: 9;'>",
              "  </div>",
              "",
              "  <!-- Seta principal (menor, frente) -->",
              "  <div style='",
              "    position: absolute;",
              "    right: 20px;",
              "    top: -15px; /* alinhada com a seta maior */",
              "    width: 0; ",
              "    height: 0;",
              "    border-left: 15px solid transparent;",
              "    border-right: 15px solid transparent;",
              "    border-bottom: 15px solid #DADADA;",
              "    z-index: 10;'>",
              "  </div>",
              "",
              "  <div style='font-weight: 600; font-size: 16px; color: rgba(0, 0, 0, 0.8); margin-bottom: 8px;'>",
              "    7/7 - <span style='color:#9E1E7F;'> Finalizar tutorial</span>",
              "  </div>",
              "",
              "  <div style='line-height: 1.6; font-size: 15px; color: rgba(0, 0, 0, 0.6);'>",
              "    Clique no cone <strong>'X'</strong> para fechar o glossrio. Parabns! Voc chegou ao fim do nosso tutorial.",
              "  </div>",
              "",
              "  <div style='margin-top: 16px; display: flex; justify-content: flex-end; gap: 8px;'>",
              "    <span style='",
              "      background-color: #9E1E7F;",
              "      color: white;",
              "      border: none;",
              "      padding: 6px 12px;",
              "      font-size: 14px;",
              "      border-radius: 16px;",
              "      font-weight: 500;",
              "      cursor: pointer;'>",
              "      Finalizar",
              "    </span>",
              "  </div>",
              "</div>",
              "\""
            ],
            "displayFolder": "Tutoriais",
            "lineageTag": "f3cda2c5-77cb-4f0a-9689-5d906c784dcf"
          },
          {
            "name": "ID do vendedor",
            "expression": [
              "CALCULATE(",
              "    max(dClientes[salesperson_account_id]))"
            ],
            "formatString": "0",
            "lineageTag": "eeee132e-4986-490f-844a-4a91ddc55332"
          },
          {
            "name": "Top 5 SKUs em quantidade no ultimo carrinho",
            "expression": [
              "",
              "VAR DataUltimoRegistro =",
              "    CALCULATE(",
              "        MAX('dCalendario'[Data]),",
              "        KEEPFILTERS(fCarrinhos_abandonados)",
              "    )",
              "",
              "VAR TabelaUltimoCarrinho =",
              "    CALCULATETABLE(",
              "        fCarrinhos_abandonados,",
              "        'dCalendario'[Data] = DataUltimoRegistro",
              "    )",
              "",
              "VAR Top5SKUs =",
              "    TOPN(",
              "        5,",
              "        SUMMARIZE(",
              "            TabelaUltimoCarrinho,",
              "            fCarrinhos_abandonados[sku_name],",
              "            \"QtdTotal\", SUM(fCarrinhos_abandonados[quantity])",
              "        ),",
              "        [QtdTotal],",
              "        DESC",
              "    )",
              "",
              "RETURN",
              "    CONCATENATEX(",
              "        Top5SKUs,",
              "        UNICHAR(8226) & \" \"",
              "            & fCarrinhos_abandonados[sku_name]",
              "            & \" - \"",
              "            & [QtdTotal]",
              "            & \" un\",",
              "        UNICHAR(10) & UNICHAR(10),   -- quebra de linha",
              "        [QtdTotal],",
              "        DESC",
              "    )",
              ""
            ],
            "lineageTag": "2c218de4-e49f-4fb1-aff8-e7e578ea0904"
          },
          {
            "name": "Nome do vendedor",
            "expression": [
              "VAR IDVendedor = Medidas[ID do vendedor]",
              "RETURN",
              "CALCULATE(",
              "    LOOKUPVALUE(",
              "        dVendedores[name],",
              "        dVendedores[account_id],",
              "        IDVendedor))",
              "        "
            ],
            "lineageTag": "c7838d0f-123f-41c0-92dc-25ecf5e7770e"
          },
          {
            "name": "Quantidade de pageviews de produto do cliente no ms atual",
            "expression": [
              "",
              "VAR _iniMes = DATE(YEAR(TODAY()), MONTH(TODAY()), 1)",
              "VAR _fimMes = EOMONTH(_iniMes, 0)",
              "RETURN",
              "CALCULATE(",
              "    SUM(fDatalayer_product_pageviews[distinct_count_session]),",
              "    fDatalayer_product_pageviews[visitor_isloggedin] = TRUE(),",
              "    NOT ISBLANK(fDatalayer_product_pageviews[account_id]),",
              "    FILTER(",
              "        fDatalayer_product_pageviews,",
              "        VAR _k = VALUE(fDatalayer_product_pageviews[datekey_max_datecreated])",
              "        VAR _d =",
              "            DATE(",
              "                INT(_k / 10000),",
              "                INT(MOD(_k, 10000) / 100),",
              "                MOD(_k, 100)",
              "            )",
              "        RETURN _d >= _iniMes && _d <= _fimMes",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "964c5931-3109-4869-b7de-c0aa3ab2776b"
          },
          {
            "name": "Quantidade de SKUs distintos vistos pelo cliente no ms atual",
            "expression": [
              "",
              "VAR _iniMes = DATE(YEAR(TODAY()), MONTH(TODAY()), 1)",
              "VAR _fimMes = EOMONTH(_iniMes, 0)",
              "RETURN",
              "CALCULATE(",
              "    DISTINCTCOUNT(fDatalayer_product_pageviews[sku_id]),",
              "    fDatalayer_product_pageviews[visitor_isloggedin] = TRUE(),",
              "    NOT ISBLANK(fDatalayer_product_pageviews[account_id]),",
              "    FILTER(",
              "        fDatalayer_product_pageviews,",
              "        VAR _k = VALUE(fDatalayer_product_pageviews[datekey_max_datecreated])",
              "        VAR _d =",
              "            DATE(",
              "                INT(_k / 10000),",
              "                INT(MOD(_k, 10000) / 100),",
              "                MOD(_k, 100)",
              "            )",
              "        RETURN _d >= _iniMes && _d <= _fimMes",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7a8d91cd-1d34-4d59-bf6f-ec7c4625caf3"
          },
          {
            "name": "Lista SKUs vistos (ms atual)",
            "expression": [
              "",
              "VAR _t =",
              "    ADDCOLUMNS(",
              "        VALUES(fDatalayer_product_pageviews[sku_id]),",
              "        \"SkuNome\",",
              "            COALESCE(",
              "                LOOKUPVALUE(",
              "                    dProdutos[sku_name],",
              "                    dProdutos[sku_id],",
              "                    fDatalayer_product_pageviews[sku_id]",
              "                ),",
              "                FORMAT(fDatalayer_product_pageviews[sku_id], \"0\")",
              "            ),",
              "        \"Views\", [Quantidade de pageviews de produto do cliente no ms atual]",
              "    )",
              "",
              "VAR _tFiltrada =",
              "    FILTER(_t, [Views] > 0)",
              "",
              "VAR _top =",
              "    TOPN(",
              "        20,",
              "        _tFiltrada,",
              "        [Views], DESC,",
              "        [SkuNome], ASC",
              "    )",
              "",
              "RETURN",
              "CONCATENATEX(",
              "    _top,",
              "    \" \"",
              "        & [SkuNome]",
              "        & \" (\"",
              "        & FORMAT([Views], \"#,0\")",
              "        & \" \"",
              "        & IF([Views] = 1, \"visualizao\", \"visualizaes\")",
              "        & \")\",",
              "    UNICHAR(10) & UNICHAR(10),",
              "    [Views],",
              "    DESC",
              ")",
              ""
            ],
            "lineageTag": "eb203f72-86ab-4dda-88ad-1f5bdd2ec9a9"
          },
          {
            "name": "Vendas digitais - Carteira do vendedor",
            "expression": [
              "",
              "CALCULATE(",
              "    [Faturamento digital],",
              "",
              "    -- 1) ignora vendedor registrado na venda",
              "    REMOVEFILTERS( fVendas[salesperson_account_id] ),",
              "",
              "    -- 2) DESLIGA o relacionamento indesejado (caminho alternativo)",
              "    CROSSFILTER(",
              "        dVendedores[client_id],",
              "        fVendas[client_account_id],",
              "        NONE",
              "    ),",
              "",
              "    -- 3) aplica o vendedor do contexto como filtro de carteira em dClientes",
              "    TREATAS(",
              "        VALUES( dVendedores[account_id] ),",
              "        dClientes[salesperson_account_id]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "352b9a25-0f1e-4135-b314-9beebf7a6fa5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Vendas digitais 100% cliente - Carteira do vendedor",
            "expression": [
              "",
              "CALCULATE(",
              "    [Faturamento digital - 100% cliente],",
              "",
              "    -- 1) ignora vendedor registrado na venda",
              "    REMOVEFILTERS( fVendas[salesperson_account_id] ),",
              "",
              "    -- 2) DESLIGA o relacionamento indesejado (caminho alternativo)",
              "    CROSSFILTER(",
              "        dVendedores[client_id],",
              "        fVendas[client_account_id],",
              "        NONE",
              "    ),",
              "",
              "    -- 3) aplica o vendedor do contexto como filtro de carteira em dClientes",
              "    TREATAS(",
              "        VALUES( dVendedores[account_id] ),",
              "        dClientes[salesperson_account_id]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "afd83399-9959-49a3-9e20-f83919181d68",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Pedidos digitais - Carteira do vendedor",
            "expression": [
              "",
              "CALCULATE(",
              "    [Pedidos faturados],",
              "",
              "    -- 1) ignora vendedor registrado na venda",
              "    REMOVEFILTERS( fVendas[salesperson_account_id] ),",
              "",
              "    -- 2) DESLIGA o relacionamento indesejado (caminho alternativo)",
              "    CROSSFILTER(",
              "        dVendedores[client_id],",
              "        fVendas[client_account_id],",
              "        NONE",
              "    ),",
              "",
              "    -- 3) aplica o vendedor do contexto como filtro de carteira em dClientes",
              "    TREATAS(",
              "        VALUES( dVendedores[account_id] ),",
              "        dClientes[salesperson_account_id]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "27d5fb8c-7f28-49ba-8a28-8dbcada7db38"
          },
          {
            "name": "Pedidos digitais 100% cliente - Carteira do vendedor",
            "expression": [
              "",
              "CALCULATE(",
              "    [Pedidos faturados - 100% cliente],",
              "",
              "    -- 1) ignora vendedor registrado na venda",
              "    REMOVEFILTERS( fVendas[salesperson_account_id] ),",
              "",
              "    -- 2) DESLIGA o relacionamento indesejado (caminho alternativo)",
              "    CROSSFILTER(",
              "        dVendedores[client_id],",
              "        fVendas[client_account_id],",
              "        NONE",
              "    ),",
              "",
              "    -- 3) aplica o vendedor do contexto como filtro de carteira em dClientes",
              "    TREATAS(",
              "        VALUES( dVendedores[account_id] ),",
              "        dClientes[salesperson_account_id]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "994e5063-9a1b-4fbd-856a-b1d88197fdbe"
          },
          {
            "name": "Lista SKUs lanados nos ltimos 7 dias",
            "expression": [
              "",
              "CONCATENATEX(",
              "    CALCULATETABLE(",
              "        dOfertas,",
              "        dOfertas[sku_created_date] > TODAY() - 7",
              "    ),",
              "    -- Contedo de cada linha",
              "    \"Produto: \" & dOfertas[sku_name] & ",
              "    \" | Qtd: \" & dOfertas[quantity_avaliable] & ",
              "    \" | Preo: \" & FORMAT(dOfertas[unit_price], \"Currency\"), ",
              "    ",
              "    -- Delimitador (Quebra de linha dupla)",
              "    UNICHAR(10) & UNICHAR(10),",
              "    ",
              "    -- Ordenao (Opcional: por nome do SKU)",
              "    dOfertas[sku_name], ASC",
              ")"
            ],
            "lineageTag": "c4390eb2-3512-4866-8ca6-d28c6abf0b37"
          },
          {
            "name": "Nome do vendedor (agrup. vendedor)",
            "expression": [
              "CALCULATE(",
              "    max(dVendedores[name]))"
            ],
            "lineageTag": "5c25359e-4b0c-46f0-9ee4-82bf5143532d"
          },
          {
            "name": "Lista Top 3 SKUs mais pedidos",
            "expression": [
              "",
              "VAR CurAcc =",
              "    SELECTEDVALUE ( dClientes[account_id] )",
              "",
              "VAR BaseAccSku =",
              "    SUMMARIZECOLUMNS (",
              "        dClientes[account_id],",
              "        fVendas[sku_id],",
              "        \"Pedidos\",     [Pedidos faturados],",
              "        \"Faturamento\", [Faturamento digital]",
              "    )",
              "",
              "VAR BaseDoCliente =",
              "    FILTER (",
              "        BaseAccSku,",
              "        dClientes[account_id] = CurAcc",
              "            && [Pedidos] > 0",
              "            && NOT ISBLANK ( fVendas[sku_id] )",
              "    )",
              "",
              "VAR Top3 =",
              "    TOPN (",
              "        3,",
              "        BaseDoCliente,",
              "        [Pedidos], DESC,",
              "        [Faturamento], DESC,",
              "        fVendas[sku_id], ASC          -- desempate para garantir exatamente 3 SKUs",
              "    )",
              "",
              "RETURN",
              "IF (",
              "    ISBLANK ( CurAcc ),",
              "    BLANK (),",
              "    CONCATENATEX (",
              "        Top3,",
              "        VAR SkuId = fVendas[sku_id]",
              "        VAR SkuName =",
              "            LOOKUPVALUE (",
              "                dProdutos[sku_name],",
              "                dProdutos[sku_id], SkuId",
              "            )",
              "        VAR NomeOuId =",
              "            IF (",
              "                ISBLANK ( SkuName ) || LEN ( TRIM ( SkuName ) ) = 0,",
              "                SkuId,",
              "                SkuName",
              "            )",
              "        RETURN",
              "            NomeOuId",
              "                & \"  Pedidos: \" & FORMAT ( [Pedidos], \"#,0\" )",
              "                & \" | Faturamento: \" & FORMAT ( [Faturamento], \"R$ #,0.00\" ),",
              "        UNICHAR ( 10 ) & UNICHAR ( 10 ),   -- quebra de linha dupla",
              "        [Pedidos], DESC,",
              "        [Faturamento], DESC,",
              "        fVendas[sku_id], ASC               -- manter a mesma ordenao (com desempate)",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "c9f9dfba-0730-4b04-a7e4-2687e609bdf9"
          },
          {
            "name": "Cidade do cliente",
            "expression": [
              "CALCULATE(",
              "    max(dClientes[city]))"
            ],
            "lineageTag": "973dcef5-6a55-4f73-a96a-f40a6e9b8a93"
          },
          {
            "name": "Data/Hora do ltimo carrinho (Cliente Navegando)",
            "expression": [
              "",
              "VAR CurAcc = SELECTEDVALUE ( dClientes[account_id] )",
              "VAR Sess   = [Session do ltimo carrinho (Cliente Navegando)]",
              "RETURN",
              "IF (",
              "    ISBLANK ( CurAcc ) || ISBLANK ( Sess ),",
              "    BLANK (),",
              "    CALCULATE (",
              "        MAX ( fCarrinhos_abandonados[date_created] ),",
              "        FILTER (",
              "            ALL ( fCarrinhos_abandonados ),",
              "            fCarrinhos_abandonados[client_account_id] = CurAcc",
              "                && fCarrinhos_abandonados[session_id] = Sess",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "General Date",
            "lineageTag": "634b5f4f-8b0c-49ef-b1d5-a6824d4a2b62"
          },
          {
            "name": "Session do ltimo carrinho (Cliente Navegando)",
            "expression": [
              "",
              "VAR UltDt =",
              "    CALCULATE (",
              "        MAX ( fCarrinhos_abandonados[date_created] ),",
              "        KEEPFILTERS ( fDatalayer_session_summary[user_type] = \"Cliente Navegando\" )",
              "    )",
              "RETURN",
              "IF (",
              "    ISBLANK ( UltDt ),",
              "    BLANK (),",
              "    CALCULATE (",
              "        MAX ( fCarrinhos_abandonados[session_id] ),",
              "        KEEPFILTERS ( fDatalayer_session_summary[user_type] = \"Cliente Navegando\" ),",
              "        FILTER (",
              "            ALL ( fCarrinhos_abandonados ),",
              "            fCarrinhos_abandonados[client_account_id] = SELECTEDVALUE ( dClientes[account_id] )",
              "                && fCarrinhos_abandonados[date_created] = UltDt",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "2d04ece0-096e-46bc-8831-a73a1ef85881"
          },
          {
            "name": "Horas desde o ltimo carrinho (Cliente Navegando)",
            "expression": [
              "",
              "VAR UltDt = [Data/Hora do ltimo carrinho (Cliente Navegando)]",
              "RETURN",
              "IF (",
              "    ISBLANK ( UltDt ),",
              "    BLANK (),",
              "    DATEDIFF ( UltDt, NOW (), HOUR )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bf133167-b9bc-4be3-9ab2-a58bb4fe7802"
          },
          {
            "name": "Data/Hora da ltima sesso (Cliente Navegando)",
            "expression": [
              "",
              "VAR Base =",
              "    CALCULATETABLE (",
              "        fDatalayer_agg_pageviews,",
              "        KEEPFILTERS ( fDatalayer_agg_pageviews[user_type] = \"Cliente Navegando\" )",
              "    )",
              "VAR Dk =",
              "    MAXX ( Base, VALUE ( fDatalayer_agg_pageviews[datekey_max_datecreated] ) )",
              "VAR TmTxt =",
              "    MAXX ( Base, fDatalayer_agg_pageviews[max_datecreated_time] )",
              "VAR Y = INT ( Dk / 10000 )",
              "VAR M = INT ( MOD ( INT ( Dk / 100 ), 100 ) )",
              "VAR D = MOD ( Dk, 100 )",
              "VAR Dt = DATE ( Y, M, D )",
              "VAR Tm =",
              "    IF ( ISBLANK ( TmTxt ), BLANK (), TIMEVALUE ( TmTxt ) )",
              "RETURN",
              "IF ( ISBLANK ( Dk ) || ISBLANK ( Tm ), BLANK (), Dt + Tm )",
              ""
            ],
            "formatString": "General Date",
            "lineageTag": "921a590c-86d1-4283-ab26-8a4a9b54af40"
          },
          {
            "name": "Data/Hora da ltima visualizao de item (Cliente Navegando)",
            "expression": [
              "",
              "VAR Base =",
              "    CALCULATETABLE (",
              "        fDatalayer_product_pageviews,",
              "        KEEPFILTERS ( fDatalayer_product_pageviews[visitor_isloggedin] = TRUE() ),",
              "        KEEPFILTERS ( fDatalayer_product_pageviews[vendor_isloggedin] = FALSE() )",
              "    )",
              "RETURN",
              "MAXX (",
              "    Base,",
              "    VAR Dk  = VALUE ( fDatalayer_product_pageviews[datekey_max_datecreated] )",
              "    VAR TmT = fDatalayer_product_pageviews[max_datecreated_time]",
              "    VAR Y = INT ( Dk / 10000 )",
              "    VAR M = INT ( MOD ( INT ( Dk / 100 ), 100 ) )",
              "    VAR D = MOD ( Dk, 100 )",
              "    VAR Dt = DATE ( Y, M, D )",
              "    VAR Tm = IF ( ISBLANK ( TmT ), BLANK (), TIMEVALUE ( TmT ) )",
              "    RETURN IF ( ISBLANK ( Dk ) || ISBLANK ( Tm ), BLANK (), Dt + Tm )",
              ")"
            ],
            "formatString": "General Date",
            "lineageTag": "026d4651-31ef-4710-8fcb-0fbb55f05bdb"
          },
          {
            "name": "Data/Hora da ultima visualizao de pgina (Cliente Navegando)",
            "expression": [
              "",
              "VAR MaxDateKey =",
              "    CALCULATE (",
              "        MAX ( fDatalayer_agg_pageviews[datekey_max_datecreated] ),",
              "        fDatalayer_agg_pageviews[user_type] = \"Cliente Navegando\"",
              "    )",
              "VAR BaseDia =",
              "    DATE (",
              "        INT ( MaxDateKey / 10000 ),",
              "        INT ( MOD ( INT ( MaxDateKey / 100 ), 100 ) ),",
              "        INT ( MOD ( MaxDateKey, 100 ) )",
              "    )",
              "VAR BaseDiaRows =",
              "    FILTER (",
              "        CALCULATETABLE (",
              "            fDatalayer_agg_pageviews,",
              "            fDatalayer_agg_pageviews[user_type] = \"Cliente Navegando\"",
              "        ),",
              "        fDatalayer_agg_pageviews[datekey_max_datecreated] = MaxDateKey",
              "    )",
              "VAR MaxHoraTxt =",
              "    MAXX ( BaseDiaRows, fDatalayer_agg_pageviews[max_datecreated_time] )",
              "VAR HoraNum =",
              "    TIMEVALUE ( MaxHoraTxt )",
              "RETURN",
              "IF (",
              "    ISBLANK ( MaxDateKey ),",
              "    BLANK(),",
              "    BaseDia + HoraNum",
              ")"
            ],
            "formatString": "General Date",
            "lineageTag": "67f26ada-3f13-4db7-b44e-16e2ba8d99af"
          },
          {
            "name": "Data do ltimo pedido faturado",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(dCalendario[Data]),",
              "    KEEPFILTERS(fVendas),",
              "    fVendas[order_status_id] > 4",
              ")"
            ],
            "formatString": "General Date",
            "lineageTag": "8f96f5d3-6c8c-4b54-ba6d-5f412dd9cd48"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5e114c18271b4f2582bd09238c5643c8"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ]
      },
      {
        "name": "Param_Y_Home",
        "lineageTag": "bdd618fe-cc27-4a9e-a867-53d01a96aec4",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Param_Y_Home",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Param_Y_Home Pedido",
            "lineageTag": "cc0cd80d-090c-4b02-9922-5404907b8a3d",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Param_Y_Home Campos"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Param_Y_Home Campos",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Param_Y_Home Pedido",
            "lineageTag": "356ba2df-2b29-453b-bd01-1f510284b5a7",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Param_Y_Home Pedido",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "d55985e2-bf3d-4581-86b7-5d3438d7258f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Param_Y_Home",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Receita Digital\", NAMEOF('Medidas'[GMV]), 0),",
                "    (\"Pedidos\", NAMEOF('Medidas'[Pedidos]), 1),",
                "    (\"Ticket Mdio\", NAMEOF('Medidas'[Ticket Mdio]), 2),",
                "    (\"Clientes com pedidos\", NAMEOF('Medidas'[Quantidade de clientes com pedidos]), 3),",
                "    (\"Clientes\", NAMEOF('Medidas'[Quantidade de clientes]), 4),",
                "    (\"Receita Digital - Autoatendimento\", NAMEOF('Medidas'[GMV - Autoatendimento]), 5),",
                "    (\"Receita Digital - Mdulo vendedor\", NAMEOF('Medidas'[GMV - Mdulo vendedor]), 6),",
                "    (\"Receita Digital  - Venda assistida\", NAMEOF('Medidas'[GMV - Venda assistida]), 7),",
                "    (\"Receita Digital  - Cupom\", NAMEOF('Medidas'[GMV - Cupom]), 8),",
                "    (\"Taxa de converso por login\", NAMEOF('Medidas'[Taxa de converso por login]), 9)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "73d91d42e6b24b83ab74d63e1894935a"
          }
        ]
      },
      {
        "name": "Parm_prod_y",
        "lineageTag": "02f0682e-15cd-46f3-91bf-7b55d0fe634e",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Parm_prod_y",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Parm_prod_y Pedido",
            "lineageTag": "17808a62-8607-46b2-9afb-75077e1d1ddd",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parm_prod_y Campos"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Parm_prod_y Campos",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Parm_prod_y Pedido",
            "lineageTag": "11953f4a-a7b1-4ee5-a84a-95d7b4baa675",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Parm_prod_y Pedido",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "4396bf2c-4714-4f5c-b24d-d702b4aed993",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Parm_prod_y",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"SKUs distintos\", NAMEOF('Medidas'[Quantidade de produtos distintos vendidos]), 0),",
                "    (\"Categorias distintas\", NAMEOF('dProdutos'[category_level_1]), 1),",
                "    (\"Quantidade de produtos distintos faturados\", NAMEOF('Medidas'[Quantidade de produtos distintos faturados]), 2),",
                "    (\"Mdia de itens por pedido\", NAMEOF('Medidas'[Mdia da quantidade de itens por pedido]), 3)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "62644286b605468c859cb5669385829f"
          }
        ]
      },
      {
        "name": "param_Cliente_Y",
        "lineageTag": "21dd7164-648d-454b-89f5-c19be4caa832",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "param_Cliente_Y",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "param_Cliente_Y Pedido",
            "lineageTag": "d9c3a54a-cc4b-4474-ab7f-b3b64673e93b",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "param_Cliente_Y Campos"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "param_Cliente_Y Campos",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "param_Cliente_Y Pedido",
            "lineageTag": "5cca6545-aefa-4616-ba01-a508ae166e68",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "param_Cliente_Y Pedido",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "4b111e3d-06bd-4b7a-b1c4-9aae99c7d8ad",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "param_Cliente_Y",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Quantidade de clientes\", NAMEOF('Medidas'[Quantidade de clientes]), 0),",
                "    (\"Clientes - Autoatendimento\", NAMEOF('Medidas'[Clientes Autoatendimento]), 1),",
                "    (\"Clientes - Venda assistida\", NAMEOF('Medidas'[Quantidade de clientes - Venda assistida]), 2),",
                "    (\"Clientes - Modulo vendedor\", NAMEOF('Medidas'[Quantidade de clientes - Modulo vendedor]), 3),",
                "    (\"Quantidade de clientes - App\", NAMEOF('Medidas'[Quantidade de clientes - App]), 4),",
                "    (\"Quantidade de clientes - Desktop\", NAMEOF('Medidas'[Quantidade de clientes - Desktop]), 5),",
                "    (\"Quantidade de clientes - Mobile\", NAMEOF('Medidas'[Quantidade de clientes - Mobile]), 6),",
                "    (\"Clientes acumulado\", NAMEOF('Medidas'[Quantidade clientes acumulado por ano]), 7),",
                "    (\"Clientes sem pedidos\", NAMEOF('Medidas'[Clients sem pedidos]), 8),",
                "    (\"Cclientes com pedidos\", NAMEOF('Medidas'[Quantidade de clientes com pedidos]), 9),",
                "    (\"Clientes com GMV\", NAMEOF('Medidas'[Clientes com GMV]), 10),",
                "    (\"Ranking de clientes por GMV\", NAMEOF('Medidas'[Ranking de clientes por GMV]), 11),",
                "    (\"Quantidade de clientes - 100% cliente\", NAMEOF('Medidas'[Quantidade de clientes - 100% cliente]), 12)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "88e8354773984c6da26857d69ffea076"
          }
        ]
      },
      {
        "name": "param_Vend_Y",
        "lineageTag": "677bd5fa-fa91-460a-8b89-d1b2e2b45f2b",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "param_Vend_Y",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "param_Vend_Y Pedido",
            "lineageTag": "8ff22e11-f128-473a-b95b-0295c8462d9c",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "param_Vend_Y Campos"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "param_Vend_Y Campos",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "param_Vend_Y Pedido",
            "lineageTag": "4f011f76-bdd8-4213-84ba-454cc1165b82",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "param_Vend_Y Pedido",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "ac3a5957-42df-47c8-b3d7-18a3361581ec",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "param_Vend_Y",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Vendedores\", NAMEOF('Medidas'[Vendedores]), 0),",
                "    (\"Vendedores com Logins\", NAMEOF('Medidas'[Vendedores com Logins]), 1),",
                "    (\"Vendedores com pedidos\", NAMEOF('Medidas'[Vendedores com pedidos]), 2)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c8da6d171fbf401fb0a644c3658ee3ad"
          }
        ]
      },
      {
        "name": "dTempo",
        "lineageTag": "7700a8e8-8f49-43a4-afa6-2735f7f9e8a3",
        "sourceLineageTag": "[imdepa].[dTempo]",
        "columns": [
          {
            "name": "Hora",
            "dataType": "int64",
            "sourceColumn": "Hora",
            "formatString": "0",
            "lineageTag": "b462962d-5fd2-42a7-80c9-8f40bc5ab694",
            "sourceLineageTag": "Hora",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Minuto",
            "dataType": "int64",
            "sourceColumn": "Minuto",
            "formatString": "0",
            "lineageTag": "1d4f0aa6-84e7-4865-910c-27bb401877b9",
            "sourceLineageTag": "Minuto",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TimeKey",
            "dataType": "int64",
            "sourceColumn": "TimeKey",
            "formatString": "0",
            "lineageTag": "c5a7e619-3387-4b77-8489-2fbffe436c28",
            "sourceLineageTag": "TimeKey",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Descricao_Tempo",
            "dataType": "string",
            "sourceColumn": "Descricao_Tempo",
            "lineageTag": "9a37870c-8164-4ca4-a0ca-716cd55420da",
            "sourceLineageTag": "Descricao_Tempo",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Hora_Curta",
            "dataType": "string",
            "sourceColumn": "Hora_Curta",
            "lineageTag": "e4e9dd89-822b-4555-873e-839796cc09a0",
            "sourceLineageTag": "Hora_Curta",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Periodo_do_Dia",
            "dataType": "string",
            "sourceColumn": "Periodo_do_Dia",
            "lineageTag": "cf905046-11d1-4f24-9ad3-87dae71015a0",
            "sourceLineageTag": "Periodo_do_Dia",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AM_PM",
            "dataType": "string",
            "sourceColumn": "AM_PM",
            "lineageTag": "44a41926-e5db-4d4d-9395-4de64ec3957e",
            "sourceLineageTag": "AM_PM",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dTempo",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "dTempo",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "fVendas_datatime",
        "lineageTag": "39c7664d-4d0c-46b0-9c15-3a35a0bc06cc",
        "sourceLineageTag": "[imdepa].[fVendas_datatime]",
        "columns": [
          {
            "name": "partener_order_id",
            "dataType": "int64",
            "sourceColumn": "partener_order_id",
            "formatString": "0",
            "lineageTag": "318159e9-8da8-4a73-b6d3-a534faea1867",
            "sourceLineageTag": "partener_order_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "c9aff9f0-bbf2-4b16-800e-111a3f134122",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datatime",
            "dataType": "dateTime",
            "sourceColumn": "datatime",
            "formatString": "General Date",
            "lineageTag": "d6f3572e-9c37-4356-a0c7-37c938a38acb",
            "sourceLineageTag": "datatime",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "hora",
            "dataType": "int64",
            "sourceColumn": "hora",
            "formatString": "0",
            "lineageTag": "ce3fcb6f-ed56-483a-b204-a6d130d24258",
            "sourceLineageTag": "hora",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "minuto",
            "dataType": "int64",
            "sourceColumn": "minuto",
            "formatString": "0",
            "lineageTag": "66aa060e-1f12-48d8-8d4f-947abf16cdf5",
            "sourceLineageTag": "minuto",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TimeKey",
            "dataType": "int64",
            "sourceColumn": "TimeKey",
            "formatString": "0",
            "lineageTag": "2a7a492d-1515-42ab-b84e-30e127407857",
            "sourceLineageTag": "TimeKey",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fVendas_datatime",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "fVendas_datatime",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      },
      {
        "name": "fCarrinhos_abandonados",
        "lineageTag": "53c39b36-999a-4f11-aab2-f9d2c0facd32",
        "sourceLineageTag": "[imdepa].[fCarrinhos_abandonados]",
        "columns": [
          {
            "name": "session_id",
            "dataType": "string",
            "sourceColumn": "session_id",
            "lineageTag": "c4d124ed-efbb-4575-a415-abc493eaf22f",
            "sourceLineageTag": "session_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "device_id",
            "dataType": "int64",
            "sourceColumn": "device_id",
            "formatString": "0",
            "lineageTag": "957ead82-2098-4e8a-8a9e-8b9566dc0fed",
            "sourceLineageTag": "device_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "site_id",
            "dataType": "int64",
            "sourceColumn": "site_id",
            "formatString": "0",
            "lineageTag": "57a14ce3-e638-4c9e-ba2d-24fedcf97609",
            "sourceLineageTag": "site_id",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "client_account_id",
            "dataType": "int64",
            "sourceColumn": "client_account_id",
            "formatString": "0",
            "lineageTag": "4bf00613-0275-4de8-9216-36f98641727e",
            "sourceLineageTag": "client_account_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "data",
            "dataType": "dateTime",
            "sourceColumn": "data",
            "formatString": "General Date",
            "lineageTag": "a7fb21ea-95af-450f-be94-5a157195a7c5",
            "sourceLineageTag": "data",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "quantity",
            "dataType": "int64",
            "sourceColumn": "quantity",
            "formatString": "0",
            "lineageTag": "1d6a90ef-c275-4ab8-b7c6-7e5f607cd893",
            "sourceLineageTag": "quantity",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datekey",
            "dataType": "int64",
            "sourceColumn": "datekey",
            "formatString": "0",
            "lineageTag": "40820b8e-5367-4cd6-845d-d304cf673d0a",
            "sourceLineageTag": "datekey",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "unit_price",
            "dataType": "decimal",
            "sourceColumn": "unit_price",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "454178fd-69f6-4617-b375-5e4b2507bbc8",
            "sourceLineageTag": "unit_price",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "sku_name",
            "dataType": "string",
            "sourceColumn": "sku_name",
            "lineageTag": "fa2811b6-ff64-4ae3-97bc-814b02e95a92",
            "sourceLineageTag": "sku_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mfr_part_code",
            "dataType": "string",
            "sourceColumn": "mfr_part_code",
            "lineageTag": "0a9cbc14-fd31-4122-842e-baaf5c23ebd8",
            "sourceLineageTag": "mfr_part_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "partner",
            "dataType": "string",
            "sourceColumn": "partner",
            "lineageTag": "56b1364a-9630-4ea2-b016-731f145b6f24",
            "sourceLineageTag": "partner",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "cart_type",
            "dataType": "string",
            "sourceColumn": "cart_type",
            "lineageTag": "32196965-9ff3-4a33-a3ea-7ec792488380",
            "sourceLineageTag": "cart_type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sku_id",
            "dataType": "int64",
            "sourceColumn": "sku_id",
            "formatString": "0",
            "lineageTag": "7af60fd9-0bb0-46b4-9ace-e7b62abdf930",
            "sourceLineageTag": "sku_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date_created",
            "dataType": "dateTime",
            "sourceColumn": "date_created",
            "formatString": "General Date",
            "lineageTag": "e0290507-a954-4c85-b643-732ea2a447ad",
            "sourceLineageTag": "date_created",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fCarrinhos_abandonados",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "fCarrinhos_abandonados",
              "expressionSource": "DirectLake - imdepa_gold_lake",
              "schemaName": "imdepa"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "17b41455-84b2-6765-5bc6-a29df019e787",
        "fromTable": "dClientes",
        "fromColumn": "salesperson_document",
        "toTable": "dVendedores",
        "toColumn": "document",
        "isActive": false
      },
      {
        "name": "67c4f32d-57d4-5563-e040-0b62a39efcc6",
        "fromTable": "fVendas",
        "fromColumn": "client_account_id",
        "toTable": "dClientes",
        "toColumn": "account_id"
      },
      {
        "name": "6e7b9ad0-77ba-8162-f7c4-21c4cb4089f0",
        "fromTable": "fLogins",
        "fromColumn": "document",
        "toTable": "dClientes",
        "toColumn": "document"
      },
      {
        "name": "51712ab2-cd58-12a3-f7a4-d761c1cd6939",
        "fromTable": "fLogins",
        "fromColumn": "datekey",
        "toTable": "dCalendario",
        "toColumn": "datekey"
      },
      {
        "name": "484e08e5-af88-1151-f7aa-37808bfb17bc",
        "fromTable": "fVendas",
        "fromColumn": "partner_id",
        "toTable": "dAssociados",
        "toColumn": "copartner_id"
      },
      {
        "name": "1049eaaa-bf09-273c-ff66-ffff75c8b993",
        "fromTable": "fLogins",
        "fromColumn": "account_id",
        "toTable": "dVendedores",
        "toColumn": "account_id"
      },
      {
        "name": "cfef15ce-c574-2bd5-9c8d-02947966eda8",
        "fromTable": "fDatalayer_product_pageviews",
        "fromColumn": "account_id",
        "toTable": "dClientes",
        "toColumn": "account_id"
      },
      {
        "name": "4d6d9c1b-60d4-c499-5aa3-c97a9a27c913",
        "fromTable": "fDatalayer_session_summary",
        "fromColumn": "account_id",
        "toTable": "dClientes",
        "toColumn": "account_id"
      },
      {
        "name": "7607a710-217a-19d5-4b95-7f9e1316936a",
        "fromTable": "fDatalayer_product_pageviews",
        "fromColumn": "datekey",
        "toTable": "dCalendario",
        "toColumn": "datekey"
      },
      {
        "name": "fdf680fd-4df4-bc27-c046-0c0217755913",
        "fromTable": "fDatalayer_session_summary",
        "fromColumn": "datekey",
        "toTable": "dCalendario",
        "toColumn": "datekey"
      },
      {
        "name": "52e821b0-7eca-7b39-cd72-ed2e08540181",
        "fromTable": "fDatalayer_agg_pageviews",
        "fromColumn": "account_id",
        "toTable": "dClientes",
        "toColumn": "account_id"
      },
      {
        "name": "882601bb-af22-c5ca-e62e-2dc8ac837789",
        "fromTable": "dClientes",
        "fromColumn": "datekey",
        "toTable": "dCalendario",
        "toColumn": "datekey",
        "isActive": false
      },
      {
        "name": "08abd26d-35c9-0b9d-5e55-1acd7a91daea",
        "fromTable": "fVendas",
        "fromColumn": "shipping_type_id",
        "toTable": "dTipo_envio",
        "toColumn": "shipping_type_id"
      },
      {
        "name": "843ebe00-9058-6e88-1734-f2ea798572e5",
        "fromTable": "fVendas",
        "fromColumn": "order_type_id",
        "toTable": "dTipo_pedido",
        "toColumn": "order_type_id"
      },
      {
        "name": "42db6623-3428-e37b-072d-2ecc1d4266b4",
        "fromTable": "fVendas",
        "fromColumn": "order_status_id",
        "toTable": "dStatus_pedido",
        "toColumn": "order_status_id"
      },
      {
        "name": "bc24766c-a5fb-71e8-b37d-aa9c73a24aaf",
        "fromTable": "fVendas",
        "fromColumn": "payment_method_id",
        "toTable": "dMetodo_pagamento",
        "toColumn": "payment_method_id"
      },
      {
        "name": "13ed5cfc-43ca-71a1-6b6d-7a400fbb6f4b",
        "fromTable": "fVendas",
        "fromColumn": "device_id",
        "toTable": "dDispositivos",
        "toColumn": "device_id"
      },
      {
        "name": "c023ce1e-f6d2-c1b2-2ee0-f15306fb80ab",
        "fromTable": "fVendas",
        "fromColumn": "sku_id",
        "toTable": "dProdutos",
        "toColumn": "sku_id"
      },
      {
        "name": "b2f9181a-abac-8ecb-2a13-a7d20f9b4798",
        "fromTable": "fDatalayer_product_pageviews",
        "fromColumn": "sku_id",
        "toTable": "dProdutos",
        "toColumn": "sku_id"
      },
      {
        "name": "31a658b4-2ac4-1386-737f-7436d40af29e",
        "fromTable": "fDatalayer_agg_pageviews",
        "fromColumn": "sku_id",
        "toTable": "dProdutos",
        "toColumn": "sku_id"
      },
      {
        "name": "5de9a99d-b23c-5e3d-3fea-d479d7e1378c",
        "fromTable": "dAssociados",
        "fromColumn": "datekey",
        "toTable": "dCalendario",
        "toColumn": "datekey",
        "isActive": false
      },
      {
        "name": "7cb21244-b759-097a-00ce-0d9468804d24",
        "fromTable": "dOfertas",
        "fromColumn": "associate_id",
        "toTable": "dAssociados",
        "toColumn": "copartner_id"
      },
      {
        "name": "ed6461e5-b43b-77c7-935c-f7f60f8610d2",
        "fromTable": "dOfertas",
        "fromColumn": "sku_id",
        "toTable": "dProdutos",
        "toColumn": "sku_id"
      },
      {
        "name": "7a0147d8-7dad-c879-1eb2-c95c6742e4e9",
        "fromTable": "fVendas",
        "fromColumn": "datekey",
        "toTable": "dCalendario",
        "toColumn": "datekey"
      },
      {
        "name": "d4e13599-dcdf-25ea-47a4-e41bd2040230",
        "fromTable": "fDatalayer_agg_pageviews",
        "fromColumn": "datekey_max_datecreated",
        "toTable": "dCalendario",
        "toColumn": "datekey"
      },
      {
        "name": "26abde0e-defc-72ca-881f-e243238de1c1",
        "fromTable": "fVendas",
        "fromColumn": "coupon_id",
        "toTable": "dCupons",
        "toColumn": "coupon_id"
      },
      {
        "name": "0d1e4287-0abb-99f2-09d7-a4463bd1d1ae",
        "fromTable": "fVendas",
        "fromColumn": "client_account_id",
        "toTable": "dVendedores",
        "toColumn": "client_id"
      },
      {
        "name": "4c4c6a68-8222-e07c-67c0-7c96b0640e6e",
        "fromTable": "fVendas",
        "fromColumn": "salesperson_account_id",
        "toTable": "dClientes",
        "toColumn": "salesperson_account_id",
        "isActive": false
      },
      {
        "name": "8da56d60-0395-cf8d-c507-0fc7654040fd",
        "fromTable": "dClientes",
        "fromColumn": "salesperson_account_id",
        "toTable": "dVendedores",
        "toColumn": "account_id",
        "isActive": false
      },
      {
        "name": "da9b4da6-6edf-ed48-b1bc-c5d84b26ce88",
        "fromTable": "dCalendario",
        "fromColumn": "Data",
        "toTable": "dVendedores",
        "toColumn": "account_create_date",
        "isActive": false
      },
      {
        "name": "8b33f3ad-552a-907b-d0d9-b9d86d2a20a9",
        "fromTable": "dCalendario",
        "fromColumn": "Data",
        "toTable": "dVendedores",
        "toColumn": "client_create_date",
        "isActive": false
      },
      {
        "name": "42c7f6dc-99e3-864c-d6fd-ee88dfd21133",
        "fromTable": "fCarrinhos_abandonados",
        "fromColumn": "sku_id",
        "toTable": "dProdutos",
        "toColumn": "sku_id"
      },
      {
        "name": "94dc303d-1fea-1c9f-7cc5-72682710d807",
        "fromTable": "fCarrinhos_abandonados",
        "fromColumn": "datekey",
        "toTable": "dCalendario",
        "toColumn": "datekey"
      },
      {
        "name": "cb87b03d-b488-d232-76cf-aab36375df68",
        "fromTable": "fCarrinhos_abandonados",
        "fromColumn": "client_account_id",
        "toTable": "dClientes",
        "toColumn": "account_id"
      }
    ],
    "expressions": [
      {
        "name": "DirectLake - imdepa_gold_lake",
        "kind": "m",
        "expression": [
          "let",
          "    Source = AzureStorage.DataLake(\"https://onelake.dfs.fabric.microsoft.com/abcbaa19-fb1a-4e91-86e6-5297bfe42be8/5d7f9546-bb66-473b-bf1e-7a633840385e\", [HierarchicalNavigation=true])",
          "in",
          "    Source"
        ],
        "lineageTag": "32a981bc-21d2-4075-b85e-41228e16024b",
        "annotations": [
          {
            "name": "PBI_IncludeFutureArtifacts",
            "value": "False"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DirectLake - imdepa_gold_lake\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "__LastRPTime",
        "value": "134135701932131029"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DirectLakeOnOneLakeInWeb\",\"RemoteModeling\",\"WebModelingEdit\",\"DaxQueryView_Desktop\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}